app:
  encValues:
    WORKER_PRIV_KEY: "AgBcXZQl94ia1oA5qoQKULlPWsQNyKR7ywIRnGUbsSX2cN7Q9iB6W6vkd4wJ3LEKdueBBjjHYGG4Ta5eotGu62Hfi0J3Oz2vsAtuuHpvefTex0fcjoCtW35qPNRoVyi35oRg0HC9ONHTMHL3HDTUxTzDZDjErwvIz6sVBanHa2CRQjYceY/VlG05wg5Gv7uamqq2flqQVM+KIggFxcy0TvYDc0Pz2NJ/7h7oMThmFIm4E3MSnp9TiwZ2N42urup+nBGN50NzAJ6AzU3az1ouo6UPXWtZDdvB/MPR0yVHnUuS1RtKIrYK3h4YSCtf/NRPnQdr3H0gPHP9tJ8P+H+FhlwTzc/Fgb5yNLMRTbdXjTr7A5f8v/vL5SXLwYimVLUkXXZ3hqVt5iifOo2eE/LTT5HLgZzXRoflE6GjrwFLUvsc1NmPBFDOpv8p2D7xBUhSQ/x/fDJ4EO8H0bEoDGAHJMOx5EdAvU/U6aKb4xaYuigz9oYmG+3DtYYTHHKhThrLLjZgHOO2O0I5Tu1wmYSob8Bth40g5HGGm2PUdcPCZ28NLrvnspiLuMD3nhq5HfJGhuyL/PLoMx4OAlsLvi6+SglmZz71GNRUCAGa5tVVHe44yx2YTrAvFb5ymHKAWr6ZvGtOPjIfughM7d/UtZt11Tn9Y8f1+SITDUtxDBoZ4bAqK2vFjLK10cr3pTQy/vBCkF98oCUKNDTIYhp4eIOQpEJi7WPsCa7kpH7ciRuftzEhTBf9cOA94Xt6d/FcP6mg4PL6lZQ04CXFuWV6WHLH6HtOaDwnGR2tFvxtaHxmxzIet9ST+0xZYoC1myrArykB/LF2TQEeFoPqAy/bRvYR27TLdt9ACRZoDPkM2ECy2Kr/HMAOvAUen2WJnDv1SS34w4SC3L2SnVLsSVO8lwXWLqwQse37NTL6tfZj4rCEQJMj0V/cWYIVNb8NBVR2R4gVtNy7oIAu2rqd0/JCbsoikdxfGXz/iNY4d36TayO1altk0Eu/6ApKblSXGxoeNFR4Nx/Hz2fSlU9bAZAW8BKUCJACt/9bu3b/RPQEU68Pnw1yUCIaxvcU6FOOLos4QSX6VNfZcAvLDiOIR+dWW2kxZd8R0BbYqQ3BIcMIQDKfs7ksLuDDO3oX76EfMamLisSilbnFd+GrtqnQnOJrkAVz9BLGNLSX3u/kwNf6g8SrhUGRZIrh4uMidJf+XHQLTTRNtN7slHmkZL1oxyEexTZM1dPHQam+vRCrjJDsbYFQJDpNFeWnSVE4SqpUhBLiLK/NWlBqbDLbGx+UMDkYdhbbNafKDCBRoYrwApL+/dp3KnOG5MImD8Sd0gqRtqGPWlX0w+0rhuFjhbpFWsNSf8bm/IkjfPNZ+cTKX+63j1BJTbSkHM+OlDAAOJAjdzPSQ1Ods+5I1SnmJq9FDdRiaaTe0NskQA8AfGwX3ZhmgFcszptcEO5jMf03JMJ6yjFY2U3aGu8BSUDN7ewwe2msa4V04CqhfZH9oNaub6w1tp7a0NKKcu1898d5fFqc0Hp8g7RtCdNHedzWoSWQAEMbcT8KnYnmbCi93cynYBZVxITxFQh1IXNM4IfobN8Q+JbJ1/XpCMqMI/j3QZXvhcVJ4cdXBjkNcYd6fcApAFK9FlWgVVa3WmwnbzlpYa27YW+/WnCAZWd6nUhghKk2s1zxK6OKYv+BlXEMNTTMI46gtJZvgXGuTKbKDkMj83AGrLp+bVM+5r7kbe3o7YUEl9H5WvqQ3/n6puEELYeAVkRn2LoFmY3aVMx0IZDHro0yZkJ2laQmYCT2CxZPqK7t4v26ZL/Yrc2qpbzmKvIghkPeUoQ3YoxqjbcL8zpdNufKwmX5G0sHNavi27loMO9J2UdSjtdU/ALcJ9qEkPqYOQ=="
    MQ_PASSWORD: "AgABH9D1GsGbxx3UiBDv4uQeihhk6bxnl+2q/uQEYRyU23NmXZ8x9iphKohkjdkozBiOF2CFPq4DZrMOqgSZBiFJ+i4Ylu76u1A2K30jTltahO9sBVUWpAWAVJvdJoyLqIPIDvGsmyhxuxy75NLIz2Zl3lpMQxIAl8VkN87sVdaYdEcZfMHwuMeWVpftQlFS68KisN1yhhqt6grDwwOzg2Z97mMsXT97P0qEeoIYV3YDa4DLF07DSEjU++G6Nm0GFhXGgQOzw7TMUoXTNFbK5MSQ2ptNJU6D4KCGDk/NrtGYQrKojNH9l9deyXAMLeSsv9C1Yn17hYaBjPSvvdAFZZTBeQrhNZQ8JvfM34z9pm9HbIBNCi1xyJpxgBbpA44awjgRSVt01ue+ZUuIMVKYlV3eqj5GpTVGe8u9u+DE2BQM1Npmnxxwc+/96hmnhh4z97lsq8sf85DsyKf/ymOVJHZrK+DVFwz0FoT9GrZblbqdRtEBs/jPFWwPeW7v5L2aY3aL9Zjdrsbm7fdZgTziJg1/Em6eycKSjcDY48hZ8Stf/zZqYZH3K/7TlrJJP7zekj0pgzvWT2hdHaJpT9Dq+WS0HxqE0MndiySYKHtFTd3cgo+wZu4Vh+0faWDUjiNL6jfa+9EsgMb6rUbLx9vwQhS5L74RrPgnVMNQ+yMPiiGl97PjNetTRHH6renetCoOzwzve2VcK3p5NxOq"
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-testnet-app.apps.svc.superhero-prd:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue_testnet"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
    tag: "1.0.1"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
