app:
  encValues:
    WORKER_PRIV_KEY: "AgCMB4WPJVjiLdozLnkhBjJH0966b3lBhT6IuKB5cIzjw5Z9E2irZTWOkPlEDz1bq5DFRgUTevIMY7NoIOVzs5r7pvU1TG2izgoDAHbfMCPli8KR7GtQxpIn8LzcauZ59qxzkg7Trgup/B8XCvJYm8/G2tlFQ83JAlssQO18yYGaTMy6kCfRM3iw+aOpODa4UwTBfXNNV7iWGQ9MXrVer7IEd/ovoDw62FR9DALKRoKsilPOisOdvXvV4dM9FqR6YOQeQh/bJontk3Ee144uE6UDv9sj4N2OUmQJr+P6F1M/ClpNHVz29DfzhdLTXqJc4wPODQLCbIOvQ9nEAKHWZbLRvAWXL2lqhVhOQN3cUAzcACxpKtQHDAmU0RAAJCIDJ6ee3CnmOCTMCfHu7qBsaAB85kT8Aumzm+MSYhamKgc+es39qKr7EhyT+Jqb71J/tBHON6PB7f08PB/sXVS5NHS9lgB8lKeShao4gQvDsKHUMDe9nGIeG0R9Zbj1r8JSGpieMA9coiEhhkIqUdS36NmCQ57NXeKk5bPjpWzg39fmuXCFny7j7vM19lEbbC0N3+iPuwAMj1eZMm4gh/+F4ynWr1QP2gmxjnxj55zd/tk8vPlG8s2TCLDtyUit09sDrTMP+vym5XYPheS8lFRDaK3grqXzOCeiypG8dd10wlZB52TFxd9qpfrRe0dPUGBEkVxhnjj1BHIlfX8X6q8BlAB4rdBJNZUBB98aKX29/KTtSSXjKOFKQnJ4F97DFpgRMLcXMP1vNohOGSRsrJ6IeHVLqY6mwkVDVWaOuP6ZkoI0cIIh6z7De1U0TTmX+P0mrbsTsfzapOJXxgoBiZAT82TaTBp6b3Jqbcmp4gatqp8Yr4uYYlAHG7TjoRjuqeASHd0YzKSqSrlIZQT2f6w2Bp54zyaVMY71tv+NeoD92JJq22c4UejC22QSSCAomV3oOEYliRrZ/WOi07pXAPq8O1hod58zybyCZJwnZXyvbTTLbmADmKJqd7fopbvdnYZr0gIYDoSf8QFEapvVpTckfrNwvqgfMcTSON/r7fwJbpQ7HF1oUz7yEyB5ZO4C3lXxHJUhLihVofHOoPNLoc9hlzq9ecNRssFaZF0sesUkrusRte7gacAaK9Bz+2Fk7rsGLWzBYzobkH/mRxfN4gb5RciSksH+7oIiTlX9vVkeH97ZjN4TAhh+K5MMLEcdqUT+k7Pa8m7LgOWB96AN72SYjb7L2PpVHZZKKsfU2eEJJMEvTCWl36EYDrZKiV8MlPqIGTM6sR2+xB99Xe18DsDrWXBT/7wxbtCJBdQu32oO9C8Js52CzNoKr0h/tQL0esVTe+nI0JAPhxYxd74WXQCiQZRxrbPjQJX4n9l5CWV5HCpGdbIIwNaMd64NvEqWXeOAiNQmhNz1zQA+fw2u437d3zvxZcd+cJCqTifn40x+xL2NqDHXhMagmyihatwdYWNtAYe3Qh30eNxpD86DkZRMaaJTU4YnVvlW5mEjXMPzdobnti0K9oqS+kf/X4+JbQBK8zdrd35me6WFTxRUY6cwJ9AN57VwCIZEf5Z+3FVZ5ihPYpHOWu0EB+nUy4gkXg4XdlLYqqbPRAU2fx7XAwAmJyMHh0qPjWkvCPl6kuk3ACCbrnt9lQSbdQxwu3tRZ/4iUOt2CCP/SOim+ndLZFJ9cye8tDqcHXuxwN0Q/1ZY9OAFMsEbk99vM6RnEZti57PJheFrohNBkFZWuYqGngz5Iqbvtt7FNAg/dRX1qqxxbWR5QAKk1wzQPNDPYuUsi9mv+GzXe7KuBNsaZ6nqwdhylQmJrK9E6tq3f9RdCK5S0li2UCBOcAX5uZJSNC766YIgMCA9W79X18kUobT2D6/n6pIvy+sx4D+w/etkqw=="
    MQ_PASSWORD: "AgAc3MqvBItlm4bQw1ImchQ7bpxI34zggAVypbcC588NYjczk2zldKfbHAr0pY3rDkaH6O+ut4MfJsoP1hLPIrznHO4VSTpTcH/bHfg+YGFphbzbaXlSRR1F4spV4O6bLB7jTt44d+g/5tlvFgQIKgphrW3U9LT3tVmrt42lPi/eIWQcOPqIKz6ZDy4OqkGKPDXEBOdM21MDv+gD3S3WHKS3ASpKQzlL8CBHo/SOWA2SejuhWdf1sLkr9b8ue/xMtmy/1syiT6c4tqB9DmPG7X61FBdrVJYMJziik9GjiVXo9BfF9vthzoz8nFBLkpEBa/0AeZwQ7IGAZt0f02urpCF9n1QqkoJrqFqrMPLjaS5KHKC9wFRCjK0VCCuInUOGZRS8W7P+W0Jsvih64PjiLRu6Mv/YL/OMSdNR7du932DkgyM8Mi+JwVdUVVU1YWH/9YmzFCSb+X4igEPDqStuIkHqpkQaJqXEmolciaIa69EDmqOEzlwPkFxk5xGEXoV8d6wAQxfm9V/dczz+ZjJr2mdzZnrhwunaa6UVTWZf+bhGixj9vwy/YyRCxaepXRtLK7/e8rlxihfpTzpQTN+LvNgTnRKBlB8r5YjhD9GN+nYu1ORbVFhCCaFwZaKhbJ8FRBTG6NwBBKjEaJI4xJAP+oavMjeXjGGmoQ13iLaUL8wPMF2xjg6SzpSczoQmVPFVa0nBUn319nqv0sQsaBlcQ/9H1/4q/W8kPPwK9ZE/SKc/ag=="
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-testnet-app-develop.apps.svc.superhero-dev:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue_testnet"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
  versions:
    - {version: "develop", gitSha: "90d5c25"}
