app:
  encValues:
    WORKER_PRIV_KEY: "AgCF+jwsOY10W2K/h3Oxi6bruMmDzofmCVXl/ojxiGUa9MH0lH8MkvF0jseNgaRitUWTFQhaQphWW+m2BDFGr+jYXblNNhVxiUuHwQlYmIM1U1z04iiTRewldTsvz7xO6Y0lmIK4RTJR1Wp9X0tTik+hlzVSN9I/HJCc7xLGpuurfV9pWXn4Wyu57IokqtH4p+NoaPXm2QiBELzKEWrjre62H6UegC+wQ0+rX7iKb+t/BKg2IB79GsNQ26i30fwDBnG47D0zGNbGF4GjYFvXUI2ZRFyOOdFVCDYV9OUh+FR9N9vz4ynoyTgUtv5+sQsjzErf8pzuNbfGloCOHSEQsB4yJFdo721Ba2XIab45vPYv4LmFgkXgXYEFajUOmMvsekiBQQBUZGwYb4TbeDyvakBUUs2mU57ly+JlTjfK9IaXOmQq+yDJmawkz6l1qbzn1SC7mkFtgfD4CBOCSiD3XCZgd1jucF2Z6CmTXiYtaKMjkF5VoIKNb8RAUEEBSsQdL19s6PwV1IhugZVCz3OceokEFP/lksyoIuRKF7z5qGbsCeCbyy0XA0QvAlSmjAZqOm8rOtMbQMsKJIC5ACZULJeMv39Kor1ZGjmqAl8cNTX2kRqzrlmGU550x5QHgPJ/tx7pbwKQ0exVbQZrnE1P8+xtYPhOdkQLFY2BVBQqsucFuxhwn6Aby+/O7Rc1WxsK3WRUJrYizkpeBq4Tvpy2JCZ1KihsmuEv4oWsQixdfIS+EBga4n9WziM1DH1eFlGscjXLL+AZKUfv2ApC1Z4C/Cpj/XfKyjrDBBLYDDdF0NxiCGCLH/N7DSU0qnVgWjYpsO/4dAAKQuzSYUjh86SGz/0oGb2evrbwKcUzLU6vCaRGhjubaG0nDDfOc6FobFF1alDq4EwSmHocMWuQ7HqlImRJB2hVjBbRJRymhk/awQZf84O9Uh9tKz2Q4bnun2x8YBPsaGxBfvQJ4Znea95QvvK3MxBL4Po19aeYxEeV/+F8w8MJ7OpY3/IHCHOgtNfcVSMbQnQexUOBhxIF2gbqdM5wQzv7e3SMCfIuLw3wIhbY/vRm/wRLPTe/7olq5JtTtl3R25YHFHhvqZ+QPafwLNZ/mkcJAcS3Fr6XFuO04oIOEPMwgs0sSdOjls+YWNdTUhXXgJbm9kwVMT5Bp5UBhXmMKpMolCuU93sJMZfrN1LUmqhletER9JoXD5jUETMlk2TaZR1SLNnxjlYkgM6a9m/xOq+PcGQ226HDOmrsW/iRNPgcS6kflc4A1ArleS4z/XZbzlWy6HLBjNPJDku46diqo/eFKu4jAf/P5agB0FOR7/OYZpAdp6djw979dPYzxD0WsheZ0Z/5d6/zXfusm9D3UlF4+WSjakpXFr5n5TumuBaR1YOJ5USa3Bua8JP2elQx6CnslABM6lAM+5wjhZ8H9uVQ1uUx8S7u6WqKDcq2Ufm5xJhYKfQz2Oflf1weeOelrybqGFoCrIBmLvdmybGe+adJ2j81S3aIW3SXKfUtmXvGnZE/WPJ/R/imfHinm5YVeBdO4SnHDabaU2ifdyL1XWmprdtC/XdRiURcn8LjajoqJROL1eP6hsdw9FfU2yA/rTNJHhLJin26BXTKi/1bF/zeA4xWdfqkmDFqYQVQvm/hoh4lKVA0T2YM02LdnshPBXP7Y713CVdsA+LX67UFu7zTjm8FfrIX53J44q5bqW2FMOBHttRH+bkDGkM2qcxYdoG7MnF923KMupHjMpg4vjBeCGjdcmWBxBQ8CYGhLi8Wyxl2kVlJ6wZbZacto3fxz8SdsMQ82iy+p0ns0yQL1d4KXfRLoMAGTQJDOQXD9LN0FVbhv8HvDt+rSlqOz7MaEcQBJnmFNtJWbxmDBPdsRJ+VcH9tkOntTQ=="
    MQ_PASSWORD: "AgAqX1OsWQrIVZUDQ/ALTu4zL5WmJbjX3RMDDWdNMcK6pbYn+bhKRCt4+FqbqwXqCf1WVmFKsUFtAnLrjmWUgCsZlug9jG+8JWaz+k2f97T/vFyXdLqn5MGnZDNrbMu2SDzkON8oMTD2P9aR0nFyX1wOoZqfuDOEWU1jZ+7NUyXLEMz3VOMd8zgUWKfD0HebQ+mgSjzXimyyTatKFj5DuYHVFvbw45imdaQiIPqe7yCSQ7GM9OmOo9Md1Effq2ZTP1GOxazKMTVPTVovC0VAP24Ci6fa8A8QIKu41OylYG+3urroVU3VJSWP2u5Y/nskVfMhNbzZ1kvAwLPI0sOwu/fbn8F4DwUeue8TipOUwGei/8vAVZTyF1FUkfxI1k6DMdcAQ9jYfkvw5hhcxSbWLt/tz69EkIK7wByqINfb4sRlJuY6r9OQaKdtGFb3E5UuaelhgnxaNUPSzq4qXyR8tajPKpCpywgc4A6T0SMuoSCETTwWNhBDIRNI9YuFH4dcKm3cmTrp3Svro/e4LmtE452cZSksocLbIdn/UDk6YfLf7VVKQsq3yav19vktDdso4nSvTDemrHQ3eaTkeEu1quA4Sax02p0DaWGxAT53vR8S5h/TpEjX4jCo6JvfPXZW+NWhd1wZejdStyk96czvGADfZ6PYRBkDBhjF+nCa2hfw9REfoDmWJ47C2C7hn34drsr5z2IvEXgyliFeRE/jfquCSLNSdsWWXYSvZS5X4YeXXQ=="
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-testnet-app-develop.apps.svc.superhero-dev:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue_testnet"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
  versions:
    - {version: "develop", gitSha: "f86c2ac"}
