app:
  encValues:
    WORKER_PRIV_KEY: ""
    MQ_PASSWORD: "AgAqX1OsWQrIVZUDQ/ALTu4zL5WmJbjX3RMDDWdNMcK6pbYn+bhKRCt4+FqbqwXqCf1WVmFKsUFtAnLrjmWUgCsZlug9jG+8JWaz+k2f97T/vFyXdLqn5MGnZDNrbMu2SDzkON8oMTD2P9aR0nFyX1wOoZqfuDOEWU1jZ+7NUyXLEMz3VOMd8zgUWKfD0HebQ+mgSjzXimyyTatKFj5DuYHVFvbw45imdaQiIPqe7yCSQ7GM9OmOo9Md1Effq2ZTP1GOxazKMTVPTVovC0VAP24Ci6fa8A8QIKu41OylYG+3urroVU3VJSWP2u5Y/nskVfMhNbzZ1kvAwLPI0sOwu/fbn8F4DwUeue8TipOUwGei/8vAVZTyF1FUkfxI1k6DMdcAQ9jYfkvw5hhcxSbWLt/tz69EkIK7wByqINfb4sRlJuY6r9OQaKdtGFb3E5UuaelhgnxaNUPSzq4qXyR8tajPKpCpywgc4A6T0SMuoSCETTwWNhBDIRNI9YuFH4dcKm3cmTrp3Svro/e4LmtE452cZSksocLbIdn/UDk6YfLf7VVKQsq3yav19vktDdso4nSvTDemrHQ3eaTkeEu1quA4Sax02p0DaWGxAT53vR8S5h/TpEjX4jCo6JvfPXZW+NWhd1wZejdStyk96czvGADfZ6PYRBkDBhjF+nCa2hfw9REfoDmWJ47C2C7hn34drsr5z2IvEXgyliFeRE/jfquCSLNSdsWWXYSvZS5X4YeXXQ=="
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-testnet-app-develop.apps.svc.superhero-dev:3000"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
  versions:
    - {version: "develop", gitSha: "f86c2ac"}
