app:
  encValues:
    WORKER_PRIV_KEY: "AgCVqWoWKQR/Kwt5NuYbJt0x8Pb0NdDwB2qch9s8QFfA7ZNNHklXXsy+oq8OlYE+N+w3kunpP6IGNXwIFu5gk/Otstjc8ykMPKVSe7iaYRTnp9xjQXulK5QBsfubXzuxYSqUM6huxVqXhhMc3NxtaBUuiuCjdENEQvxd/Bz7k9r77hbqxvnhmscV21723YPf8rHTE+xLCK7HkMxVhpHTSSIKftfbHjF0+yvEOrKm8n996mCrmZvhynVVk/uy4FDr2qLJ99wrjN4TopShn9y25GF4S9gmoUGrf9IJaKd7a4hlAPzkfMWaEgM2YsdPFs4mzav3rcCdD1rWQ+4ZSKbDHuDJL+bdnxsDpVcd2/MnZQVKlL56GaIDaoZ4gWXUPT7bkKBD2qGrbnQRzMFi4ZJD6BjwttE+gqcOUmJme0ydSGb5rlY13wsgMvMyP+Gf/VfANO+t1JWbNEO9yJnp0j57n4xk+eT+KX2WyphKabMWoHXoVeUIIjaaQx0Vaffia1eRJAc0n0SBM5b4TWkDhptK1Ny4P2PCsR4WF/3tdO3qay85fKcvq3o/qzP8FMoAzaIc65H6dMIGrIxBDrndflr5A1D6CXsV7GABS5BWUWvawOLq1Eq9juDpHvouGvqtY+RNMRCqcgTs9gFErhy16gmlJ18Ku3pB0q+VrS4McEOml7iPe5xGorg5hhHsJH/WXYJOEvhQzZEFuxmp/QgShl4ZW9X13esNBQlFA3r7kMeT2QeMZxgAXUetAEL1ivRip6Esx4rZGaGI24wBa2fQuMkk2EN0WpyXRpj8b6aUJP3nTvRNjaaTQ2xvrtScu34Ll+OmOtuPYzXKKHZCpzd3oNBuAOHTsPrgkU83GpPDernEu82VMRxkJKuhOLg9ZStSLt3V6vJRBhiQ4dpLw0V0znbnPoHII8bUaRIv1aowct/AKQZzBaT4bgqduTXUnOPIoHqFNeX0ANs6ZUMNsrxBaUCiMgMP2BiXlXVB8UHAc1NpbIzrARK2zA63UyskONThSZiosjcD3m5+WSQc65zDhjEO6HV2e6C5gf0jVzp8g/2S5/CuKu/C6UWh6p3/wQRgeul1i5Bp4C2u9SubvY46idHIoyauH/w4FrugY49lmahzcGqpMvdD7xjV+G5+y67rPO3q60qsDrFLMVx9Hg/0yj1em3s7OOO5u7uEbMG/fvI4ffPHTrkBFdnHPBboggwLrB+w1+n5bsLeeZRrJN59omO+GtDVE9G+SBAXXMhEZJgxHSL1lQ75WPHSUQ0EAci+Tjzflx28TXOqxvA/Mfg5+7PQIG9JXFpgVVZIAsB3ERybego43BspNBPYvjQCI8tBMijCt5DvTGnjKrZ3CDphx19UYkUu5c2yGkZbREvBd7GfWW6gTr+Z+ZbGpW1Y4I5BkSodWcnV0+vg6tSZ+0uJUTOUbZh+HHezgiLhNnq+dXFTmGGdo6VMQvPboYctHj2L62elWUL0AbJYltdyxG2xGy/AmpoEW9+llF1QJSvszLLUoViOW/2Xm0TjFuYt4H2xI644SEy6MFcWEdyiwfxtahPH3q6CzaYBD1QQe5lUNebI75rZXifzj+C9yJlriwiDw4jxKU6kT5GaC5sLTnlqd6ySf5tEUQ3BWg94bvtEKGvBcSdSx29SIXRFv5F0R1qOBNd/NJdNmodun4i2Lg2x0fNIjk4OT5dgpWewbiVF4AzF25Pkb2hdsZpGhO/M/p19NzxFW+gsTOWe683TtGV4Uo22DBzWzNKX4o6pAgWRQ4y+3bRPe6/B7ZJuMl9q2n9oCIoNW+I+ALWYkwcVFplnq4DbhxTFCoCf4QW4YVI8OrdD4Fw3g/VBdywB+ICutwZRexzLeGkihAHWTsW75jDmi4FFHXcDg6ahcHOmrA==" 
    MQ_PASSWORD: "AgBH0Ybbx2Ev9Ybz1XwpuW+IqbPeqtft7G/qWTyKYCbeqkuk4JnRpx9pEoBsPUd2UKjENhN6jwLYaLH5Dv3sRR8Q/mUBkBqA/Uzfz/3/bMhQO6KG7+mlxfAoeFufgY1+4IqLfpOoSBqXxCBYUiag5orM7vDUyPLJZ4aXNFXDwYiPRuoPWE1S4gu7msFvFMAXgvYE1bl3jTvVdWBJtf4wdgZxiCdwl4yVfK9mm9VyVmJtC4GjVuv1bZqJ8WINXhDp6DeKbA+uTRKiuHUFuY7w98tUdhYU+jTE5y8yLWtfIE2d6Rk1Xb/f08MdBH+RDVDYO23C0pSVMFnBbGFussL5Hn7SNcSxChpjCvHyOviJtloFLsN9zych3hJtMw8MPutmNZIq0/IepXIlVW4J9/hWO+qOi5n+O1fpttSSEShwTqIvVJCovBLtG9ixGF+BSia5TYivVBbv7TY3ItmN1U3IENpfglS6ykRXcOpfR3laoJkMpl5EMQEIW3RTfRq9AxPuDGeQbG/ecTH9vuN5jIcg1N9aEyoM0n3zKQfxqFH94vmFAF6NI2VYvQam14C8DiYb3l2eOOIexngYf89/GLX20yWG/fi2DvoyALq1WCLoMIYChtWkjLn2vRS8INCUfPTu5wAyK/UodXeDxTXwLrW8sADFH5/SDBuGhcq7mtPygeaFCCCWeVGJ9z9AvgAuo8Sdk2i6ZqyC3F/iVNn+Qg=="
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-testnet-app.apps.svc.superhero-prd:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue_testnet"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
    tag: "1.2.0"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
