app:
  encValues:
    WORKER_PRIV_KEY: "AgAcklYUR6ZmjxgbJYSkaM8j22ua4a9WbTlJSojV7YAZnteOqTHyyCutcDxRy4q1SWsUuMILiARNA+lEr1wbsEGDd3kVCnf5aNXYM6c2iq9DxD4UuoPFgUMDBaaoZtSYrpBRhY2jvK21GmtyxDR5dqUcqQs52OqtOW3KY4X/dkxT4IMt4frEQrjqyefRkhbHwiyu+J2TuOt6WgmoKaoyj3kIQLc++YCwnpe4WnuSlnTmoX83GDEzuXIg6ZbPFPy0Idoj0ob8B2B+sC8DKrBhq5DWsFMQFhImj2kyDhwcZbAb8CMOmwsLeyfiS3f47c3HH9jzuN5yWEY+RteRTkFgE0jrtsPjuDf/NZFOCRbVe4P3Xe7tBsW12VKvucAyv8GyGMoqPw5v7TNJXbhX4d0uAZQO6pLMI6ZklhJ5UfGoO6A2loS4CEY2W/cj/ikRde9P/MO5Jk8aQtMkXTB29p81Sy/JblULLTy+RIRftNme9Olpd77g9aDJsl1EEawNi6BZQAOEnGEFWb5cNJzrrkmoo56UNkM4v5cpldGErOazL4VzeT/YSgasVnEIAI+BiwXKFmID8QUyhKGJvqEBdiF+wglGbNuFSdt22iNntl3hyxT3d5/v4bD3tTrzsmEW5w2me8r1pcKM4tPoia8nApAXI+iNDNbP+J71gTwtuNEWNmSnTlvn8lghWyPF8Ho6rnH78q+2jcliLQSE+T4gHILzMgCj33zT7ZrN9qNVDDDBNAUNdKboupuT2ZkAfcLuyBZ1DqJ0bjU1L/HOOZboQavI9OekujIqA77FPDPz8xsbjZWuahnV+yyUKfcSmWYWDJPGc9O8Kyteogi8qDy3+vqmDVgfOU/AV6Y4ioRRNklrDXk0ycwNC/DsKKp9BFZjznOMA0PLANv5ywiN2z9eAFHbyCWfKySdXcua8DCkfgVduCKSg0CNVFF3YcXnolcApJg+/DlBr7Ed1bu6GVJTPyN6vRAeW3A2hNDypp4Y8N+RsSZOLqANnB4JO1wcP5BoyA6h4T4M4LP3ZL9tXsaRxrTrtz4VlSs1m6UAPaQiUtSh2sUWfYfTdc8Ig67xY+L4KLvH/jojHg+S7tSy/Aqq1kwrfoy52WtrU0wxDKwMgyTVNVqzxd7rlc1crFwMAttumnRv0P0EAmLWM6L4xuX+PRCRpkV61biiHaW2Yn4yN6UUapEhpnl82Ntq3N7HiMe0/VI84gy1hOGkwLHslEyNPOzjqdV6eBX2HFl49c/hMjQO0NCh2Awbu+QeVn6Ld5Sk/b49emYvOY1bojBbg7iiLgWCxxaYrvIAQwmncDpvuDEIimbFqJcUP9v83g3MQQtShhcDLfZ/8BBPomJGybg/mNV6cIROrwBGKLVQMPunAKvvqcvfnHe7z6DHTUuuQGTdgJzlKP/fNNQqRzNvOIoXoLcFmPllpH9+jb0BlJo9dAZn1SvDgQbNjSW0EKeZ8mP9KDJiha6dMHASpVvaWMZoZ1c+RSVLDj8nKmHvmpcemdfBWb1TCYVPQbe8sjNiSvCsBaffhoB87ZUQkJr+MEIUG3BpgjUkd/1tpQGWUQuhudASUYEHpsq4Z+KPjG0quM5MyITx+EIq4WUEsp3wnVlY47Aj3YaQDkgqdDZoU527K+9+8GAjEpqYDRINHanvjFVZgQG0BBPeSmhbs6z3Q8bwOwSQx/MgrwZlqDZrVpy18irxt7OSBGUuQhVYQDyPUjCJkxsr1uLgTGrQ060uD2l6ZrOfm242weRE65lbQo1TY2W52dCeDBT3wQOL2nMFnj7SKt7g29e/CZo37kYdry88tWUfQiW3igJabivPASUQ1yn/nuOhL/g10MGJbGAQwECvptk/MwnYzd1+/oIFHNSgJWl91BJsr6mXYFUxzg=="
    MQ_PASSWORD: "AgAZrQynb/5e/oWzeYSiJq+rIUMoAQ9jjDOd98oUGkt+Kppk5zCAL57mlROlU8RVX7y1k0B8wXrE05jr7zDc+DmJXVbAjUh3FC8qqchN/OYD8MbfKZ41zN5rfy1Wf4f268H9z0zX+X6k+kBAYraMEnIU9CYMG2LRJQCuTMMWodCaKIhmyuvmciD0j+tP2YBZKlzYMSCceHE1TED0RGLW8ChVylv5RcrY8GZXmpELpod2fgnkc2CAGBQbxb+qBFiAd1mjut9arRFcsFOu53sl3fbyL7I2OHe67BGDBpalmSY1cUV6vy3wrpJJv1bhD3goL6L9MWpp5zToqT9cUjCb0WB8RPlqObpg301KDovP+jhrneoP4VNbYNWCT7efSAey/gOMLZMQn9K71hJ9UEBeBsJVZcD9qfBx1S0Bb9rVSqmhjzjmuw+GaMh80px33cLHhIWB/qSTpviEV6V4U9i9Go10hhj7pMgrOx0K8KAZX7FVaGhunv7i/2kjn98rAuw3Qr4tmZzN139EgYsSlhvawUVI8SOy7g6iCsA3Xmpql4+nLYC18A7hs8iCljI8jtDSXjFokO6HEwRP5kQzwLaWjvFUsjYLJeeqfyJ2QGzG+Ri2PjsUNsAqcuKkldBTdhzwjdMvDgca6x+6U5lIfCLkS59PD6MZ7wFj0X3Uj+lNEXYFYR2ej/vHaVBwP07UBjbjW3NzJ3nlEWjBOadd1w==" 
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-app.apps.svc.superhero-prd:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
    tag: "1.2.0"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
