app:
  encValues:
    WORKER_PRIV_KEY: "AgA9vz/OVvxgt1NLiK08ia1zWzfq/eaP32fDSyhEaJJ02166PEealxKuPupQO0v8004402Og57DwUEUYBBalisKOtI3CdxyhCerZEXJXY/B0grezQTgQuAMg3gBYIp1Oc1DVTed72oMwtZrsiCnqGxy8xfJqhmCGUR++QE1H5+/987VbsqWvG6rpZWAdHySKBNJ5uC7sqXeBXuIqI5AOZuWsuHMlpier84blAHfBdd1g9ffEfzlYzur6NasQKugTC4MJm5VzQW+OIqw2XN+MtHn95R/dWG2hoBt6w0556h0vC87vHnDmAYoLys0oUCpK3gNUGqa+Gpu+Fq3kVRRtxCPrnL8h+ucfTxXZgpacQknDimQRMn4Rktdshr+tI5V9CspnMWXCFBzBGm85lcM+Wzpm/iRE3ObtEOQOgGQ3G7yIJsmjBF95910W4LAGirfEpwirIDZQK1WUOH+D3EidsjWyKi+jCUPRjwTYUbxIRzFIujf+Q59b5emqB7UX9L7LeQngtq+2rjjSP/MAP9k3f7BIvnXCWx17sN5rbck90EirmN2EY4HRncuUIGXGLCjS6AEjMUF29Pvv50f0Y6WqEvf8mrWy8iv//U+djJ/A1XojRK8KUcCv46r2TUPvLMYYnrFJsnHBjRWrVjOiWR2n2Rw7R/Ibs7RahExR/6f04Uc8c5l+87B/ueVq78SReIfNPwJxOWm6w9SVKbkAM7WT9fntJBWfBicHi/0zO70znUKrfkox3fHdbsMYAplnotfkDDIBFw2B2yuM/icKLt0XXV/y/gyZ+mCBMNB/CySSvaL0nwBp7Jk9mTUs2BATKH8zwvSk2gaV2uKbIxWOdZzHYnRxyJw7Ob3EIvPzuM6Qs4FcvBGKpHtzjuR0LyX3H25/3VdDbUJ+4n85kf8N05W3FiZxtTbV83HJ8kTpySUJqKPlyOsUqWPEqDNsDKrkcKxnukshO9dVt0psl5OXyvJY4H7jACVISKW4NBe/A2mf6cBUyLfPYuBXIw2ZekToDv9Kl21SFaGXB+hRinNDLwjHFXgSkls3agBKB+rlu6t+gK5Arm8ZUQ/afxyRowtswlBdoYmZuSCo/0C0jr/hoGJk2Y+/Nexc8yk/KIyZnqDfGBB6dcR4sDdlYhW/m3TtSHUOoZ8KFpcRWlpI593Z/mpCzBRqh0eCMe0Lg7SW+SsmMoMCjmdnwy2I169a81SLTj8qJHbDolrSa9FOr389oYJrhMpg+zf0zcZF+/pDeAnXE/hBffRcZL9mEa4r9KcZtxw6PfS8SibUKvQ5Js+/YSC0zhqn1oYKJUjbvA2rk/1I13KjjNwtFU4nvFJC06gTRRtkv4jeX0k/2domLQ1HmHiSw/Oyz2Wv4EhnkE8xiV76gkxprwIv7Q5y4IpnGUyHReX29eLJCLuIIL9oDwWHoLglRhPESCs72XyDy/LYMxwpo/8fuvXmz5jDjMSSGYdDqkRwlk6qujcfTjCFlPOscSrHGDXykU1BeSt+bRxG0/5U1LPs/+wgkQ9o+XdbaGc1hxqBD7ZsNJVOv8+6H3dVznosjI1tdrKxDPM2ur3k/HErRXEHm8Q06AHvf5Mm/Y3WU1ieQbLkFrO69CplHQ+92TwqLd8+2JnjBhRRIjNN2a7CX6/T8gruFB2dVnWIfUW4EwDLFos9i2hFye9nEoVWkUnqqFyJFIp4pt9/j3s90v/4clGCnlkPx3pxGsGkylU5MJN4wDpm/lxojh6XeVrQeWD9ddn/P5I23Ajh4IY0fnQRJViarUmEgwpVpzTB2IpDVOlMfm/lLoouYmzER7fvfMEp5qdMR4KEEWVP4BZMg/X/nJNRbzm3CNlV7HsJiN+N8vRVzeR6FlGe8VcaG2SQL1efKdCG3LKp5W+Hjw=="
    MQ_PASSWORD: "AgBOpbzheUtaO4yeXL3YH6hIe2jiim99YfHerl9A+AAvg71ORAg/UJaYrGtDkje3ViIcV09cndkFeylB0+vEsKxsg2i4p8cNIwfLnylBrO7ouwdLUk08sFjhrEs6bX8fqPsdM3S2n5fZ++K3sxujOLZv3zVlxdgyVgRAIKYX24Ih2ZenJnefJLzLBvghGfqsVsFswKBO3UaBUuPByyMgxqRm2QgFJGS5DHv5OmtUUAERYFPtYXP8f3n7pMrTOi7SP9L1/ByL/Vry+ckPIG9MPgGYlin0gg2bCZBwub85hA/W8w04IPhi24a0gtj/KHgmMRYTeoavVoExaa7YZUGrOIFryk8K0qq6LpfB2EZ8X+Ha0unjuMGywfprlRaXe3lpw+b/HL+tsUHCMoyLG0wosLucWRoo1cFdPWdHgyAf5h3fM4n7oDvgt0q0I3Gqz5Zhc3Ci+cpIhntGITb/8brXxVeQrmmin7WzNr2zSQiDQ+1VO4bqpwlSWblRZtS+ImtBvPYiDVFMcer6GkTJ/LzPassIFuZ938JSym4Lvajy/s/EYsIPEc3De51OGT0o+KXcWtv0lBYmvbx8Pe8ehJ4eFwtH7KTh4+tN3w9J+6LFfejVcfo8h0riDf/U4oG1+Wqt7Xkd9CmaFr25unImf2WBkvOTLp8wF3oDYnD3Nymsw13NjhrkrX9813QBLFwD/uYg559SMk/frxsllTUx"
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-app.apps.svc.superhero-prd:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
