app:
  encValues:
    WORKER_PRIV_KEY: "AgAgryLw+LD8nqvVkWQe+lJMr6mKfQcmzA/3VO7NuMMj9FY3FkREac2MpX8Fy964KLwWwUC/V+J67R402686YMUUNQNXmLKPvbYPMoyTjzpuWK351MBwfHrmgtYPwD3Q9dQ1mIZCZSNxyvgTP7LISQK0SkOOHHRFE89CCw9/nYtHoGRjmS6QV8LVkNnv/r5ymMI6VAmAXMR4/jj1iyRdY3T5B5MxuTd+gWCN3vWbAQJnCjsqXLTNDE3yxeH56m81Mtd7nuh+7yHuaJ4eE4yflZV47Sx2H+QdX5TnwmKtzWC/bKSenZre/fb5WqtmNtXYMiTQxL7R44j79Y73lcbayCOfLF51cuACCGpWBMek+7AZ2YaNGTYdd8qMrhZTg6z4Bjpt2VWhnaap17pbNVJtIqM0LdJI0Jt5fKvifuC12X0SggYVJaBuFZkvyi5WIS8lGzzIP2q/h7L8dKPIqMam/N/9WOO/6OBNWnnY/EgCx9/q9L+dY4WOKaJWCkjXFCiMPhLMHQkJ3usYAz7+jrLTCzL1/0303j8B/q7Yo0LPw5/w6HGgv8oEAGailsQvVMPxF4ExRu+t4mUop+VxnQ4oIi7umN9VYg4y69Ndg+0WsEa9o2vzYmrXPMJnAOS2QQZzNEdlPcT0TeS0ahhm9XKmJ2Ic6zo/9xRjE/WD62j/EDWAi2sdY6m6Vy8N3qcCm5UaXZUJ5cJDhM7oO/I0F67H0fQgAXW0EWLiZXWlhr3kchycF59lQyUB32MaUV89T7tugmQZfK5qA789/q2XxpFVv2PgG1DM4S5JxNU2jSN1WXvMx0NzjZVO4Nt4MfETu1w4eNMuU6IgNYnmB3hGBTOGBwlTG/tk536P+22BMoAeNMxrl0KG/V0S4SqzwXYB6fG0KISNPv64Rnzuu9zISoJD2XdEn7mMd4qRDuIzbuZaCV4gGE42fhdnkM6SuKL88rMqQJOrS+taNRnRXkxunfwfkoNLdyzibQLhsxoJMEUJCUGMFrvLzvwJ8sA9Q7arnpphi2Qs4rq2KPB2n25eSFOTHOKObqKYXj9+lSQotSiAmg7CEKRYc6BSeenrPaZhKklUcJvHiTUIqNDULauxi4QhzAkyyEWdAkGVgG0ZmuD3JPGmGvfSs9ma4jyOL/FU8hbF7Nn7mUmKnvrlDarYB1364hqlmF0QGRlCmPNKlgEpUC53Ztlg5ji8N4QV92fqdfxJw374TxavoJnIl/j9UE7w4wnrTseJLGTrEl72PELLXyMze6ApbWZPP8Ms9qTvXQzvAaAudaBERxKrlxw3tuXJJ5h+voO/5X9DUTPlz0R/RR1WQCpjd2dUndWFsTdlr+2+JfI7CHthUGyquQZnwaLbsj8A4Maw6D+rx1c53yjRP7eZvTP60jLR3yr0ReDFlZ4qcyp2dQxp5Tu4SuURS0+p7gWd2qLV2OxQQx7uw/czVD/VAptZOY2pnxTpRKtUY8O44WeSTfhKukUbika+J0i+cAqh6Wn/ofzu2zOJ7RCKVvNK9V+/cnsIGcrq7oZTZqFTUJzYnyiwaegjHyCWJG/oiO4pFl/AGlPzvaPdNXNHQ/8jzUrP0FlZWgZ8TOIwtqOlBary6yukFmZfF3gUXqPx9j6VbeiYgqSplC8l8FOpbDdPEr/NwMabWugt9PUURFpNdE7EBNgOBFurFByUBQaXdhiV8i9pLBwUrrW5mtVmukinUX0+U+EBBrwx+2C2SfnueEdTMhlKyryQnO/DN9wKX6RE2bI2lol3YiO6OcwYP+ZhxmxnCglcDz0Nh4+70d6mEYEQqgWJstt5091Fp/U8uN00/5jHpcD9EN7vO2mG0bBTIb1JI6tYdu/ht1LoF8Sk/8M0n8xY7V+5Oz/sBJIFDtJB1s+0rKmF"
    MQ_PASSWORD: "AgB7eAaCeoGWPDchYPi6FFxh+z0aRv6rm+6r76srMWTZ3uCevBit50fwIs13QZALTZZOylHNt95t4e2DlNjZ1SR9PlOmOUQINFU0NYajwavTJICJxCT1psiDMilXJ9usAYqyeYDnADymUf2TSRw3ymxnpiU0U28CrhXb+uzVr71ytMnwsNumLhbosd9rWmuC+YTf+zYfkW2iBK/X9ztdtrdJ+by3RwfPJJdaN7xWhpWJqmwk4YdT/4aLD2r6mADiHDGuT+znpudOwKCQzpfMMb/x1Q19RF4RuMOxLVetF3bi1j65mJeNMbiVXZiHZIIGnxYcPVBcJdXanTAEvmlM2X9rijOybmPL3aeNeY01/f4x2TAFkBFTRFNuTYDCL/fpjyoKZ92S4D5CZ/BerC3mOUjJwH3sfHb6qZNoBs7byLxC3iiJiUWwF2TuadRsSG48G9P11+VSATiqaJc3bW9AGnZgH47OKJ5/h13G4qt0OHGwST8uW2lT25SzMJivYrsGS13BO8ogUrj6SckLRH1ok0cmoDPzyFyRDWg0ybINuM/NSMMxF1hnQxtz8/hIc/XQlFsAlEstZSf9q9YRywizXwH/yPGQrCr8EXpK+/gcqaHBEzuu1kaspfzjiEu1DNpJ/EXn7BthH8OIMStEJauTKN0EZ/VsKfrZyxckQy+GZ51dv6jbZvB7WqD/T9PU9G+WABhD9ddspK6gFlz1hbYQOfU82AkXDcyc9cK2YYrYLPeZng=="
  init:
    enabled: false
  env:
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "GATEWAY_API_URL": "http://scv-gateway-app-develop.apps.svc.superhero-dev:3000"
    "MQ_VERIFICATION_QUEUE": "verification_queue"
  image:
    repository: "aeternity/smart-contract-verifier-worker"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3001
  ingress:
    enabled: false
  versions:
    - {version: "develop", gitSha: "2bfcba0"}
