app:
  image:
    repository: public.ecr.aws/aeternity/aepp-governance
    tag: governance-aepp-v1.0.2
  ingress:
    hosts:
      - host: "governance.prd.service.aepps.com"
        paths:
          - path: "/"
      - host: "governance.aeternity.com"
        paths:
          - path: "/"
    tls:
      - hosts:
          - "governance.prd.service.aepps.com"
