app:
  ingress:
    hosts:
      - host: "stg.wordcraft.fun"
        paths:
          - path: "/"
      - host: "pr-541.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-541"
      - host: "pr-544.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-544"
      - host: "pr-551.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-551"
  versions:
    - version: "pr-541"
      gitSha: "null"
    - version: "pr-544"
      gitSha: "b749f9b"
    - version: "pr-550"
      gitSha: "8ed5b7b"
    - version: "pr-551"
      gitSha: "4d6b34f3"
    - version: "pr-551"
