app:
  ingress:
    hosts:
      - host: "stg.wordcraft.fun"
        paths:
          - path: "/"
      - host: "pr-558.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-558"
      - host: "pr-575.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-575"
      - host: "pr-595.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-595"
      - host: "pr-546.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-546"
      - host: "pr-534.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-534"
      - host: "pr-606.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-606"
      - host: "pr-610.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-610"
      - host: "pr-611.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-611"
      - host: "pr-612.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-612"
      - host: "pr-613.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-613"
      - host: "pr-616.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-616"
      - host: "pr-614.stg.wordcraft.fun"
        paths:
          - path: "/"
            version: "pr-614"
  versions:
    - version: "pr-558"
      gitSha: "null"
    - version: "pr-595"
      gitSha: "null"
    - version: "pr-606"
      gitSha: "null"
    - version: "pr-610"
      gitSha: "null"
    - version: "pr-575"
      gitSha: "3445622d"
    - version: "pr-612"
      gitSha: "3419d46c"
    - version: "pr-613"
      gitSha: "null"
    - version: "pr-611"
      gitSha: "4d015437"
    - {version: "pr-616", gitSha: "5ee26270"}
    - {version: "pr-614", gitSha: "53b46484"}
    - {version: "pr-546", gitSha: "46613254"}
    - {version: "pr-534", gitSha: "58c26246"}
