app:
  imagePullSecrets:
  - name: dockerhub-secret
  image:
    repository: superherodotcom/ccga5tw
    tag: "pr-542"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  serviceMonitor:
    enabled: false
