app:
  image:
    repository: aeternity/aepp-grafitti
    tag: "dev"
    pullPolicy: "Always"
  resources:
    limits:
      memory: 750Mi
    requests:
      memory: 500Mi
  service:
    port: 80
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
