app:
  ingress:
    hosts:
      - host: "aepp-grafitti.dev.service.aepps.com"
        paths:
          - path: "/"
    tls:
      - hosts:
        - "aepp-grafitti.dev.service.aepps.com"
        secretName: aepp-grafitti-cert
