app:
  image:
    repository: aeternitybot/dex-backend-testnet
    tag: "v1.2.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgBPwnLdNZoMrxlcSUt+xC2TX8AxPcvIf4NmgckjJUFD20X+4Nkok+oHsuTKKGXSJ/OerIckEXivX75UD+dGn04OkwycAjL3qyx+m4fxB6KOZkAvq+vV9GLL/751WP24qNisbfR4tODYDM0hH2tMrQotYPtA8/G4JlXZ9KJMyNhb+jrtQnK+d1Xw2bqi9ID4Bh6hJOd+FpQe2v+PjjiNRXp1p0rTDY3iVmpw1axs99FBJpW5TJkyOq/XilEUmWfUnr5wBxRwd4xvjd6UaqOBH3QKiB9NKbXiRwolktoqzj7b/s2cy7OX/EVOjCYNSLafExz01BNaeytM0a8U8bcA/+wInX1VDBeSjC20pERDrAMvzST3r8ligmNn3fOA0qwugriTd5es2FvCJvpMZXaZJav3+KJv5sZfoQEd0IWIa+h5Khet760cCirDIF4dXHG6mI9b9LJ14+rZhuWunYddXpzXxNNflA46Ns+dcTPq60RVTgLLd2WHWTos79ovEYJVjfi9oN5qHtww2bfaQWefNQ7Y9oYDa3Hw2leJ2mByzucpg+qW0GKCpQmFj624qg5ZnjFwgtWM/WP9ZdnXTpfbXRIc1QKYTCKEa+GeAbVl9qmdXgayq43M6BHxgwjuUyMv25RG1PcRFQom2jIh86NjhxIRy+V15zHTQOmM14E6DxGGhL+y5yJxoS07v82knZF3NFbz25MxKz4HogVEKNE="
    AUTH_TOKEN: "AgBIOv69pfdpekRHmF3pF+nV9Yc8lTn8z6fwas7Bs6iI7eLYZzGbXi1Sefyqu+FzKBBDOb/aqL3+CvMBQlGWpO8soJT2ieWw+16OyXlDo/mKABqpS4HCEWQ8UvAAzgVHIIrH+xjGpQclasBtPCIUi8+vmC8y13Oehhwr7cR8F9z332sa09bdLetFBrAmzOlHkpROcSI6EL9RjOoY5cVMSsoBSKiS59yWCfX5LocpO++JBIqE1IlhF4HlaawqU+zukcPAPkaY9TKoy1idgSXYD3p9tc+0f1qminxWEGYqtBjAh7k9UFo0cscSSlwGyAF/kTHl2LVCyN15kKFNR7SwRyxZ87FVfqXzzv58Wl5S6N6XSezBKJD1R2+2Fxq/DHOxOXQSTI2R+GGUXGvvlKqhOPvms6GWMg4rfAMXv1fadMlQ4QgWopJ4vdKgOf3P822L1MGhsZ4uuYTG8Jf4jIFNhT66kCerYxeJhKpPY0g+uXF94GgCXvNGhQCHf2iIQXm4Jxnn8Ynvbd3R6Lc5bvJjLRnloRuwtjPMcACQb74ImGXKMV336m7XllkX9tdW8/ycdsG1ve+HP57llHG9UmNrMSsmmJ+MTt39EejsBFwQlopqTB0qx3XkLTzj2G0BiFixgg9adhbWG5UbkzrUYVwQ/1LeVoNBqIUApe54Xyrbgy03wjnV78KDhZuH8Z+LeCyfBo5QkKVPBEbPg2wUdn4MymgD8rUf5OxhuxfnKC2+MgPY9Q=="
    COIN_MARKET_CAP_API_KEY: "AgA3sOFBp3gDQQNr9L04h21w1z+J9XRHD+9uoE7ziR19b6+qrjyG/isSFRa+3QRqAieOf5fyKpG5OncIrDpX6vd5Gfr3iYebHwAbRHdZ2ghaMAlJ8jngEkg58pEHmx3ASg6O9xCKwj1+Q6tYUFZ3pnuq+rBM8q2nKcOjOaUd7v+DV0hJq2uyHrTi6+pBKk7fAGNZ3sUSYwlgoFFQuqvr8Yc+GMlddqUqoYyszAjnNlyVqw6Iwq1sgNuEqsg1ws722FyWR4agqSWwDm0Q4pMqAInvNjTR2Ma/cMf1taZZSkMa/ieriVOlSj4WVcXp/V9iM2EZNJO1hs2L9ejc1t0TAy4AFv8800OvGwuujPbL09oYbDquebb8kjb5zgf8rp23LPLpkKq+ziJbdUy/tPodY04MFCLgo9KmMAdVQzpclhX0ol6R4P+quYyVsnI36ZeY+U+K2DiFhJh9nWmuRE7E9DVm/Jo9yUtWKgVACT+aVvugdUhm/Fm5PdKEuywImMkTK/c2hwG5qmKdlxTg1KhFY35H8wVuXnxTwwpBNtbDeJMNdEtmBFqkHDhONCjP3ZotJXygxkHFtIilm0ZFYY/dwbFw92zwfEL8XkCvf1c0YdIwk/D/wOMbPvD0dwUU9hoAOZYV3JLF+T1vrSD2z3anASur/OPwGCXEb+RDbnXui3zyak3PsPH0Jo2TsooakSAulEwTi7/mEOt345/nVY/EPxjtvo97KQ7HUT0Z4qqrk+e5KmiuRPE="
  service:
    port: 3000
  resources:
    limits:
      memory: 40000Mi
      cpu: 3000m
    requests:
      memory: 3000Mi
      cpu: 2000m
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-testnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.service.aepps.com"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "testnet"
    "ROUTER_ADDRESS": "ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "FACTORY_ADDRESS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9"
    "DOC_PAIR": "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
    "DOC_TOKEN1": "ct_b7FZHQzBcAW4r43ECWpV3qQJMQJp5BxkZUGNKrqqLyjVRN3SC"
    "DOC_TOKEN2": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
