app:
  image:
    repository: aeternitybot/dex-backend-testnet
    tag: "latest"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgBSfSH5vAgSZoWVvFUJrqfhKWPJLejn380Kr/zbYkCwJQucyMU1wz5nh0ueKhKP3gTWwhHptaYuYmQJLl1RrVGFfTpDVyBVygOB0j5v64F98YGPbELdXJt2lyml3aNtsGPLvEmyVFaxz9xEewV432efe5zd0KJ0WRYtrulm7DIQrV0zPgIfdbc/ov3303fL2q9kfjcLBYGFwvkm9R+cZCs7NCWPPOdoZDMB0mxn92iMt/1KMhlM4TJotI3AQ5oFOxPLhT0TJeY6m/K2TF+bQYygmHPPzZlE97sby5Pbf+t8Xn98SDLYmyQ9r1LSiK/oe8IFP+O/LglQvJAeLkKw3kxPWwb584cHNP0vaoq75hnFTW+L8Ogb0mTcc7CywGwbTtDF57wqrluiscDmDnC/OrzfLsLiz0zeiAhhM02G/Ya8eyjkWhN5uRmivkXZ73nndoN66lDYrFf5Dk3bnNJra2jq+14wj/KLqcGeoWBGV1kQu4BzOBL92l9lTALcoYfaDMn0XMix8zSG+ZAUgScfGyelgm3U462aBe9zO5pRlj5H41Tr2tiLcYwL6xHYBVQ8Y/Jwz/x5zBt4SyjakonaDeJbEgoXeex7OTRYj9csnM4wKTrT5JZOzcNikVp8C2CqcLXsnIOm+83RL9gFeQ4s5zofX5FCnFUptgcS03fQcoJ1Jv0iCZRjiWdLG1xtgoIGE7SmAHdQnJK0hHfB08g="
    AUTH_TOKEN: "AgAKJ2cYrt2j3QYrrOCqsC/AEQOz3D71X+CCqTclRgCz4hBWwPw7BdaTQ+SCVTOKMAC4WuBEch+3SaDLdmL3chER2pso9q4tiwlsUNG5zsWPHaVmsaDdzi7nRY4O45K8E+a+UzTsePfyqFZuLN88kk+1TJaos5wae53E303LHccg3i7/fHRlVvG+n8yn2Ab2lTftEZv2uyrWxJOjKODDQ1AlIjB/GcO6dgCH7cos34i3NlA6COLk0aY6UpG0lOfEkXrwf6S3jbSvnGbcWcmuPTFKmqi8/wz+Ay8+rv7WhNwi87XpraDHkeejf40kFAaY+GmN08gaF+1TojJaUO0tJhTWsQOE68+ds1jGf/R4NYP1pwesoup/yNVITw96OaskAJnn6aI8ncA4vt/sfx7fHfretvEs+AN5lAB/p6/S8BTOoHPYSPahEaPTuAejIDYLJHbg+d5L+jAGlBHlHK3io8ufChtJL3tJ2ZV81IK77FAa6lYOQfPADdPffPTjsuFPNVVB9EAECdK9RLmcmlh693SnQkoOj/94CUGzm5JQjRJ7kDmU9/MeIq+0IuV5JHGnyje3T95L73KEDV9w37kx4Z7MjpIzVzPiKF0gGK03AkmJNhsHSoMSAZfBES/Rm8WANo2qxlhLYLTKGgGS3T1rO1dBFaU/24i9rLb5rrdgstrD5Q5KAMY3QOH81XQL8Pwmv2avAVvEZShvZoIZldLjlZ7kZNMB61AMQs7TfW7rpWxx5g=="
  service:
    port: 3000
  resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 300Mi
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-testnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.dev.service.aepps.com"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "testnet"
    "ROUTER_ADDRESS": "ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "FACTORY_ADDRESS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9"
    "DOC_PAIR": "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
    "DOC_TOKEN1": "ct_b7FZHQzBcAW4r43ECWpV3qQJMQJp5BxkZUGNKrqqLyjVRN3SC"
    "DOC_TOKEN2": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
