app:
  image:
    repository: aeternitybot/dex-backend-testnet
    tag: "v1.0.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgBG/lUIIy/bbEbS4wLmC9YX4byJitmQGiqW95t80D3okN1gZ6sET4g8SVZErr2ASi8Js6YHuBmasill3Rn5xzzylQwMcGaAyof2CqHlc99WQ95ArZzkYvjPzHPaPxUgvgmfssX2uAA9/4sKzL2QMzsn8bJMdsWH1OVUZnlViMnEZ4s0Nao7TyYPhNV5b477ahzsCdknWG5HdRR7oGNkjL2gg9Po5i6rXypYm50FwH6l44xRwd9gFXyCvgvIC15MHNaGXPuho6p+lt/cdcnAzArj17lTpC9e1ALyyy9gFSy3DPShteHuiNzytuXfTgWlLmtHnfJDJ4KSwuKf0+curjvm9qrLaOm4G6vTlKzcxF4FqSl3LC4CSZSG573m9g2K1fK/Co699RxztRE15JT9AcVJYz9WNz7oCezK5vgq7B/XhNYCfrG4umidzzuBlzvAAjJj8MZvdX5ASMgTW53W+QYubQf3xB21UopqnTCoa6j3/D62TOlHW9sio5XJmVjktFxFgf7ylWjE0xOfONxx00K6lJqoDHU0TgAy9QQH2TrEwn0YycY0oEhUF9l9tZ16+TKXHqOjEId8TkvfyRV8uX50wK+OuOTNak6uXX8dgEB1XsCO38pR3rfOruMReedBc1dk3hxSt88tHHIdrObP/LJEpsunUI3+fxhsQT4HAGOKCWSJHIk2yQy1YPgMQp6XSeuCgQJ3vN9E+60Ffw=="
    AUTH_TOKEN: "AgBIOv69pfdpekRHmF3pF+nV9Yc8lTn8z6fwas7Bs6iI7eLYZzGbXi1Sefyqu+FzKBBDOb/aqL3+CvMBQlGWpO8soJT2ieWw+16OyXlDo/mKABqpS4HCEWQ8UvAAzgVHIIrH+xjGpQclasBtPCIUi8+vmC8y13Oehhwr7cR8F9z332sa09bdLetFBrAmzOlHkpROcSI6EL9RjOoY5cVMSsoBSKiS59yWCfX5LocpO++JBIqE1IlhF4HlaawqU+zukcPAPkaY9TKoy1idgSXYD3p9tc+0f1qminxWEGYqtBjAh7k9UFo0cscSSlwGyAF/kTHl2LVCyN15kKFNR7SwRyxZ87FVfqXzzv58Wl5S6N6XSezBKJD1R2+2Fxq/DHOxOXQSTI2R+GGUXGvvlKqhOPvms6GWMg4rfAMXv1fadMlQ4QgWopJ4vdKgOf3P822L1MGhsZ4uuYTG8Jf4jIFNhT66kCerYxeJhKpPY0g+uXF94GgCXvNGhQCHf2iIQXm4Jxnn8Ynvbd3R6Lc5bvJjLRnloRuwtjPMcACQb74ImGXKMV336m7XllkX9tdW8/ycdsG1ve+HP57llHG9UmNrMSsmmJ+MTt39EejsBFwQlopqTB0qx3XkLTzj2G0BiFixgg9adhbWG5UbkzrUYVwQ/1LeVoNBqIUApe54Xyrbgy03wjnV78KDhZuH8Z+LeCyfBo5QkKVPBEbPg2wUdn4MymgD8rUf5OxhuxfnKC2+MgPY9Q=="
  service:
    port: 3000
  resources:
    limits:
      memory: 3500Mi
      cpu: 1500m
    requests:
      memory: 2000Mi
      cpu: 1000m
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "postgres"
    "POSTGRES_SCHEMA": "dex-backend-testnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.service.aepps.com"
    "POSTGRES_USERNAME": "postgres"
    "NETWORK_NAME": "testnet"
    "ROUTER_ADDRESS": "ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "FACTORY_ADDRESS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9"
    "DOC_PAIR": "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
    "DOC_TOKEN1": "ct_b7FZHQzBcAW4r43ECWpV3qQJMQJp5BxkZUGNKrqqLyjVRN3SC"
    "DOC_TOKEN2": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
