app:
  image:
    repository: aeternitybot/dex-backend-testnet
    tag: "v1.7.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgBPwnLdNZoMrxlcSUt+xC2TX8AxPcvIf4NmgckjJUFD20X+4Nkok+oHsuTKKGXSJ/OerIckEXivX75UD+dGn04OkwycAjL3qyx+m4fxB6KOZkAvq+vV9GLL/751WP24qNisbfR4tODYDM0hH2tMrQotYPtA8/G4JlXZ9KJMyNhb+jrtQnK+d1Xw2bqi9ID4Bh6hJOd+FpQe2v+PjjiNRXp1p0rTDY3iVmpw1axs99FBJpW5TJkyOq/XilEUmWfUnr5wBxRwd4xvjd6UaqOBH3QKiB9NKbXiRwolktoqzj7b/s2cy7OX/EVOjCYNSLafExz01BNaeytM0a8U8bcA/+wInX1VDBeSjC20pERDrAMvzST3r8ligmNn3fOA0qwugriTd5es2FvCJvpMZXaZJav3+KJv5sZfoQEd0IWIa+h5Khet760cCirDIF4dXHG6mI9b9LJ14+rZhuWunYddXpzXxNNflA46Ns+dcTPq60RVTgLLd2WHWTos79ovEYJVjfi9oN5qHtww2bfaQWefNQ7Y9oYDa3Hw2leJ2mByzucpg+qW0GKCpQmFj624qg5ZnjFwgtWM/WP9ZdnXTpfbXRIc1QKYTCKEa+GeAbVl9qmdXgayq43M6BHxgwjuUyMv25RG1PcRFQom2jIh86NjhxIRy+V15zHTQOmM14E6DxGGhL+y5yJxoS07v82knZF3NFbz25MxKz4HogVEKNE="
    AUTH_TOKEN: "AgBIOv69pfdpekRHmF3pF+nV9Yc8lTn8z6fwas7Bs6iI7eLYZzGbXi1Sefyqu+FzKBBDOb/aqL3+CvMBQlGWpO8soJT2ieWw+16OyXlDo/mKABqpS4HCEWQ8UvAAzgVHIIrH+xjGpQclasBtPCIUi8+vmC8y13Oehhwr7cR8F9z332sa09bdLetFBrAmzOlHkpROcSI6EL9RjOoY5cVMSsoBSKiS59yWCfX5LocpO++JBIqE1IlhF4HlaawqU+zukcPAPkaY9TKoy1idgSXYD3p9tc+0f1qminxWEGYqtBjAh7k9UFo0cscSSlwGyAF/kTHl2LVCyN15kKFNR7SwRyxZ87FVfqXzzv58Wl5S6N6XSezBKJD1R2+2Fxq/DHOxOXQSTI2R+GGUXGvvlKqhOPvms6GWMg4rfAMXv1fadMlQ4QgWopJ4vdKgOf3P822L1MGhsZ4uuYTG8Jf4jIFNhT66kCerYxeJhKpPY0g+uXF94GgCXvNGhQCHf2iIQXm4Jxnn8Ynvbd3R6Lc5bvJjLRnloRuwtjPMcACQb74ImGXKMV336m7XllkX9tdW8/ycdsG1ve+HP57llHG9UmNrMSsmmJ+MTt39EejsBFwQlopqTB0qx3XkLTzj2G0BiFixgg9adhbWG5UbkzrUYVwQ/1LeVoNBqIUApe54Xyrbgy03wjnV78KDhZuH8Z+LeCyfBo5QkKVPBEbPg2wUdn4MymgD8rUf5OxhuxfnKC2+MgPY9Q=="
    COIN_MARKET_CAP_API_KEY: "AgB02XgxZqBO3+QEG0Lx21gmsjD7fmn9gS4La7a3wmEvJrdJdtDGV5KNSBErhYgrjYWSsDxezcwwK1YH6zSaRFCXRjfwu8jAgvj/0Au1k9kkg1zNSOcUVO0sfUJGISrycbvDqDL4KdH4fN/tnAtfMOtEsdQXmpyIEFwY/CXUO51fjRkYkNvlRoyKkXeUfN3lninbZXFt+wFV17Ly7HtBCHjbVlPQYLw8B0Oowf1nBKdYymYriIOkhBE5Kr2TIuCaNlN8jIE+8Hgtpje4rHPUBPyrDoLkFL8JpPIScoScGzW1kq0bdBoIZPSLqTGlTP9rQe9Zqrno1HVuB+MALFCUvS9UiUnXyuXDjSLSpwvHhabzKz1Dfydn6JNR4Oz0fywdSSYlv9eowTZIzuSbJ6/2q5uRPEi7uxf1Rrbeb9euZSZy5/QV4ycN9BA8pVqD/wem0YBn5vHJvRcWtcVIfnaSlHiqxTD8q5SkaHtmE0QebH+nhLZLEX6GnAlYJu1A4qFOKu9iXGLg/5/JnFfDZqrfsmJboXGyQow9XU3jX7cEmE0xFd38NThD7sBSFeliLJtlVmB/fnehb9I2pWl2yxfbwGkIlCuWVXqmJCIO/bpay6Vs6qmQs5MHWN/XfBl6/Z+JKPHXX7kC5adZyyyNgeGbv6vwQ9R94PJFZIXd6Cl8ywBO5WMBvsaOrMOlJyh+qgxHNNozFBdyPMvBnBUFHcFoiYsl9N9/pOjRVo3xj33YxUNi2qkXNDg="
  service:
    port: 3000
  resources:
    limits:
      memory: 40000Mi
      cpu: 3000m
    requests:
      memory: 3000Mi
      cpu: 2000m
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
  init:
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env && export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?schema=$POSTGRES_SCHEMA && npx prisma migrate deploy
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-testnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.service.aepps.com"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "testnet"
    "ROUTER_ADDRESS": "ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "FACTORY_ADDRESS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9"
    "DOC_PAIR": "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
    "DOC_TOKEN1": "ct_b7FZHQzBcAW4r43ECWpV3qQJMQJp5BxkZUGNKrqqLyjVRN3SC"
    "DOC_TOKEN2": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
