app:
  encValues:
    POSTGRES_PASSWORD: "AgBtMfsR5zKBOoZTJf8bBgtygqWJXMMbJbhkhv0cpgfq0mKmiO0v6ka+nE5CkraPQrJokKOR6cwOHq+2zmor+TkMg1adecPX72P1/FVMGQqu6dW9HszDKrpTy1iR/2VJkSuQNoRcadR7afUtteCO+ZLhKW/JsnnX9BgTnZLqU+buV9BR1g647TJ1S8Ec7+ucBsfHtvxlwmpe0obJYHbuG3scFNR/Mex6HBAvuNvDCgnWe+T0vDITOk4s4tYy2Dc2ykU2FG/9moubsyDfxu0Bm+7KAY2QIHabVxOPeRVYDrITx62IIeBfhNzzkiqUkxvrDFxUIqR3G+b7/zxdQxAaFtbMOwFpnPjuL1h6aB5Gf1eUs+33OTuvWyAh+aJkDVZ9XsTXDekmKL/Mn2TcW0Kpd0IGddl7CM4N+nrIg+IA17X8Q0TeQpK/y0AIcER13DLhiOOhegg28InDTsrtvTcZ8oz2nPzmWQNUpNnY0ZNYf9YrFNrkl78f9JuDDD0NQlCL71+irvNJ8o5xBAeAUSpruEHn7ryiCJ2teFHBozzyyPOhCCpxVl3sMA8Jn2VzoQrlnSvm8ihJPx5Ny4l5DT3km6mmvZ9ysflqqkrExB1QFAd/AmwjOEoI5j8Zg95FaTQPKtJMSiVmcTUwIHD5SFknRSwFUIPB1qiDAFDPAcfDd60nYTliqR0zjqSthoikJKbYYrFZegxoMnOwbn2d"
    AUTHENTICATION_PASSWORD: "AgBd9lSr8OAIvCzeFBAVQAy7dW1w70jn3nzhMvHIKvXD9yiGPk92Gw9uiIR99YGR33JJOJ0YPJltnhSN/GEGN0CfCdQFKLHRZPGPydhC/XVZWIKjvJkVo0JOinYnEiNxEcUgtx4UkyEV0qS7XcPLxT5g1JFamdM6dI7Vd5hzy10IMl7h0A3WTidpWTUswVyr2DS5i1hxC+g/upHoixhHcdOhb4gQN6s2uH7tvHOKksFDo6jtMpePSLqtk5yB8bkn6XadOtVIL63amToZ2uYImfcJby4KGIs7SyjOjvywH5o6hFcQrSr67t7Pm0yCkShzFGZ25gkXEZRz6WxTcekGlSrXnwEvJi6yjBswQWSTIq8CVh37f1/Ovfv6Q6/FoTZItgE+zwI9kCM+RQfNQUlk2T5yYlhMt24X12si+3NoI1vi1nSU3omP5c54c2dzqpVopIbn0Ne/Lk3YVz8vKcV70upXvjJ0XRhQhvHmo65qfffPuhZSvegsRd3NURsJXJI0t545shuqifN1wZm2vFQZdrT197TD3dtdnhdVxXa6X8gPRZDRiPQ13CZdh2mmNBgA342fnTteVW8VVZEo5OeT1toSyhLwtc9M4ilD2a+C7jBd+OJnkXrJGlDYRLgPV6qAukmuWONRrPeKQQyFpYXMr4WN7XOaq12tgpgxCuBZBHOVJLNqGmjfGHP4cmYY0JQgIibKTqQ4aK5fE9Cf9phgSA1igA=="
    PRIVATE_KEY: "AgB4hePbuo72KTAwzsH1NAVaTaehuoJryWvbYilFPNI1vFnAM8VvpYVEpBLEBFmfcTi4Viays+BUr1XEnU3Q1i07hEoDnrlc9ttfsYu1/L0kOEKipXW/BCMQnbHqM9nT4gGGIyQuDlGIzPXjJ2uxb6Jw1nfqAztoMRRPzxBy/S58sU8aXei/FZvZlDcMfo68Zcz2bfQJugSjCo9atZWgYrnJ2f1kQ+hTkSdxJ7QnZf9tL7r6YtpewgH945UDlCDRa8eez1VqOxDP+bY6hwqCdvezTjEzKEi1VON57u6yGZ7GoYYb5qywze4ALouEKLabP/8hEKOIdwzynM0Ac7StzTJIQrltAllYztPkWllkjCtuv+LQSCDRobhP2nncQE9KbiaxErOk21SAU+k+HoAPD1wvGUUNMdqaSuSDT7fqi9QF+Fw7dW8ZLlv0ovhSdcEYq33crgTfZnfirD/POy4SnHTp9Nk4z+PBuCjct3UaXCkevqBU6P++q6d7sExVct+DTPay69IkrGSVdles9nR991qR7+8uXkNCfm8LR4hEZnu1YKnfsJqTuMroPdxaUMbYsAHxQUTeMQnCRhuB/es+zfTBAHsiVegNEWKZDJCysHWGrUPYSb3z0a/S/4UXLVhsEByEcW381zeRKdvU9Jgw8qT9h3iyzyglgij4hcWRaUdEdqWAH5/222qP4euPPWaAdVC3QDGdH1CXniL9STZ8n6fEH6wAtO3aMJ46VypO4qEqXdtAt477ARAGbHuKlW0DM1oEIYa/z/gRJdpo+43LvfX9D30Pnz3hQqd7BtdaJCtb40VPJEdYyjo2WtXCzfa58EAQd6FIpxVisN/9PUKJMZhaHo5XTE2YmtCKoo10aXk1BMw="
  env:
    "REDIS_HOST": "redis-master.redis.svc.superhero-prd"
    "REDIS_PORT": "6379"
    "COMPILER_URL": "https://latest.compiler.aepps.com"
    "CONTRACT_V1_ADDRESS": "ct_2Cvbf3NYZ5DLoaNYAU71t67DdXLHeSXhodkSNifhgd7Xsw28Xd"
    "CONTRACT_V2_ADDRESS": "ct_2bvoxQ6cwwzoFASuddUxzsYVBZUet9KGHRAp7i25xsMXEWvSvx"
    "CONTRACT_V3_ADDRESS": "ct_WscpdLQf6ZZxoVqrsEwUwmuAEdzEkJii5W5TzG84rVgHeK6BW"
    "TOKEN_REGISTRY_ADDRESS": "ct_2Ga3mNT8er2zYjGKx7tJggn9nVnYt5UzmH9x9irRV4ayg4sfLL"
    "ORACLE_CONTRACT_ADDRESS": "ct_2PbBVGroJ2G618tHbWEWRrrxxf1BAn7Qt7BoNcLh3LqsSck8Lu"
    "WORD_REGISTRY_CONTRACT": "ct_2vTMtHgJTxTpsQ8Tm3o6DmfDkhc3vM4DefV845Yp9FSDuS6YWB"
    "MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw"
    "NODE_URL": "https://testnet.aeternity.io"
    "IPFS_URL": "http://ipfs.prd.service.aepps.com:5001"
    "PUBLIC_KEY": "ak_fUq2NesPXcYZ1CcqBcGC3StpdnQw3iVxMA3YSeCNAwfN4myQk"
    "AUTHENTICATION_USER": "admin"
    "NODE_ENV": "production"
    "WEBSOCKET_URL": "wss://mdw.testnet.aeternity.io/websocket"
    "ORACLE_GETTER_ADDRESS": "ct_XabcJUxaZc1w5X4WxD2WUVTLPkZX97HFYzhuwkhQXc4ZzDqDF"
    "CONTRACT_V1_GETTER_ADDRESS": "ct_2ixHY4bADzDY6ZYThGixnjYa6w5dtYoSoxtCThWvZ7SGgMGFWL"
    "CONTRACT_V3_GETTER_ADDRESS": "ct_414KdQa9is3wiq6AKV7LLk6z2UN3Sy3odmAZtenyYSv35h7fv"
    "POSTGRES_USER": "superhero_testnet"
    "POSTGRES_DB": "superhero_backend_testnet"
    "POSTGRES_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "POSTGRES_SSL": "false"
  image:
    repository: aeternity/superhero-backend
    tag: "latest"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  service:
    port: 3000
  resources:
    limits:
      memory: 1500Mi
      cpu: 300m
    requests:
      memory: 500Mi
      cpu: 200m
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: apps-superhero-backend-testnet-app-text-compression@kubernetescrd
    TextCompression: true
    hosts:
      - host: "superhero-backend-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
