app:
  encValues:
    POSTGRES_PASSWORD: "AgBR5mgXhqGqYyElUBEMJc1jWNGrXrKNm7df8GgG6jDVEGQE0tXNnpr4vqQz8LmhUJZFV79W38rF5pzIh6+IobcqN/B4wRO5pLuA82lEV5iPuem3DcLXrDeTBJwr/HLy/L2+56OHuLr3nk67dhdS76B0c68lM4eUGb1lmE8YEPbc0N0inXGjr4B3+faSrfB2rUt7iarMLFMJWytruWZCcGzTrgwSXeB4p0bUMSedRXmVWziSvMgB57n0iz+o3771lOBYBzG9Lbs1Tln5dJuDlDPYpOASEbx2CbcBGn1hbNWwHlY4HZmjTvTMqN2paYm48hNNQFSvDtjnfiKOGf9KEjWz4qTXIEA5xQ97lgBb4QWDNirMRIZJm9gtiTsrTFdAWdOUrI4l/GOhdM4T9+5LsCP9pl4riuRyQ/sbzLbpslMK3EGTrwaqZDxU55up90Wn6c7VcK6ETqtTYPCMmOVfiCkfjpCOEF4kD+ADYigWE20MghX5yaEjHO5zd5PR9Bp0ywd4laJC7BD93UzNyvDRtQgS7HeHbwkrrSe0LsvCiiyMwwidq8dplrdjJY9ZButSpoHyFLYUgt7ChWc8Avt1Lr+KBfUu+qkMA10t2bN9hwiXHP/18FqiUmJ4C0m0s5USMViOoKclrYNtqFXsyJIeK9ztsS3rJqdZtAhpuDkXjrzgchW8zE2Ft/GPht5gPwkgNbj+9h/9znNS8q7T"
    AUTHENTICATION_PASSWORD: "AgAKJakhI5WXoy2/t/MuHei/Mlvpuo3qOgsgY2vPLuqVnMczfO8yxjE+qLvhaZUv7TBD/mJzDk1v0nWywGdqRBUjT4SxzPBA23CH3Z8S7nMMSlGc89Und/Rm/B5K2nXZWPlYrCwMkajSm4ewaBiOFFlRkI6GPFLL1lnlu8xgXkivlk5r9cLsQJaaevjAsHhdNPdYicUiASgMs26CeYeHN6UqzYXG4pPGGO/S0boRs6zNlhIG7G8ANDP5/uLDDcntXMrCdgO0mWCEbyFpeGW83IpITD4rdfuEM3bXkGcPwIVF+h/Px8oZcvnH5ClL/9u0OU478dVQeujS4/43KBsYpexeGVTFd/besUL60dJXCkGl9sUlK+YiDXBK2wMAeTc4r0xC1VV3HgecTWss1jVfx1odSK68eAyhoTsSfx2RVTGa6lC6w/CV2JM7v1hTXtEtGz0uLevL5yq64Oaw45cs0CMnZX4lEah3jVEQjD6Hn9dIt1OmrEVXngC/ikn16VVsHmAHx5hopo/NHNvTj2Wgl+TwSAxk2M9+5dZHc9ocbvL43OFO1e9HJL/rgnlU3ugGNVUZJbO7QxSzTQ8kkc8rPi0ExlaNCtou5rE7Wh8aQ7oYf20PiVekfCtEjfCf9/EdMvagmJYe+iljOYua935RWUaiaj3JQCrZvDOadkpke/0lhUODSU/zTW3ZeJR/NXBZuwRTUvzZkVClQp6G+65imuOW"
    PRIVATE_KEY: "AgACTAbfQZce4ttBoda3QdYktYC8d8kS2Z+ILeSrbhg3oGW6EYC8EKes2sS4nprM3gvUp2pwHTlozDKKG4F+Mw4VBgVOFtGWuvd8ZGLbEsNmVDs42mL/XWkzZCxKsdsW6ldMq9/aFqXrEccj9WwLq6lXibrIHT/SiR3tK+ngtd4ja4skDDG5Gta3lnrB9VW38O/n4ogIuIadPuuqLD56zOxoc1yrbP/vWODHy1NKMVjNpyzXdAG38CcfiCXAhTs5PAk5RPzCgakfiCkEM2tlqI/ZYoOtCdfRa/NYTFy66VeWGaxhKaFXZzq7sV3o6Bi3kue1ir8NuP0IPRO/dRRs+nA6ZpkJCi6VSlyJfXG/Vejxf67SC8eOVm+koccRtgahY2L6mhllIHKsNndM3lvBshD8rBvsjwK+FCneHxnRXKKDP+F4l6wKUj8ShEVBoC/26TL7wwL9AMw19JGxJ59K2ve71dCiz5yWJhmOQqSNLC14si7o0jVmsNfMqRqdQdHjY2gtc9/tNew+VqkIL26uqsOpRThLwwkOoK58hsqGGSed9se4KXvBoatqe/lUqN2lSd+gUkPSZ1Kpm9U7Qvc2TB6AK0Ab+H+Ssvw6CTMbLQzQTthVUuk8xEGrjMP91NnH4DkmSDVfgKLb4YYfbd/pfexzAVfB+3SzFjHfwbdBTCppyGnXJWs4hZzhceYCOnEjrMda2R7BRX0eS3i3AWdQzw94mwV1IcHHQi+Q07tm8SbkIhRsBGGixBZiZpbkf5BfOwdGs53tEJL0vihfD+j27L5Spgkni56tGtjyOJyNA7H1Re+PItg8pzUiqTaArQDJqrWR9DtuMY6HSDtMPv6wSGzYStHZUnsZIGngdqgtOTOoJQ=="
  env:
    "REDIS_HOST": "172.16.1.6"
    "REDIS_PORT": "6379"
    "COMPILER_URL": "https://latest.compiler.aepps.com"
    "CONTRACT_V1_ADDRESS": "ct_2Cvbf3NYZ5DLoaNYAU71t67DdXLHeSXhodkSNifhgd7Xsw28Xd"
    "CONTRACT_V2_ADDRESS": "ct_2bvoxQ6cwwzoFASuddUxzsYVBZUet9KGHRAp7i25xsMXEWvSvx"
    "CONTRACT_V3_ADDRESS": "ct_WscpdLQf6ZZxoVqrsEwUwmuAEdzEkJii5W5TzG84rVgHeK6BW"
    "TOKEN_REGISTRY_ADDRESS": "ct_2Ga3mNT8er2zYjGKx7tJggn9nVnYt5UzmH9x9irRV4ayg4sfLL"
    "ORACLE_CONTRACT_ADDRESS": "ct_2PbBVGroJ2G618tHbWEWRrrxxf1BAn7Qt7BoNcLh3LqsSck8Lu"
    "WORD_REGISTRY_CONTRACT": "ct_2vTMtHgJTxTpsQ8Tm3o6DmfDkhc3vM4DefV845Yp9FSDuS6YWB"
    "MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw"
    "NODE_URL": "https://testnet.aeternity.io"
    "IPFS_URL": "http://ipfs.prd.service.aepps.com:5001"
    "PUBLIC_KEY": "ak_fUq2NesPXcYZ1CcqBcGC3StpdnQw3iVxMA3YSeCNAwfN4myQk"
    "AUTHENTICATION_USER": "admin"
    "NODE_ENV": "production"
    "WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/websocket"
    "ORACLE_GETTER_ADDRESS": "ct_XabcJUxaZc1w5X4WxD2WUVTLPkZX97HFYzhuwkhQXc4ZzDqDF"
    "CONTRACT_V1_GETTER_ADDRESS": "ct_2ixHY4bADzDY6ZYThGixnjYa6w5dtYoSoxtCThWvZ7SGgMGFWL"
    "CONTRACT_V3_GETTER_ADDRESS": "ct_414KdQa9is3wiq6AKV7LLk6z2UN3Sy3odmAZtenyYSv35h7fv"
    "POSTGRES_USER": "superhero"
    "POSTGRES_DB": "superhero_backend_testnet"
    "POSTGRES_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "POSTGRES_SSL": "false"
  image:
    repository: aeternity/superhero-backend
    tag: "latest"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  service:
    port: 3000
  resources:
    limits:
      memory: 3500Mi
      cpu: 1000m
    requests:
      memory: 2000Mi
      cpu: 500m
  ingress:
    enabled: true
    hosts:
      - host: "superhero-backend.prd.service.aepps.com"
        paths:
          - path: "/"
