app:
  image:
    repository: "aeternitybot/ga-multisig-ui"
    tag: "v1.1.0"
    pullPolicy: "Always"
  ingress:
    enabled: "true"
    hosts:
      - host: "ga-multisig-ui.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-10-ga-multisig-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-10"
      - host: "pr-12-ga-multisig-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-12"
      - host: "pr-13-ga-multisig-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-13"
      - host: "pr-14-ga-multisig-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-14"
  versions:
    - version: "pr-10"
    - version: "pr-12"
    - version: "pr-13"
    - version: "pr-14"
