app:
  image:
    repository: "aeternitybot/ga-multisig-ui"
    tag: "v1.1.0"
    pullPolicy: "Always"
  ingress:
    enabled: "true"
    hosts:
      - host: "ga-multisig-ui.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-15-ga-multisig-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-15"
  versions:
    - version: "pr-15"
