encValues:
  GRAFFITI_S3_SECRET: "AgBCo2BkzAq0lKh8k1NRYEEukyuq8tveH9E4t7ge0Ad0inJFv3cfcXMYKDA1s5HXDOqT3HLLWBim1RW9RItihVEh8ht5u1mZFeFgZN54NNCDqdBh54RkPXM+6CBX9rew6LdLozWbJAPYxsdCofE4+52ryhGgqQKFWM2VVaQyAj9wfDbccplARpRcn/s+xHXP4Tbe4xZfllIgNDddnwOxLp0YTuubASfX0FrBIDWXKVPK4+rY8R/UI3Fuxz64xMcg6L0H8I1iSdlm/Njya6lBWBM9BSRQVZOfGHZVHwvjrk2X9KjtNOMlRBRXXSty4K2JbjM0o57Qts+rMWpjfO/1O+T/xWErYZWzRWNSJICdg8wSWLSNjNDV4ag//lHcXdqxhjztIQTduGzIsKf+svpypM5e45LmKOn+Jx/EnAEU5c68X8sUFVDSwkt6KR7lDtJMeWPpaB3FusyGifZ10LBDdc1nIOdVZ6f00aCfUSmE7FDGjKcoCFJi3y3AqHz5jp9oWoWoMN+3LKpecUo4Zd+OpmWECP8pm4TdrtayJ9qzOsXbMlxYFLHgy+sI8G56ZiaiV2iJJN7HYHHza3k809WkKj7uR8vwVwYa1bDiRwbBr1g3lkTQpVmqla1ooHU0r9OFONinyiUlFhF8MZ5WovP1JVfmMsg9f0iyjiTXWSlvwEP8M0wfitWzcIvgkeVFCT1GScTGzCv0bj/8/c1KY2BNticmXoRHrzqMUiSH7ESAB1u9LdMnDwlJPcTE"
  GRAFFITI_S3_KEY: "AgCqht2BdNovRevMR6+CvCEzCiD0CJvnYDcA/aB82Cps1Ms8jcL4Z/3vMsk2Ahet+iMJCk083S/X/Mx7j0BrBmw4vGgCExEVMYkUBe4hRX+scfDJ+C4rPKh4Gcc6F/PH8OOM2WoFJUzyW3cJgo+MnXeIpovTqXJEcCqq/PuUq7p2aaNuxPLyEfb78GehCKFzmJ7ij843vSRltSfubHdaib6VYSpuIznN62S0H2eQC8317HZtUluhAerulNtPeaJgPeTNdTwngU+lrPehg4faZCg1fPjYvso06OB4Jiu2FM9fBPrw7V2QntyB+0B+38CnuJKLDgjMjVmresKIorMkCEezPu5+4kz/gva/ddYGlXIzZKDt2YDJ5Bcuz3CpsmGg0sav9TpBO4rq8HisQXjPLqogD+2f3YKNrLzQIf9DTKW95gAxmNaC5EDU7LxkD5UQL4vqAgAJOeLteaLOrL4YiqE0NNE30giOvEbNfWoUdW4I4Hm/xbAl+/Til9lenTtUI2DsOROskhWG0Yj2JTzuVXb7dnV2VrRjfcVyrMlzPiRWkE9c/7FltuyI72AuYsaE6aR6GOQvup5YrAlOogvk8Bzb/ZmFru0bdGFV3FDs9Daw4k6u+VfAc7E8GdAesbPjtYI/vkIicSXlXhteC2/FdRf6ITmnzVwpxRQY/B9SkbLrua+ZuDKX1l+ftzh6CwCA966VFsoykEE9ygC+psPAqa8YOpIF6Q=="
app:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "graffiti-server-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
  strategyType: "Recreate"

  image:
    repository: aeternitybot/graffiti-server
    tag: "latest"
    pullPolicy: "Always"

  resources:
    limits:
      memory: 288Mi
    requests:
      cpu: 200m
      memory: 288Mi
  service:
    port: 3000

  probes:
    liveness:
      enabled: false
      config:
        httpGet:
          path: /health/testFiles
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      enabled: false
      config:
        httpGet:
          path: /health/testFiles
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  env:
    "S3_REGION": "eu-central-1"
    "NODE_URL": "https://testnet.aeternity.io"
    "CONTRACT_ADDRESS": "ct_uJ5NKmuX7eX79QPerixR7Z8zEdxKCKJw1yzHjX1tsmRP17tuP"
    "PATH_IDENTIFIER": "/"
    "IPFS_URL": "http://ipfs.stg.service.aepps.com:5001"
    "S3_BUCKET": "aeternity-superhero-graffiti-stg"
  serviceMonitor:
    enabled: false
