
app:
  encValues:
    PG_PASSWORD: "AgB4U4c6LZ3kqMoZdjQiHs5Qm5RNqw1dihQkFRx6GbtiMw4V2ng0/x6Kst/WEbnQWPGk2r6HMMMcR0LqedmNVh9xU/ZrAbGOM1oGEh0StUlzHGPHYJIyvxjkMk7v8/kM4bpsDjcAJuR5ugPkwub49oY2iDIcrU/9O8gzifQh+2u70QKNhTabbfzxSWR4Ce8m3dGuqFy+hrw6zYZH5db6VwxA+YvWqA/Nre7+ydrBMJRb/HsMfbOb3jxzyrB0FVURLBSOBtKJf1eCtvQEEj31NPawenZarJSDM2FcVVEUesmBaGl0XtW3mGhRWv4DuvALPnijRjib3y6SuXNS6shV50YResfsgDNf7BdqWPncCdY1zvUlk9XxL7Vg7D7UR5DZZUF+gydlsRP6n0bydU9GAuuTdpe9+qdQBQDAPfBWghEZ8M+UwacFh5ddBoWEVtOxrQfmAQGqpkif6RikQwm8BhsfOWcc006u3jWtEQTdh30Exc7IN5UM6tif12m5cnN3+CCj1jW9qQ3OfbostGV0h2Dke02c2NbvxVrpCFwB3Pvv/dOGvS8jSbq1PRmkxQmxTvKSEhY1xr3Kisd7XtzM4iw+pyfAZZI2YtwvYgxmSKqaEQYG1N2HO54HiE1TMG9aMfDztPyoet6Dl44OgCHg02Gv/+dmI3nCBdct7xosCM2ta/3A85Kf0nJMPFbrKUAPH5C1S1BoLW3BhHg4"
  image:
    repository: aeternitybot/ga-multisig-backend
    tag: v1.1.0
    pullPolicy: "Always"
  service:
    port: 3000
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  ingress:
    enabled: true
    hosts:
      - host: "ga-multisig-backend-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_DB": "ga-multisig-backend-testnet"
    "PG_PORT": "5432"
    "PG_USER": "ga-multisig-backend"
    "PG_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "MIDDLEWARE_URL": https://testnet.aeternity.io/mdw
    "NODE_URL": https://testnet.aeternity.io
