
app:
  encValues:
    PG_PASSWORD: "AgAlrMEZx4avsSyrCHc3db2PxSZKJrkrhi1HcqyXu6aTatkfuQjojpt2SNBZU30ZJZRB6/wHoRvOdH/C1SKP1sl81HC0sy0VD/73a0aXekQKG8C1ZVWxbppTXIHP70UYgdVlMuB1EdZS22Q0zZtWamMkBXPq1KUNrSg5zP3pQ+oQXXf3LhXGJP25AQzYoGJn7138B+9TPg3jneYlZjOWPgzJBi7PlryEXPn0gwt21vkrjHNpUQsZYySqPlnXvjlM/e8kckIXmn+dhoU5cUJZ/Nwhr3BGt1zfRAyB4AggwxBx5OKRNUjZUkrqVy73c7cpjEaemktbyAcRU9BPbujaD5PebWusxSUIowU7KwdVfivuRFTPSoU4w6aEZFbbpqYEZc564OF/8hA6JrjDPja7Qe/QNkP44yF+joUwD42hvnjYNvp4qsfH/kAyg57glPPcV3bhZOL7VKk52hVpAfF4dFg3+1831L3WOpPd/U6mFZKG1+ybq8GTuMmTQOKBZGtOcTrlZWHVZ570/v5PvZu17czpSxsUTbgREuSLHuOctxX4mMxUFuaFw61OkGZqXNQdDpVVHETgDZ5fZLEDovDlrcyP6iLWHgzVNmFJSiB/beAQldsZUuOiE7PYJ1H/b886+BH+XNVafeitQvbR1x0piJXWiZpbfADyRc3DX/Y266iPsEZK3Go5xpbGQNCRcM/Oc5gUae6pI4qDtMad"
  image:
    repository: aeternitybot/ga-multisig-backend
    tag: v1.1.0
    pullPolicy: "Always"
  service:
    port: 3000
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  ingress:
    enabled: true
    hosts:
      - host: "ga-multisig-backend-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_DB": "ga-multisig-backend-testnet"
    "PG_PORT": "5432"
    "PG_USER": "ga-multisig-backend"
    "PG_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "MIDDLEWARE_URL": https://testnet.aeternity.io/mdw
    "NODE_URL": https://testnet.aeternity.io
