app:
  ingress:
    hosts:
      - host: "governance-server-mainnet.prd.service.aepps.com"
        paths:
          - path: "/"
  image:
    repository: public.ecr.aws/aeternity/governance-server
    tag: governance-server-v1.0.2
