app:
  image:
    repository: aeternitybot/dex-backend-mainnet
    tag: "v1.2.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgAWnOvy1M8dQnG1sbSoDI4vdEW41DRDwreznNxRxa91GjF0Z3NpbTsusTbaFD6tkOD6XgcyJfF3jqsb0xECibeNxWwtng33uFhsu1GONoIo3vqigCQQNJqjOXzGKvwUhlLUe+CImZ4GXJ6SRKTZlWdcHWwgtQgvl03hHk0jM0AJlXhcF/r69qTUtgmQ5ma5zPdeZsVtJI6SGUmzW3F3sl2UD4YoEEBzATiRriC+WU81SUcs0IC8WVDnQZvxs3rh/y6x2BwGIt6DFOXmbQDDcxXDtUAWqhN8L/4A0BVJIiPhOr29Hy93vJrd3CPzLtJ1L3DUkdB1Xv5CW4qAgN24s+EMHnLoDPMpv3W61Hls0DAZ/9DYoOUVy275X45GTbEgoI1wOGAIY8wZs7f1Dg8NwjDxSU+/q9AVSxNU+VBQbacVQ1WReqgCzHhE4PRn+HFZ/t3I4po2zi1M5mbatqrgwhqJvh7F4GvyOcNNuY/AK+AgQCUggYVhXUCNqzsfx9WqaeZ8huoZ+8cIND0J83VMWTdUbH8fH4CaBGasbuXbe2BiEJL4s7c3+/nI31PCOBmY8xZn9fS+fYYZQGXwQRJnJXFscQC/yha3Z+oAmrE4aYcsu2XVdjut+UYdXWWkS66gQtSsnuAYkGff2Q4x8jlTSQd6dy3vfhfMRJUdbwN5O3xv3bLus4JmS+7jI/Vs4pXl2VSDJ6hClg7ZURfBmms="
    AUTH_TOKEN: "AgB2SMzhPUeKZhzRh00gbQ+U1E4E9hhBJShCyZjafu20G8CC4tAihlDzleLRKoBvXrBKjI5XrzXlR9QVFFN3NmXvVQRbs8ACbr3O1BJH9JhY8/a0FkOP9gqd9N9Iwj7FRRp+ePND+cyFZzRbqycr+EEHtQIvI7TkYD7ycQFzxQi1CisMR3OU6J9+JgDUKLKM97rHBkEzBC3z34p+CMcUAO/6n3pI9Ydvu8pASYIWvOePUFPXHFF1+GMfXPcrI5cg0EqIqNbjCh1XuRk23SVcfjCMkTCvwRMdaTkvHFTizGOBxaGiAhOuDcPPbIlk8qGJezrZNwEMSc/tgUjyQSmb5GMWzy7jV/PUg5cZhpYTpCSen855h3f8fqIQSSGHN8S24uQPY+gORTFkfkxZwui7C8yQgX5ueInDLDF75yx8L8DjalMmibQAyaO1BuXR1Ak+sgC0A+DXL1Aufd02FotyFyibw3MFa5I9lG80Xix37VtCN9g7LVmyVe5qhgVGKfAhdvjODO/z2GFuq50m93Jl/ipaxpTIPUfc7GLdRrHRlA+k+EPOtznuy/9DQQSeWZcag2aHOLePwMBh74Cq1Ia9+/u2Sv/s0LBvkvlSnwKk+14ZixSahDWEwIKTThmGMMKm6Piab3Fkz2BgjopqZ2bKWJpsTEHSBYo8Aj8zeo3ZpDIVNOq9LIugGI+mHg3FRMHls4g8r/OB+lyRhFbsU32ZFP5KSWdsT4sgqD3XyNfUJY5UxA=="
    COIN_MARKET_CAP_API_KEY: "AgCMlEXQFUDoj+zd9Mie0jMVCYlmjG6EriUOIT4BL5miLns83pkBa2DiiJPau3zVX1Oog1KXE7sHR0hnb8K4c8kqlFtvsZodugBy+MaPDrw6BrPBStxT7gvkCSuhuna3P1zatXmgbuE9IYi+HUoSqDLJgQkOm27wr12kH6/DDxdDcYMr4WRwBhmW+Ah0QEEKAmc+wduFebGC/4Z+uS26GN8RNaCub/cmjuRb7mx95YfJ1wXqZCJesbUKorM7e4G9zaqSBo3zM263asemyp+gpWT+6dLigY0p9ZcGApVz0vgyS388AY43rxPm9kk//axuzz7KjE5mAiuszJf8N4eijAdVxOIsF0U5vEM4db2Pm/77UkdfHnYfb6+08zqf++eBhRJ9ufe+Hf9QUWgIgZk9+BlGK4iYBUFFcs8nzz9hcpTCFl2mMQkXgXrmdL8FjRa7Gl0f3j4b9sQjkclU/fARbgehGdkV7Xp39IyBgryfp+ibnSeatEAfJmvZnjUNh58Y+fXqnzcTCxxuOK2jrABGZQM5xgO3/BgRCzIdQF5/EOcHZX6GY2P0/BVhjLGVN68O7HxpqMhWzEqV38pI6gDrTbG0THCsxvgg7Rq/fYKena9h7O6v5G1q2bn97alN3BLCEgPrhCKow6f1dS5PBJ+EUi/766gPU1ey4Hgeo4ZvCW0s2ZhUwVVgHS4m3jXSfimFygQutx7qwKgGTIXlMdQxdQJ39PhyArTZMZA2Faw/MdSR3JQT8dM="
  service:
    port: 3000
  resources:
    limits:
      memory: 4000Mi
      cpu: 3000m
    requests:
      memory: 3000Mi
      cpu: 2000m
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-mainnet.prd.service.aepps.com"
        paths:
          - path: "/"
  init:
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env && export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?schema=$POSTGRES_SCHEMA && npx prisma migrate deploy
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-mainnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.service.aepps.com"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "mainnet"
    "ROUTER_ADDRESS": "ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "FACTORY_ADDRESS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW"
    "DOC_PAIR": "ct_NNmdSt3Ws4r87pESGKrhGb7VJmC8zpZymXNJKHY8bTLaFttsi"
    "DOC_TOKEN1": "ct_2dE7Xd7XCg3cwpKWP18VPDwfhz5Miji9FoKMTZN7TYvGt64Kc"
    "DOC_TOKEN2": "ct_7ur9ypT3a4tjxxv5iG6zEQDQhysNtCKr6tyc7PkqhtRmEw6yY"

