app:
  image:
    repository: aeternitybot/dex-backend-mainnet
    tag: "v1.5.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgCBaRQIpimoc1JvtXyxVDGI+p3yZkuxoEVssfwehfRKHoYzHFCl+FoOIRGcGxkUQevzN7oMshRRC0HGyip1nH2ky7D/iW5o0DLtpgAEbqkbs43LWBvxNP91BhOx74KqB4gedfDrArRPvUPn/zwci5Tn5xMT50IkzAetu3VY59IvrEMUOWTBI1iiccX4mRm8bYIQ6eAmFOW9QzPF4JPOdTgojVZCR78WPcYy2MH3QQnl8wbX1Bp6+Y4ior21ZidHoAN1/xJGQutYSIXzwIPmOTRCC/hbix/yW1cjyUpdiDwWoFHBOi7ET0+wcIdOqlR8J64FPAtyUw8dMM46w/qkUR0ZuzQBO/PY0HKsK0DJTecm7C4CCtmut9UAih+TtINzSiJo87kAmK5LgiRPRqGcfXig28x1UkdN1HGrvtx81o5dt5WcpbQ0EZw+E6WX73SxhabmurgBehT/CADyrCSrugJUv5jooRBeFBY1o/CbyvXb61DOWZ/mDqX9uPkH021cc3mdlWIcwOttMk1NOmLQggX09CL6wBclWfvsJbgoOTF8Ss4aWPIZmCd++8qHCUQNESws93qF56mRs6LNKRHJ9rIq5oJ6AJd+it+6MLXN+cbAKRHLTDCyRvRAqWj29xDtl2UX9kMrCkoR5F+DnoJHVkGvemizVWzbeJtCyqGeW0WLhLruG1RJn75nPwAsDozD3hR1p5NsJKvvzMz/N2w="
  service:
    port: 3000
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-mainnet.dev.service.aepps.com"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-mainnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.dev.service.aepps.com"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "mainnet"
    "ROUTER_ADDRESS": "ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "FACTORY_ADDRESS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW"
    "DOC_PAIR": "ct_NNmdSt3Ws4r87pESGKrhGb7VJmC8zpZymXNJKHY8bTLaFttsi"
    "DOC_TOKEN1": "ct_2dE7Xd7XCg3cwpKWP18VPDwfhz5Miji9FoKMTZN7TYvGt64Kc"
    "DOC_TOKEN2": "ct_7ur9ypT3a4tjxxv5iG6zEQDQhysNtCKr6tyc7PkqhtRmEw6yY"
