app:
  image:
    repository: aeternitybot/dex-backend-mainnet
    tag: "v1.0.1"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgCce6i7MDvaanErK1FJXcQW9WHFnWi00O+8zHAQDL/9C8/Q48xQzu255qD5pO80C+rEWa7Td6EhGRgDU+3czVcb2t9kUY98rFW1Y+FbjVPGy1RtNvOZnOwYd70n4bTJseXLtVhTqWfc1U/ZVQc9TwjPKCXAkunJ/dFIIchqU+MbH/3dGSHLHYujPY4VOL390LjxHDJmvj8zbytG/NjON9Kar3cm5dZ61Y4Vpr2rEQqrRWL1vqgp3aOcoypnbOUZycLROgEWKJIV7RuieZK/dqZTnZ901yPYAcTTrQS13bz7O3DkNqnEAeo80yX6OJlJEjPeWsMG4vdkKzYMxmf/21QgHU29ShmQYoXgK2TUyyL0jMmbuKOJSOGD8HPhrKje/4/MK/bdcwiR6kyUAV5g+SmzF4OM9Gw3cBdZkeOSUuQL/qYBXUGmJ6HJay79JBdbDz55tESCiJdu4+WtAvwJqF3MSps+dQnnCnCB7kkJeiHx/jQUUprHw36p1QWufe9dNcGtQ+4jlbJuSOmpgsMiSMnEO3pzfWR0293PwS1zEsg7VeDOJ+TcbwtWvO9s6N7gO784dYyjBTAgCQNIV5XdqJKaMwVTRR5wffHEPPMLOS3Y0IlTmImPzyaA7++iCYN4PFczsCzWczo8WUu7+0dlvowr/KcsPNlTQagUS4fk5zVGEW5f2X8FYM5Vz+Eo7ZLhk6vBN5RS6apBsfcg/A=="
    AUTH_TOKEN: "AgAMrkT7a9iVgjKjBhVw38yHdxi7GU/0mw57iMxNSjFYBDRvE+SjboyM5VOZgz1nHedRj5/9LC1Kqr/3OVo+Ax6diwkRxxhcqROaBP5iatiVg9Ii+gqiXYzTukX1us5ifc/h7i73e3z0I2kZ6sH7+6uGdbPhWi2dQVi3uld9PFx3bQmSCK38ZTjWPRhcnt2lqp9C6bus6vZjjyupsrGjGAmD1gQZtX5Iy2HyumitP0NTtLJp+UG6hpBMpZz5CrDGbrFIxSJFJ8AoXsDrWDyB8gHXWAFJtR/tNeed159l3T4Utrd0HXRLrrtrPbIoNktO9mqG0bfCbW217hsGR0G4lYfpW0ly+jLJGFSvY2r3Urj/K5JLlYyV70nwpE5EgRm1aAy66G+e1ijhAupZtZhQNo9+40dlz9pC02KVdjbJY5ZjE2C3HQCAaJnesAkbu+wcLtx3CAoZUfdXdKzFFkNNUr0B2QVd8M9UNWUL/hoirHJokZ8mmic4Bb1JdA5ru+8XRfzqVwWVDe5nC0vBZDU/KmHDoLrgYmm9orqxZmwxO/QvTV/J2ZR+BIRD2xqoPuMsTEZ04VfoiYmtoeoy9jEMrIn/5IZZHwWkUIyWLovYgnpA2euOVhysGPnxwpKIfR0z7vyVCI1nVqJ/mJxwo8u4hFJ+2v4NQt61f9NLqAJG9spzJQHuDLrNaBAR8vNBleOmc9JLXKKoHa45ViscFR4UNpbMzSq32lg0iCX2D+aXmMEV3g=="
  service:
    port: 3000
  resources:
    limits:
      memory: 3500Mi
      cpu: 1500m
    requests:
      memory: 2000Mi
      cpu: 1000m
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-mainnet.prd.service.aepps.com"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "postgres"
    "POSTGRES_SCHEMA": "dex-backend-mainnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.service.aepps.com"
    "POSTGRES_USERNAME": "postgres"
    "NETWORK_NAME": "mainnet"
    "ROUTER_ADDRESS": "ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "FACTORY_ADDRESS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW"
    "DOC_PAIR": "ct_NNmdSt3Ws4r87pESGKrhGb7VJmC8zpZymXNJKHY8bTLaFttsi"
    "DOC_TOKEN1": "ct_2dE7Xd7XCg3cwpKWP18VPDwfhz5Miji9FoKMTZN7TYvGt64Kc"
    "DOC_TOKEN2": "ct_7ur9ypT3a4tjxxv5iG6zEQDQhysNtCKr6tyc7PkqhtRmEw6yY"
