app:
  image:
    repository: aeternitybot/dex-backend-mainnet
    tag: "v1.7.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgAWnOvy1M8dQnG1sbSoDI4vdEW41DRDwreznNxRxa91GjF0Z3NpbTsusTbaFD6tkOD6XgcyJfF3jqsb0xECibeNxWwtng33uFhsu1GONoIo3vqigCQQNJqjOXzGKvwUhlLUe+CImZ4GXJ6SRKTZlWdcHWwgtQgvl03hHk0jM0AJlXhcF/r69qTUtgmQ5ma5zPdeZsVtJI6SGUmzW3F3sl2UD4YoEEBzATiRriC+WU81SUcs0IC8WVDnQZvxs3rh/y6x2BwGIt6DFOXmbQDDcxXDtUAWqhN8L/4A0BVJIiPhOr29Hy93vJrd3CPzLtJ1L3DUkdB1Xv5CW4qAgN24s+EMHnLoDPMpv3W61Hls0DAZ/9DYoOUVy275X45GTbEgoI1wOGAIY8wZs7f1Dg8NwjDxSU+/q9AVSxNU+VBQbacVQ1WReqgCzHhE4PRn+HFZ/t3I4po2zi1M5mbatqrgwhqJvh7F4GvyOcNNuY/AK+AgQCUggYVhXUCNqzsfx9WqaeZ8huoZ+8cIND0J83VMWTdUbH8fH4CaBGasbuXbe2BiEJL4s7c3+/nI31PCOBmY8xZn9fS+fYYZQGXwQRJnJXFscQC/yha3Z+oAmrE4aYcsu2XVdjut+UYdXWWkS66gQtSsnuAYkGff2Q4x8jlTSQd6dy3vfhfMRJUdbwN5O3xv3bLus4JmS+7jI/Vs4pXl2VSDJ6hClg7ZURfBmms="
    AUTH_TOKEN: "AgB2SMzhPUeKZhzRh00gbQ+U1E4E9hhBJShCyZjafu20G8CC4tAihlDzleLRKoBvXrBKjI5XrzXlR9QVFFN3NmXvVQRbs8ACbr3O1BJH9JhY8/a0FkOP9gqd9N9Iwj7FRRp+ePND+cyFZzRbqycr+EEHtQIvI7TkYD7ycQFzxQi1CisMR3OU6J9+JgDUKLKM97rHBkEzBC3z34p+CMcUAO/6n3pI9Ydvu8pASYIWvOePUFPXHFF1+GMfXPcrI5cg0EqIqNbjCh1XuRk23SVcfjCMkTCvwRMdaTkvHFTizGOBxaGiAhOuDcPPbIlk8qGJezrZNwEMSc/tgUjyQSmb5GMWzy7jV/PUg5cZhpYTpCSen855h3f8fqIQSSGHN8S24uQPY+gORTFkfkxZwui7C8yQgX5ueInDLDF75yx8L8DjalMmibQAyaO1BuXR1Ak+sgC0A+DXL1Aufd02FotyFyibw3MFa5I9lG80Xix37VtCN9g7LVmyVe5qhgVGKfAhdvjODO/z2GFuq50m93Jl/ipaxpTIPUfc7GLdRrHRlA+k+EPOtznuy/9DQQSeWZcag2aHOLePwMBh74Cq1Ia9+/u2Sv/s0LBvkvlSnwKk+14ZixSahDWEwIKTThmGMMKm6Piab3Fkz2BgjopqZ2bKWJpsTEHSBYo8Aj8zeo3ZpDIVNOq9LIugGI+mHg3FRMHls4g8r/OB+lyRhFbsU32ZFP5KSWdsT4sgqD3XyNfUJY5UxA=="
    COIN_MARKET_CAP_API_KEY: "AgA7p7m45k+LdGA946bs4u3Vpvy31RDUF0tRp1Qm80Kpz3LgtQpVOLZ6tEGSZCHA1KmmIRJukFu5VfvrzlvtAGVAkpkhiSyEYtkwTRUZUNNjejPxEYSLp91vE1cHAaetzX3Ii2+ZjiZ506TWQ0AL6kB1vtqxnhtQxPZ2Ml4mGEUJ9kZaQc+MJhrTx6726oHraEXZ0x1wdqpeR4xm7F4OIqFnvW1pQmvE3ffJi6Ocw5EOiohrWIZrHzVxHl68aoFO9C0kYEaWm+V9ybekbzwsIAW9C5pM8Bgkb0rZVO5c7c6BcuGH5z2bhDsc8WGZNld1FZ641mGFbEByFX0zyeU98J0pJyY9Wif7b0UqY+x5NL4k7laphGtJyFPtIdyBYgmruKYYxix7TJ8L65fk/g5x4YRTKgTRKJQmqePa2FqDdYSUW7cgg3JMkv+zl4Gs5BlBf+1XuCopHKwU3B5WJLsjDdMHCtbsXFNhjQlEMo4xQ9D5qNOdDihsoANYqFDZCxH2vdExVvEzeixjC9MfpPKz5mxt3fAPvKnBSeTMzhNABIHwFCbM+Z83soWLwmsbMlO7LMR9ezPUt/0QH3lGw2qs91FrzNps7RnjXFowOP9LxoexntrWymZpJ9VhSv2QBNV03SxnlTfY6RA4ZS2Lfa51IqVh35hTIiYYXl+RoxyH8wKfLmzSWqe5Cxh4sEsKEk5Nch+TTJ+1+3MSqqqF0cY1ZQAxia0yYqpvs5AU4YQ7bNlklNpmeJ4="
  service:
    port: 3000
  resources:
    limits:
      memory: 4000Mi
      cpu: 3000m
    requests:
      memory: 3000Mi
      cpu: 2000m
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-mainnet.prd.service.aepps.com"
        paths:
          - path: "/"
  init:
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env && export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?schema=$POSTGRES_SCHEMA && npx prisma migrate deploy
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-mainnet-app-v1-4-0"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.service.aepps.com"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "mainnet"
    "ROUTER_ADDRESS": "ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "FACTORY_ADDRESS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW"
    "DOC_PAIR": "ct_NNmdSt3Ws4r87pESGKrhGb7VJmC8zpZymXNJKHY8bTLaFttsi"
    "DOC_TOKEN1": "ct_2dE7Xd7XCg3cwpKWP18VPDwfhz5Miji9FoKMTZN7TYvGt64Kc"
    "DOC_TOKEN2": "ct_7ur9ypT3a4tjxxv5iG6zEQDQhysNtCKr6tyc7PkqhtRmEw6yY"
