app:
  ingress:
    hosts:
      - host: "stg.trendminer.fun"
        paths:
          - path: "/"
      - host: "pr-4-hexjump.stg.trendminer.fun"
        paths:
          - path: "/"
            version: "pr-4"
      - host: "pr-4-hexjump.stg.trendminer.fun"
        paths:
          - path: "/"
            version: "pr-4"
  versions:
    - version: "pr-4"
    - version: "pr-4"
