app:
  image:
    repository: nginxdemos/hello
    tag: "latest"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
  resources:
    limits:
      memory: 1500Mi
      cpu: 1500m
    requests:
      memory: 1500Mi
      cpu: 100m
