app:
  imagePullSecrets:
  - name: dockerhub-secret
  image:
    repository: superherodotcom/acad56w
    tag: "latest"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
  resources:
    limits:
      memory: 1500Mi
      cpu: 1500m
    requests:
      memory: 1500Mi
      cpu: 100m
