app:
  ingress:
    hosts:
      - host: "stg.trendminer.fun"
        paths:
          - path: "/"
      - host: "pr-6-hexjump.stg.trendminer.fun"
        paths:
          - path: "/"
            version: "pr-6"
  versions:
    - {version: "pr-6", gitSha: "b17d0461"}
