app:
  encValues:
    DB_PASSWORD: "AgCQVU51JCXvtmGp1WHFX3Ti51jHO6UvUofrs5wuvUxKgg3TP3iinNEduOyy8b+R5dCvMH37nqDsvLLBSslomiSinlHdj1FazzuaFxAxI9gonVy5HvKrLWgSQIP0UiYArkrQN2jYhIq6VR3V2gZHQ9mnofnUV5jM0joRAPzr6klxerIWkT0EZbj9jStDwTA18D6zfSTbxCLShpAs5A7ZXRTjGTmlBVhGZX9e2AzOEDT4pHv1VbD1NBxCOmABYsRtuHHUMkdC9T9cAd7wvykgrSmBYOV1zrD37Hk1yvC4RQHO3hauufbMa7TqcvjoFudo4BEpEjji2zCifHxm878/1qCKU1AZVO3WLbxZ8fxbcj5YNkn1v0V46L86hF5RRHkvccLxmsziZze8UKeosdR9IVsdqcFgWwS4cowRpI3frUO9b+AiKaJuiHWJlzO5of1FhUpf1f7OkXmdmUe4Br6Ws/yt3kNnZdi4xDb0fIwhinzEnJ2p63oWqs0CfBOrN23Fw5VPvs4FwHy8eWQYzMtHhJu4M15bBEcgcRLaTClvuEWTGv0l9BtT7R6ad+0ytOaU+IFk5GcwKdrEXRNr8HyLVTKMCr7eiA5iEz3tw264deZBvvVPk6Yz5ImDswbsCoJIGyC9mI4JFiTgUNQ5ZfqSInRUCGCOv4fpfq1OPlbu1+Xjs8FLjjooRpY/Vj5scYAB54RR53zDfrv1NUsvEQ=="
    MQ_PASSWORD: "AgCksMBoCNPGRb4gH8Sh5Yz7z3JS7Sq3DbM+COEoiQA7EzfqMeqQlFW2fVwogG0Shd9YCvrEwyhLh0+tpyUkB6ofRgq1IqpS47idnBbsoPvGHYukauQqSHjBN1rlYQssQjBSpg1vF/0guGSZA/LPxVoaFUIZQ3AYwrrHqPkxCdfH8SUu0wOl74rOUmEd8JDL+bu/ab4tY5ffFiCVfwvlS9jwKdmoRPDUqpgaSyHCe2mpNb/qBgcYCKqLP/L4qf1Qdr4L7sgY7zssHfQ7JsfJmHn4bHdpKz7gAQ5Zshs8HlHtlTPrEJTyRtbcUnHhUAB0xLWRBSD2WY3U2QsUgMCDglAOa0DMIzXZsf4kOJ15HlrAlmNFAVM8X0RHBFlHzmcefR0Hzf1hw2sU4lid3BrYFy0x6YthSJtIFMQJSujAGlOY54+pRvD5o2psM5SSDs6XNc5lkmKHXn/1LEX6uY7tcP0ywCkVfBp7fIj5VJQkskBYE9CD1E8IWoUgyNT7ZJXFtIDU7B1MXZgdRvUCrx7i2S0CMnA4wqRyQDgxE3YkSe+H9gIc0ViKU96OTRKtyYvaJfHVUr6YLAR0ovw43vU4dMMCUO1IagbnCPMxO/Kc2RaDKV6OKBBDPAkZAVA2GNeAL137yNapDSyXrmna+E+M7iz5LhWOLKJyzVPVbfodfjxmw9bJVJbfHE3aLbVjZ4gjKC/eOi3duvyoHyKj"
    WORKER_PUB_KEY: "AgDAHz1v4eD18KGn8f8DWF5yy4FZRI5NIq8TqGtLDqTbucvTQsoFo5CL+YzItuITVVMRpSl93imlgfDokTYwfglm5ghW8U6cyi1+ZnbRdEbw0t+DeQkMzp7TCYjsRfHKkfibZI0wHXj4KC6GSQFBvkH1y1wn+nmr7ZmV8EFwl0rHyMdrNa4e70LJBm5qVxH1Z0H3mGBmxMbOgFRqveIaaJ2HBie1FZpfQbEnVmzL8KNTSjHG572A/iFDdZHPDU/+bqrQtzmmQZWNlLKZHUumCL7tM54bDMvPV8tzaEbvhqqikNObCsbolcH3uWaf8kl/6X+WgCJU2Sr18sJowh6ua24Gmj33fKbmxowvXqa2Jj8nTJpDNDuGamVllzf1Gjja//Fc+zAi+OsIWy6jE0V2wfjjJdPbWsyrsU3mJWm3WaM1sUqGmUe9xP9boNLZOFi/k8+EyFzjV+fuiNawI9fwCijzniK+NyQs3Ym2A6i4pPtN0vzTG5pdAq5kaH5sPl/k3Q7AfF3cG0CprI1bU++axdNebYqMxltM9F5b0HehdZ0Lz6I64Lx2s/vladaGtq7EOQHhLp5StJe1Fnv0MOM/Q8QcPfNRduCS/FUjUYR4mPxX8EzG/JwdeZxfny8GQH94fiDpgKRLLmJQ4QX87DPnNE4OZajIu06Mjfk4A84FDVXJSoHAC6wSK4qNC5reCIO+06HOTiipalDCy8n2XI0ixdkCxp4cjK3hTkxcCewutLS2RuEXNAbwLeJBpPUD7kMF4Cn49UtLm6yQoYFo4fvjgy5Rbbgk+0JGml7HMa4lIPUYKguJLUAMhjrftTdp/y25XsJ2rU9On7x4Bp1hKfkSxncvYTwGViLKAKue8HVsPK9lG2QRkWxcxbeQ3Vv43PsVAR3mfPuO6NjRk2xneYIh/PwSZf1enpMzU+WgY+0GC9YFaNaX9iGZ6y98do9v7w5Wr06MCkNjFLAUcNZ+MN2AZ8+6/fvw3r+o6RI0ZOg950IlR0Du4PNMNQoDKXRO53rkX3Lab13RGZ0qynv+TWLpTIpPb3AXnf+BP7IP73yx1XsrmQ=="
  init:
    enabled: true
    command:
      - "/bin/sh"
    args:
      - -c
      - >-
        npm run migration:run
  env:
    "DB_SYNCHRONIZE": "false"
    "DB_USERNAME": "scv-gateway"
    "DB_NAME": "scv-gateway"
    "DB_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "AE_MDW_URL": "https://mainnet.aeternity.io/mdw"
    "MQ_VERIFICATION_QUEUE": "verification_queue"
  image:
    repository: "aeternity/smart-contract-verifier"
    pullPolicy: "Always"
    tag: "1.3.0"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "scv-gateway.prd.service.aepps.com"
        paths:
          - path: "/"
