app:
  encValues:
    DB_PASSWORD: "AgANUDwF53q3K98SJJqaaxSwLOJXhTgtBJUcdF4J4CX31V9+zVYWt0FIy46IZZ3C/vLtrXzbv/Uv8LEW4jNvXr+4EAVHjmiokN8MbPBqJEDsHrncLE843pkJp8IpGz7I+msKHd6wwo5Wa5DZoSJh/TNCJQ0/S6zYpcbEP2PSwQFxYI2foW16xcFpxA2VHqUTcYqQ9zWPdK8rIrnk6nVHrAQCNcrJJ/eO6l0ov7PDLYURPRSah5MHTP+lVUPuraD1KopFFp5GHlSqOhjYFn2CdGU/cSp1ODpVBv0ArfdeROMDw/3x9pgf6uYgIO9+q5A0HUa73qZuqHgWlN+EGV7TxsjmxqjXcX8wy+WGEfXI9yC//iAxauVVUaM5zwwD55UXsjBxTqFWNXFMHcPu9ml6TT+PGChkAM0eJrg+wvDyEqDlo7oNL8kCCMS3IvaP3DW2hL6wmk/bh+DPiP+ZCxogbQ9E7O7tsXpjC6HH+vWfIXa+1Zrhe1ZL158SignrUlc7Z2Bwo5BOsKWVP4tP6ccYsLBpuNhKxa9oBkcpjWamS5og8tMPPRB1YgKE1r1Upik+TqwTL6tthSd5XoBVC4oL4ASxXa+A/SWWEzNaWPhB8YfwTIG3YPfn83mgjSQz8vfv0EFi8sKdkUMtinxsu+wUnXM+RkPqmieqKi5FnDN4E7+CtICK4TtMCpP8Cn7GnqM0KpwAA85dW0GTbiSU"
    MQ_PASSWORD: "AgCZuwFBSRx+qwjLlDk9tDkdh2WboAg/AhbziAWEg1esBVSPAPAM6jGV8il2PGxwVhP49gbUoaJZfBh3ap/8qSzIkAFCg8Us3x11CzJ2xxivZFJSHsp71OGJXAZ4pvpGypGZRbKOmJJmbLJxQIWh+nXTavufaslDSNo+pG5xuxKYYvpW+zpJG73QKcdXAp+c8dAXxnmUdBbu3ypwt+kXk8yvorUNM72aDD7x3GAfaqPD4UFKolG1neEOvQhf5W6MSiiHRXjrymuO/IQEB6uoARTJLN6NqbHXWhFb+9NRte1KzlYzRxcoIMxFbcQOLRHS9h9Q8Af9Ui3z131VEkqpZZIHAfet0jVgyvLWJoj2LiY68pwA58HhFdh9j8EEBdr8lXy2ZoITNP1VDno4LVHpc4yCoZXW+2iVQqz6N69JoKdyt/Cdd93tpgZC8JsSj6uCZcRFYNrZaChz12zaXhOeImfvKOCu5FjltsmA4W7ivBnGoz4/0/nweX/n7lHO+n6m9Tf95HytWc/kwZtepf3rTngpFjZmK4R9fzzYS5T4XO5egraH4tyw6JTziSNCdFTPwOUsJd9J4zpnb4NT+HBOW4ivew9GFRaeJXWIKOMgaaVEcyrVJxFGFZYAeXsH3u7Yx/qOqGbv6eIJk8Od8Ks/qjbWe+6rrH7MWMGkCC8/cUX2G6sDcd6fthLp3uUdLeLTeTn88QPt62r0hZFtOCSPWxXBIYoGAS01Hwv8RWmtBfYtIA=="
    WORKER_PUB_KEY: "AgBOmwx1z+8fmjWOtnS7TgvT01TPXmVgdngXB+twnv1t/Hqs9L3QwbM9vqAJg7Mj19mYNETM4UMUOS0g86Gi8X5BBEQxETPXyUap0hEVh5cruxH1Jbm5jUQhsijgMBW/ugOswffyrYaj+HbtyyTMMFl1WOU6EnaTe3qGltsaDfycHyZ2EsdI0lNWTy/odZ6zQs4jyyqL4/ygeRctEA1c5y7HrYFgsskWKNiuLQkhk1U9KPt++0EpHktMkvs8qP/d+ilYfK4iDGGKNMj/G+oEntfnj8VMSmLvJFhwJpXcaSlOAE9NXpcJtvghbE3X2kGqxNa2AFoaUl5DsxxaIPerpIyoVTAglTD4yp02B4uMoBKDFDaG+jTeC4BnvgN8Sw70IWv7r1F1sdfMig6teIGg8wEW39QjMho8iDGpF11vIRuWQDwm3/mTa2OnS4RhwVJeLDioYtGJ6TqOZOa/bdZ7JwCxaMt6V1ZkOMETLrDNbgboOO/nOEnilMFV9qAvOatIpXM/9Okje8VjyqsE5EhQAsctwLzPfBIhi+Gb/529IS8r8EQpG8XNKehC59aLBm8MSheoAreAMTIOrAyVX4OL6HAGz4ormuTeiR/z875kVOJMD6LSG4Ajl8cpIB4UptRWJTVTOH6fkW22K14NZFfPAIKrbyDqD80vT9UK+cI3q/jho3wzu/+WAPZ92W1qcKtM7R+Bos8HbUArFKBpGkgHlJdVmSe/c6r41G2UiEwO0cZHR4xKFVXFbBn/RJNI3ogXJOMYXhdY/CQSUbzhU4rLSEkTB5r/QTgMUQaaAuKRNLzzpx8OoqkJmU58QWuDEgviiRlvI3L1REdT+tHFWG8v1lJTTnHEa6n28JJoMi/S0bhgC7kN6ZMFAFnvo0wIdyBzsIZQe9QFlVWmWSENTdgOltagNNiVaKUK34GGgK8/P9EOeAymnLk1gT2x4PWABmoKnUvfCJIw2+V9Chw9k8w85+ymvax+YU0stMua3vU4Qb8UVvcpdsrgwMQRBKjzz46daBxD6AZZVuW87R6SKsc2hAlUK4XX2B7qHhpAN/6RmXmk"
  init:
    enabled: true
    command:
      - "/bin/sh"
    args:
      - -c
      - >-
        npm run migration:run
  env:
    "DB_SYNCHRONIZE": "false"
    "DB_USERNAME": "scv-gateway"
    "DB_NAME": "scv-gateway"
    "DB_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "AE_MDW_URL": "https://mainnet.aeternity.io/mdw"
    "MQ_VERIFICATION_QUEUE": "verification_queue"
  image:
    repository: "aeternity/smart-contract-verifier"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "scv-gateway.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "a823088"}
