app:
  encValues:
    DB_PASSWORD: "AgB+4Pk1fSSfAr0hoAHgPBEJ/WCKW6UF3DeeRJvezWrCaCOvItI6gUMMVvCnzHqa/RxYvGpTGwXOjzpr1XV6NdhQRCfYAay5zBKnV/suYCEe1NXVICo/vnmIXgZ2Xtac+B76FDIe4Eb49N9HFAUZQP7WsDmogECrPK9EsOxuhT0XQ4Zb0pZHXHcEk9nMO4L4r5pallU3Ie9Q2/hgqUzhClw902sivYML2V1oDhl56FgG2k6cB052TrBCe/qoYcGsO9ho1Qq1HMsYYiLOcLwTETd92pnAnEy1WsIeaSsAuidI7Dkr/gQUwj7vb5hQXq58/qlWRmurclKxlceD6psFk+oCMGBNJZJSuhKkp26E/dr3K3Sf04XEai4BVdoF3OxqCdxeTjmoJQ8D0LJY68jFy+btkbZxxwIkwXkXl759weI9O8mvz5pxulV8I7fo/ZxjHUr5y5Pa15acLYXKiA78Qr4r7qx8YBnmED3t6oIRCSpmHCekkQGkdzK/AQY7CM9uRkcnXUVrIP7yMbXCG9e4tGTiPtD/HpGCNL5V7SmZl3np3A1HuRIeLS1Cmk0iFlO7RQUnPNcXxS2yffWsNm6+upA1EqpUONCJez9+jRn8SPAjM2xzKT1t8aXTpNboYPC65g2oZVChtGDoKoCgChR8rzbzV6dWAfUpjlGglSemicyhO97BaL30q76sRw05HSfEVvo9WzG6YA/Wj9qvGw=="
    MQ_PASSWORD: "AgBXLrOKycdsDV5rlqz7E2UsX9GnPSmBwt/NbbXRzjyFQ4HoSeguMNUYYVemUolT8DIymYdgoYpsko28/SeHQLnaXU2KXA+wyJqeUrI6tQsfwAfmPcuAwDg7Jbe3Ii3rNuoS9mm03m09rNNwu5v3UpcXtcllDY8ZCZVBMpEDtm2ttonbsahDC6lk3Da6dRa7XkVtsFKsxnibYk2/xSTp0xk9XL+lbAPHo3/Jn0XcQhxZurP619eGBVPFABe6fIJRDT4QC07qar7LLmEfF3J+bq09lMQDE618mejzTGAUgctq4P5KdUvzmOlUfqnyXL0BblPYe5Hk5O8h4lMCPfQyAqZ+b9b6K4ZurZxzQnQPwd+tw5aYJHibjvxGobJSuXf36c5WQjFYSXQcdYzTn7CHPJG/pEMJvUhLkoUZebXLDT3LUz7GgYV0W2lB/nqsHLPwp19gYb9mHwN1UIZ9mwZhoDKVGLLgfeRifOAFcA66dzw7EhXy9M1XnUMAfHGPV5VElUXnN4jsrDvozg0ih5Wds3k8OEqPc03vfxdRaQqoMorVYQigV8A5KHDnAhfQSthmtLdyWkQjtbK2RqiNg7vEYJm8/MSOsEB+btYZtnfW9ey1rIZi9yElnaSYE2V6lQJeQB/cBANUtbjW+74/xb3tbIa5qur1QMtbRg6lLD4QmPc9JbT429Z2lnHRxJjPHajkwCVa/8RW9vQlRCYXlQ=="
    WORKER_PUB_KEY: "AgDAHz1v4eD18KGn8f8DWF5yy4FZRI5NIq8TqGtLDqTbucvTQsoFo5CL+YzItuITVVMRpSl93imlgfDokTYwfglm5ghW8U6cyi1+ZnbRdEbw0t+DeQkMzp7TCYjsRfHKkfibZI0wHXj4KC6GSQFBvkH1y1wn+nmr7ZmV8EFwl0rHyMdrNa4e70LJBm5qVxH1Z0H3mGBmxMbOgFRqveIaaJ2HBie1FZpfQbEnVmzL8KNTSjHG572A/iFDdZHPDU/+bqrQtzmmQZWNlLKZHUumCL7tM54bDMvPV8tzaEbvhqqikNObCsbolcH3uWaf8kl/6X+WgCJU2Sr18sJowh6ua24Gmj33fKbmxowvXqa2Jj8nTJpDNDuGamVllzf1Gjja//Fc+zAi+OsIWy6jE0V2wfjjJdPbWsyrsU3mJWm3WaM1sUqGmUe9xP9boNLZOFi/k8+EyFzjV+fuiNawI9fwCijzniK+NyQs3Ym2A6i4pPtN0vzTG5pdAq5kaH5sPl/k3Q7AfF3cG0CprI1bU++axdNebYqMxltM9F5b0HehdZ0Lz6I64Lx2s/vladaGtq7EOQHhLp5StJe1Fnv0MOM/Q8QcPfNRduCS/FUjUYR4mPxX8EzG/JwdeZxfny8GQH94fiDpgKRLLmJQ4QX87DPnNE4OZajIu06Mjfk4A84FDVXJSoHAC6wSK4qNC5reCIO+06HOTiipalDCy8n2XI0ixdkCxp4cjK3hTkxcCewutLS2RuEXNAbwLeJBpPUD7kMF4Cn49UtLm6yQoYFo4fvjgy5Rbbgk+0JGml7HMa4lIPUYKguJLUAMhjrftTdp/y25XsJ2rU9On7x4Bp1hKfkSxncvYTwGViLKAKue8HVsPK9lG2QRkWxcxbeQ3Vv43PsVAR3mfPuO6NjRk2xneYIh/PwSZf1enpMzU+WgY+0GC9YFaNaX9iGZ6y98do9v7w5Wr06MCkNjFLAUcNZ+MN2AZ8+6/fvw3r+o6RI0ZOg950IlR0Du4PNMNQoDKXRO53rkX3Lab13RGZ0qynv+TWLpTIpPb3AXnf+BP7IP73yx1XsrmQ=="
  init:
    enabled: true
    command:
      - "/bin/sh"
    args:
      - -c
      - >-
        npm run migration:run
  env:
    "DB_SYNCHRONIZE": "false"
    "DB_USERNAME": "scv-gateway"
    "DB_NAME": "scv-gateway"
    "DB_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "AE_MDW_URL": "https://mainnet.aeternity.io/mdw"
    "MQ_VERIFICATION_QUEUE": "verification_queue"
  image:
    repository: "aeternity/smart-contract-verifier"
    pullPolicy: "Always"
    tag: "1.1.1"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "scv-gateway.prd.service.aepps.com"
        paths:
          - path: "/"
