app:
  image:
    repository: "aeternitybot/state-channel-demo-frontend"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "state-channel-demo.prd.service.aepps.com"
        paths:
          - path: "/"
            version: "latest"
      - host: "statechannel.aepps.com"
        paths:
          - path: "/"
            version: "latest"
    tls:
      - hosts:
          - "statechannel.aepps.com"
        secretName: state-channel-demo-frontend-cert
  versions:
    - {version: "latest", gitSha: "d9f0052"}
