app:
  ingress:
    hosts:
      - host: "state-channel-demo.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-263-state-channel-demo-frontend.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-263"
      - host: "pr-269-state-channel-demo-frontend.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-269"
  versions:
    - version: "pr-263"
    - version: "pr-269"
