app:
  ingress:
    hosts:
      - host: "state-channel-demo.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-274-state-channel-demo-frontend.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-274"
      - host: "pr-278-state-channel-demo-frontend.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-278"
      - host: "pr-279-state-channel-demo-frontend.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-279"
  versions:
    - version: "pr-274"
      gitSha: "null"
    - version: "pr-278"
      gitSha: "c924587"
    - {version: "pr-279", gitSha: "07b92f6"}
