app:
  image:
    tag: "latest"
    repository: "aeternitybot/state-channel-demo-frontend"
    pullPolicy: "Always"
  ingress:
    enabled: "true"
    hosts:
      - host: "state-channel-demo.prd.service.aepps.com"
        paths:
          - path: "/"
      - host: "statechannel.aepps.com"
        paths:
          - path: "/"
        version: "latest"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  versions:
    - {version: "latest", gitSha: "1c90e48"}
