app:
  ingress:
    hosts:
      - host: "state-channel-demo.dev.service.aepps.com"
        paths:
          - path: "/"
      - host: "develop-state-channel-demo.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "059fdd0"}
