app:
  service:
    port: "80"
  ingress:
    hosts:
      - host: "sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "sha-44bda8c"
      - host: "pr-168-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-168"
      - host: "pr-169-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-169"
  versions:
    - version: "pr-168"
      gitSha: "c0e980bd"
    - version: "pr-169"
      gitSha: "652789fb"
    - {version: "sha-44bda8c", gitSha: "44bda8c"}
