app:
  service:
    port: "80"
  ingress:
    hosts:
      - host: "sol.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-52-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-52"
      - host: "pr-52-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-52"
      - host: "pr-52-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-52"
      - host: "pr-52-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-52"
      - host: "pr-52-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-52"
      - host: "pr-164-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-164"
      - host: "pr-164-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-164"
      - host: "pr-164-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-164"
  versions:
    - version: "pr-164"
      gitSha: "342e2c32"
    - version: "pr-164"
