app:
  service:
    port: "80"
  ingress:
    hosts:
      - host: "sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "main"
      - host: "pr-168-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-168"
      - host: "pr-169-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-169"
      - host: "main-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "main"
      - host: "main-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "main"
      - host: "186-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "186"
      - host: "pr-186-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-186"
      - host: "pr-186-sol.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-186"
  versions:
    - version: "pr-168"
      gitSha: "c0e980bd"
    - version: "pr-169"
      gitSha: "652789fb"
    - version: "main"
      gitSha: "04859942"
    - version: "186"
      gitSha: "45d54c35"
    - {version: "pr-186", gitSha: "65dbc136"}
