app:
  encValues:
    DB_PASSWORD: "AgBhEoiAzw+HAz/oynRa+3bDZ0MUjURcybaZyJbq1EaK8Xn9iMjAH2LK3RJZqexVzt86S+gEsw8QexH8DbYsjg6Sne/lJ8hSCj7SIfTmB1VMWN0aCMMImbszkTBs+Yy5jHeeSbU+Aq5bYXa+iBiEjgFcd/+m50cvDnwgxmLJYXvnueb9f0uFSsvoIL19/rurwDqvrgWHJw6gI7McuRbxf4o93urvbQohR0peLyJiKfaOI4yJXgUa9oUX9+8X2DFdT8QMzSZt/bohlgwMcnIQTAqRfxBiVQec3gyTS9CP1ULEF1W14Av6azSXF4H5MzeGNy6l4RBX0NmAupBCDil+Imbpheo0yxP//lTdhg1ZmHz6AvodK3Mei0pjkmETouu35/ZGKOvN9mrWyUtGWaXiVW5riomfE5D8+toHXmCvdJCruUpK9wbvKpQNiFFdk5+z5w1cxMzy8KdzygnUe8T1hBuiDqlHgQP2Z6DmpXkZ7VFfaFunW/DMjiHy2HhAeZ4YWTrgNWXnlGxsWdoOZyp2E7kRfd6GQoxQZ/VLNZ1IM4xshpAz9F3JsAQXGXkTue+1MTd2kKAkCzuXmZyUbJVyuZaClVoer5KWPZwUGeeneAXE/Dugtm0zIlpfSk2NhxxLwEZij0mJr077eNd6svVurHgvgdzTb2p/3axqk0ScxENvNfnGaEIA85r1+UoTgL/6sJU/oI98f+0m8hBh9g=="
    MQ_PASSWORD: "AgAXFMwH7oT1dHpcWnZbPdcGtQPqgv521KML1Di4nvTC9CRu+ud0Z1N8iFVQb/WWbGh9ribAH7kzpcCQoCivbQCb8fxVIPBRAoULm7QPJ7R3F4yD2qF9KIdZk517IX9E1db76iRyx/8p9DDcfcZwmMbErO1Fba3H3VfScKPwG6XwLA0hqZRW1iN1g5T5P1TZ9FP8X4RkPfD4XNtK8ftIlCm7WNg29KRsap7kxmKMdUiPZXcKQP5m6nGY4yCZppxmLkBKuJNiTd0Zx5LfFEZYnzeH2YIy83NmqNqDRyumvAealmG9giW5oF0mlFM4JtB2nMDhAUBMjZ5AAqczG365FmF3KqFKu2UxvTjplb/Qq8L3pjFhs5vjneNGyl8dW/FtOiF/QYhpfqcjfwDL3XTgbtVbFnRJtbfEILQNVnPRHR60KQJGhC569gAymaiHtBKqqAjzvI0TkxQpcbK8OknJ6s3fQbn8kQJxV3HM2OOS2oBAVUfWk6QO/54Bu68snGsWEKJm8H91lav6pVnPDvn9NWcrJhGfZZtIP78teZLrET8P4wV2sjLcEFb+/entFGEglk7kOAe7gwsQ1GkdflhljCRHpOEC0G0FgJE5g4O7fkJMjBBaEGmlLO0/PQapcfzfM2khsos+DDMlD7vqRKsTdQRPNNFGXLraOMBFJNeLhlT03aHQXCAMnVvSK8pAsV72a3BpMAiyp/8yVf+csA=="
    WORKER_PUB_KEY: "AgDGBodgexPhfdTr9td5zhBaAmOXI/rZ5g7/1zEshovZh6zyGwsr7f78qZsU1TTl+7oO9zPr8I3N5yPCZ0j02xSknyvUYgFVkjhN9NU+bNC9d4C/zXhB1ZjCN6WFhoWED2GCb9mL/421A0UDQNqfE8K6weH8+iNlJQjeqkMXJQOfWI5tcER+D9ZOfzmTA7pBMNnrvWMlwu7JYXfN6oOYpB5AT+37oseNv0tgvhaGPPNAjeVe/GRM4sGibJ45zxIZ3kLmn14LKg1EwjNdbrj5ws7mIRZyu5508yM311cA4iXajA4mBIXvDIOHnC25Bw09je2Nw6UgF45ocCy0wBWE80kkFOUjbdmNODFMNC5iMYJ30G5NDwR4kb7f+2g4ILRyOUKHHSq3QqvNXRdzNbUn2d0M8b+OR0iChMtb4WjlLN+G9y/w305/YmRUAsEhEZ7Qv7atLVVc9fxqCewmrZkx7HYhn5d/y2xKX2jDgl4uZRmyhZpqSUKajC3vZKqL09woK47V81H6/UPRLvpp0Ielo/Z5q1ltYyRDRJXAbVMIhyThZYE9xOvVySnySZHZM8s5WEaCe8vtLe2Zo0MsGGD6NEZyB67dz4sLMFY3iGgwURZo85qclItgN6jr5Cj3e7oSEA1KFHnH4yiZ+VKoWNftEtmxzuD0LxRs4bIWTdbp/kpsqOAYavZQcPQaGaFt2aev8ZZzFqOw9X0BdkIYIgyrJGmdHPk15HCc+nfYWWpwH6rQt76nXTYcYyzOHB71x5SP6SOBPIr7CGxp4c9Bb5xxPkZnBMI1DPNyGWUk5GKWaRudORmgQOQXOXfWtnbZ2L8gkfmyTB8TWoF5lGnnPJYhfSSbVjjNlk+gfj2OS7l1rwNS1/ubbB1wISrA83zlIxYmn/c7fSmlIPTyr4xVE8kCvsX7xFdLWFvfSOXOYJHB8SNx1HLktgzxGGoksczRdMyMV3AokeqIuWE22gZ5WjJI/1b/mKjCc1Jf3XxUTw3x9LEyVkYAYAAssyVR0QGXtZTp0cuLj4HkLpRMkf0KmInJVZEdOtDu/U51QGdo7bSX1HExww=="
  init:
    enabled: true
    command:
      - "/bin/sh"
    args:
      - -c
      - >-
        npm run migration:run
  env:
    "DB_SYNCHRONIZE": "false"
    "DB_USERNAME": "scv-gateway-testnet"
    "DB_NAME": "scv-gateway-testnet"
    "DB_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-prd"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "AE_MDW_URL": "https://mainnet.aeternity.io/mdw"
    "MQ_VERIFICATION_QUEUE": "verification_queue_testnet"
  image:
    repository: "aeternity/smart-contract-verifier"
    pullPolicy: "Always"
    tag: "1.3.0"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "scv-gateway-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
