app:
  encValues:
    DB_PASSWORD: "AgBC9RYre2phweL/nbuxZg/dxJJH3tU7o0pOottusAVRm7woSguEJohfyqoZ1lLy2+NPjGlOrc93V8WSgO41mHLj74enADw7VlRkHVpArf3eZM6+fDe5FUqWHvIEmnodmazJ9ZQArPxAFly8jvBdV8oeJtDHrsC4X/nYe0pCtXUoR47LDEkDoUleRRmEjr0D3jV5ulGdoqpewcEgimbio/Cq8JlaLEtsYNOMI9GRLfwqWDMT/Hcrz1YjiQhp2heTXaWc15umrLPQbaWgeDyKCB8IXizjMi/K5Uw+c4Q5tcKhHS5vobcCRuruKmyiDZUwYkWxAm7VCqvhyVJjP61NTd3t0n2+TC5YAd4lZFqiZIjENB7MBEmeHJ28mDBpw9h3Ja3iF2xF/2Sa5cRMLiSrehW94Oma1SJS/FNphIOwVf3DNfzcM53rg/4D+roq9VRJAuJXVAmIcKkPi2wuujSd09l8EHZ42MFfrh+VMvawwcO+AEhtwg1cOgAYbIMIBXRUNOfqD6qPAOsAoAXq49Lwr5UPrLTOd0nvX+5J2t216DP8tey02Vn5pDMYKtBrxfRBVcZCqgLBT7nUougsGY6xy+JEdbHhkeWsB6ElfPWJHqK9902LD6TLzOYoi6V6EwoFCL0odAssFbqGHAKNcYQg3d1dCJJNAsuN3/p0tRoxNWAjSf7WOecO07ik7V9nei8I2ukQpxEF26f45+XE"
    MQ_PASSWORD: "AgBOpuOQk8hMOWqKKWj7EGjeQCGp3tZ8hNPo/my5szPji7oSe5zolxgyE5n0RJwMj+Kn5JRoH8qAw42+lpBnJTMHPRBp0skUqxKiLbLcXBzeYr6kJpTH8badh7Wzj9Nvyc2+NUwjpdGLnwKMw7xwaBpNMmc9+JfUb7Mid5U6Z+vGiaCqObxsT6NGFcxIybPvxO0/D/xU7fRKl+mmUZLtm0jK6p5miQy1fCzXekdDSqmUzCu6yUsPl1in7yYz2jRb5/M1KnLwZi+Tp9YjkjmWtXmWwFZgJdWaOBfOR8hB8m4rt8h3FdLvvEzUeTpb5lmUhgNXow1HtVzQVlKtluLTHIEBVZ4/4H/IMjWTTO/SOCK4y2LHQs+8aT0RVgbRViI+TywKsLaIZ1mZxDOgm2FtKP/wNTORKOuXTSmUWuIOSXWAHSiXEiZgOQdPNaMoE7htws9DsZV/CWu0YSxemMWraKz3EGVj47rdIF2zBghMFcFquaIrIEHjZ3kxY5SRQ4z5CYToV+eNuQpgIxAwIe4YhFJlPTKJj8VpZPtk/alfbGYFQ2cm8JuuFAbBel96odTKS/FNBIk9Gxzrr/2PFZUtEcK1Qcu+oWVr6WBTKa+XFca/i3njxXmQY/T0UghHVPFWqg+AoRAH1lWNqyzq1uIMXcJUXGZtRiX3uEBV3nGfzcT03rEazCzyCyvfZXy7KHGk2iIhnGiodpHHwrA5UImfE4oGwy9wPbe4ePqOr6uEg5buEA=="
    WORKER_PUB_KEY: "AgB0ctzh5XNQLuWm7NkxQIrxokP5Zvq2QCjkY7zpBSqcJPoY7eyUhaPVnMpEXAcc3RcY2xRgn2fWFLzBvEJj8HA6VJGfQXd1LOsNCtXQSrPeIelUQzwGIc9v932YuZWOxEVTfkC685h9ul8FidNMRmTZbb6tjKwHEL/Go34t8Pnu1J8L9/ShzwZUQduead+6N5rl3qOMz3AmmVpctgV9+oB31qRreHhcJbf9hOssuoSFes6O+A/Rnnq3JWIF89XJ8YVzBsDq+6RrhPRz1lvNh4HEYelmf6uOqvyDGWcphQEqHtEp+Sgcb7Fw01EcBuYU+0xqKDCLx/fO1feATbVfXJp7pYN/GkLLvweLTH3Tn5fAAQySh6rp3UrVjXZXjgiJCVMnaaLoqAULAV5oshJxJAdjOasu5Oih3Ey795UCW5+eMXUyzgFRJxsK5fAjQ3elzsKtVJ0xKkkEBe9m/oDE06RB1k14IPDUMPi/1z7kIc+ZQkg3SosPy8Scl+CFaSQGmL3rGWdr3muDFHUA9/hI6HZAnm7eGNWzQPh32xujlfbDf1BwAGbYuge8rQhOWVsd7w1bQgcVaxT6EB2OHS5MpBezXOp8SUbItHrZDsL5DwMzAr6zcXisk26ldFHwUmxRc9VMlDQvRnvhr2yBajCuEaiEuaaSO8zTKfXmQEIXTv8OPDAY3U9CLdxKZ28LZ2F8kWo0HBBTn86rGiuDsE43vYpUCoISoL8XpYBL9v4UpIv3uK9w+Qr19Lo93Awl5VlF3zSOnFZIT4UpLKX60kB5e96cJEShGR5OBuT3dJHDANM7hUOPNe2FWriu4ZjGVpfbcovkREnbiRYRNhlPMTxn6jAZA10dUwICtJVhdJ3VleT4C3d0q3H2zSNqCEKR4yBP6LSg17qhzf8Vh9BqwCDY0jEExsEp8g3EfyR/cTzyayLaFJCQ3QRnJSw3xRpQ0nS1cuIUY1XdDCoa1mAIBRPwMH3xdRZi0y1bBHumFIWTNQnF6kJyCqfSjmzQfj8zrt4+X1gFwxVuqrCMzTlQlo/Q4YijZeQCYeQuPaUjxQmB4Kzu"
  init:
    enabled: true
    command:
      - "/bin/sh"
    args:
      - -c
      - >-
        npm run migration:run
  env:
    "DB_SYNCHRONIZE": "false"
    "DB_USERNAME": "scv-gateway-testnet"
    "DB_NAME": "scv-gateway-testnet"
    "DB_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "AE_MDW_URL": "https://testnet.aeternity.io/mdw"
    "MQ_VERIFICATION_QUEUE": "verification_queue_testnet"
  image:
    repository: "aeternity/smart-contract-verifier"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "scv-gateway-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "f86c2ac"}
