app:
  encValues:
    DB_PASSWORD: "AgCFz3OsgeTGK/FQ23NlfW4ujsUWo3bsfukB9fvfPiCgCuaWDQxePJNmkakaf+73xohXuyFAX9a7HAkQieTVMJSbxX1HhvvE6Adc1ihwtN88Qw6Z1nuUi068ff3MHmukS/CS6zM3CDQfQeXXK6k25KFItqk2tN+UHed+VQ9FYdj8wnr+gbMpUAHWXpv2kvrdI6SI8YhxElXAzTV3zdQ1btTByHJAGlpcXm7bEJMYljW8U+TCoEK0/salLEjaaFbEZmOdyVaPpx5sGHu20/ytkiPUGfJPFlR9INcwhZoY0IgwrTTX/6vsmWJwZKKtyqzb4xcHOwkFYbbD9A88LVTxlHI5dQMdNeCRZhigKxLeG4EIQMlNmFuK31yTTY7Q2fUvYd8nJlZ4vXK62RQ4CyTvS0sMMwEpyVjdG7FSiV5kwCnLWDfuTYXH1I7UOakAF02UpJB0Ko8LrifztRq64rPiwM0PVSjOsjbZs76mzPvC5QKwRyeMPuNFJxfiv3DWdTu2TjTnKrDbwpWtqpdOWl+Mcq6ST3CiQKXfBlCTyjh9+KvzRBmNjaZQhbAejWZbIhFaKUPWyoJ8zbz7l3PCVMURRcGEBqKe8a3Nv0WZxL7GkDL4NzVr8YbT/rtJt0sal94Fv5k9D6cdeihNt7Qpuuho+JBqxZjkripXEAL+dSqY8aeZewg8aBs8JDlvbSNe3SAGBqsgVrbt+l4o8hTx"
    MQ_PASSWORD: "AgBOpuOQk8hMOWqKKWj7EGjeQCGp3tZ8hNPo/my5szPji7oSe5zolxgyE5n0RJwMj+Kn5JRoH8qAw42+lpBnJTMHPRBp0skUqxKiLbLcXBzeYr6kJpTH8badh7Wzj9Nvyc2+NUwjpdGLnwKMw7xwaBpNMmc9+JfUb7Mid5U6Z+vGiaCqObxsT6NGFcxIybPvxO0/D/xU7fRKl+mmUZLtm0jK6p5miQy1fCzXekdDSqmUzCu6yUsPl1in7yYz2jRb5/M1KnLwZi+Tp9YjkjmWtXmWwFZgJdWaOBfOR8hB8m4rt8h3FdLvvEzUeTpb5lmUhgNXow1HtVzQVlKtluLTHIEBVZ4/4H/IMjWTTO/SOCK4y2LHQs+8aT0RVgbRViI+TywKsLaIZ1mZxDOgm2FtKP/wNTORKOuXTSmUWuIOSXWAHSiXEiZgOQdPNaMoE7htws9DsZV/CWu0YSxemMWraKz3EGVj47rdIF2zBghMFcFquaIrIEHjZ3kxY5SRQ4z5CYToV+eNuQpgIxAwIe4YhFJlPTKJj8VpZPtk/alfbGYFQ2cm8JuuFAbBel96odTKS/FNBIk9Gxzrr/2PFZUtEcK1Qcu+oWVr6WBTKa+XFca/i3njxXmQY/T0UghHVPFWqg+AoRAH1lWNqyzq1uIMXcJUXGZtRiX3uEBV3nGfzcT03rEazCzyCyvfZXy7KHGk2iIhnGiodpHHwrA5UImfE4oGwy9wPbe4ePqOr6uEg5buEA=="
    WORKER_PUB_KEY: ""
  init:
    enabled: true
    command:
      - "/bin/sh"
    args:
      - -c
      - >-
        npm run migration:run
  env:
    "DB_SYNCHRONIZE": "false"
    "DB_USERNAME": "scv-gateway-testnet"
    "DB_NAME": "scv-gateway-testnet"
    "DB_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "DB_PORT": "5432"
    "MQ_HOST": "rabbitmq-headless.rabbitmq.svc.superhero-dev"
    "MQ_PORT": "5672"
    "MQ_USERNAME": "admin"
    "AE_MDW_URL": "https://testnet.aeternity.io/mdw" #check that
  image:
    repository: "aeternity/smart-contract-verifier"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  resources:
    limits:
      memory: 450Mi
      cpu: 150m
    requests:
      memory: 300Mi
      cpu: 100m
  serviceMonitor:
    enabled: false
  service:
    port: 3000
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "scv-gateway-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "f86c2ac"}
