encValues:
  GRAFFITI_S3_SECRET: "AgAntN+MRpufVpj2w746tpNk9x4oe67GtKGQ5af4Nl45dhn7DGgkUhURgcMz3hL4/3Mo8AIU0oVlRavLvwy77c7f68t6so3fCbw4By/BTCuyhphYGsMzdAYWR61n3m+smOwkKAf05b6dTtRu7+qgk9/lkf9PwcV180tAcE30pIhUObAOXa0YpJbkZoWSs1RXX4VzNg2CtmtJk8Vr9i+SHsW1NSgF2Iz/doBeWT2YoIKn1PJGmWAkZm1GZOOyKpKXmW0wvUnVyoSXuWIsHsvb3yrGaYzdz9OtVLItxgWvX9g7vtcK0ODUUGsXKxl21+doAt1aaEDFdhmZZ9aebG5xZOGErFSS/A/r6E6Rbc4vYR8Lln1ROylMHVhw1ZJpZ2fEmGbbqXWIkMLhS0Abl3p2YWXT9/GzkRAkHuA46F6I7n3oAZWA9k9KYuRR9+LutGLv34hvb3Na++60sKN7w+ETp/swaKJii6jzmWEeyi8z2sw/xh99QhK+FcLOT9A3usT86RzDLlOebvUNriUlgqp5gHECWmi75hwWMZnm5pQ5E1kilnOmsbwf5CUGSNLNvPHRnBEVEpnOBfea6nfHDnBcSlHGGG5r49ML/mb3+Xwgme4yvVg/NQ8mfMSwO3PNIP7TS72LgZTBEY17vwqTFQfVe4qB+Typy2FEpxw94Q04HvqSZ/ziVPoIL4NuxOKFze0CymiuAlbibRNE8iu0M0rV1LTHou4bYq1uJIjy0JqtTwINLSDRUWGO7Lz7"
  GRAFFITI_S3_KEY: "AgBI64FRJXNhlJ3ldj+dV97FxHQLRySSlfTccuUli2DB6KPuTKtzFDTAO/5r2b5vk7LX4iubSBMPnaFeIyL724GGo2gfCnT70uYdF+WGleiv6c22TsjvKiRRCQc4CA+beQkZQMiHbhh2yrONOWlM7K/hOgCogXzOQLsz33cdUa5+VVNIZ8+KwMKqKZlqidTzLuZDZmB/7bZuESUhcLqkdEqDgJDQSGqLlKaqGW9t/3MNOpjosCGz6d5MDuIBTM2xPHHS5qxcpMXpbc1klUg4TCzjwIEbsVMc7wVd+QrV39Q1otntXGtPH7HdNuy0oILNnEhedJyLidhF0aUcuYqLmYe0Fsr7c/oIV66W2aiQRRXE3RDXBlW3qNfyKaFMJkCN5ORFatshMv2T/CPTQIlUBQUxsYW5KSRZ33j3rg+x/E63qtrWXBPihUk/9u0A0rS+WOvLoKPTm7ceKSu5dUxdASHdiMmVbsRnvUe2OhOogsA/2wRi7XaQZNiwgcVttR5QZW1d1f8RrSF0iCISJXt2NBIkcgedYveBwTTvR6hZeIAbIAkinkL+5Vpvr2BMh2uGlIlRzNVlqq+QbKiCDMvnmGL9DK0OXmMtG2HIezmSWs5+jlyXLe/PqHHbll6LKIiUrFShWXgBjI0rLZjND8Fd5gUNlnFmVnJveVqm2KDC4XCvp7ZXV36LpWkhUbumB0yJLKVSKmbNODzm6i507mRkx90Z/yx1ew=="
app:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "graffiti-server-mainnet.stg.service.aepps.com"
        paths:
          - path: "/"
    
  strategyType: "Recreate"

  image:
    repository: aeternitybot/graffiti-server
    tag: "latest"
    pullPolicy: "Always"

  resources:
    limits:
      memory: 288Mi
    requests:
      cpu: 200m
      memory: 288Mi

  service:
    port: 3000

  probes:
    liveness:
      enabled: false
      config:
        httpGet:
          path: /health/testFiles
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      enabled: false
      config:
        httpGet:
          path: /health/testFiles
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  env:
    "S3_REGION": "eu-central-1"
    "NODE_URL": "https://mainnet.aeternity.io"
    "CONTRACT_ADDRESS": "ct_ftU4u1wEsiWd6YN4AAekEArJmLds4K8AB2k4UXKxn32Yrf5n5"
    "PATH_IDENTIFIER": "/"
    "COMPILER_URL": "https://compiler.aeternity.io"
    "IPFS_URL": "http://ipfs.stg.service.aepps.com:5001"
    "S3_BUCKET": "aeternity-superhero-graffiti-stg"
  serviceMonitor:
    enabled: false
