app:
  ingress:
    hosts:
      - host: "dex.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-508-dex-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-508"
      - host: "pr-511-dex-ui.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-511"
  versions:
    - version: "pr-508"
    - version: "pr-511"
