app:
  image:
    tag: "v1.18.1"
    pullPolicy: "Always"
  ingress:
    enabled: "true"
    hosts:
      - host: "dex.prd.service.aepps.com"
        paths:
          - path: "/"
  versions:
    - {version: "main", gitSha: "6895935"}
