app:
  image:
    tag: "v1.18.1"
    pullPolicy: "Always"
  ingress:
    enabled: "true"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "dex.prd.service.aepps.com"
        paths:
          - path: "/"
      - host: "aepp.dex.superhero.com"
        paths:
          - path: "/"
    tls:
      - hosts:
          - "aepp.dex.superhero.com"
        secretName: dex-ui-cert
    env:
      "VUE_APP_MAINNET_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.service.aepps.com/"
      "VUE_APP_TESTNET_DEX_BACKEND_URL": "https://dex-backend-testnet.prd.service.aepps.com/"
  versions:
    - {version: "main", gitSha: "6895935"}
