app:
  service:
    port: 8080
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgCC7hOUJNAuA/of7RqrffGT5EfA7weEPyzjFP3mIhC6VJ5MARA2PYkrCMD5qDKzfrgsXHJwhOeXkXJHhJJjp2WDw8WgtksUlaXKJWN9MXUAyA490xJs4AsJlX5ALMLc8FJWQ5Ety7hjCUgvfMdrWaacyRVqnDHfxCNfXFqQWB3OeI+uJZ3ddw2hKM8z8wtwD+gVJUcH+TRLgLrqYMh1vRgK0MAU2PH/25RWlIefM+SsGl4nvP0ae1MdNCkibjYZqfcXyCXtQqyp+zba2qF+hqvHvJUfF4bmm3pH9hEHZtLn2zD5u8dPVTA/2pDrEyns/ueGVolW1PXJu7EWd+bIT/K/RZyAk8mezq7brmduiHYQ94WzNcEaBsYTcCB9ZCLJMePLKxB0rH13TnNC7FeMtFM4aftcExbHpafTHJ0LXHTlkh6OeW2FfMQbo+P8Oj4aQlFlstbiA+wD9xJOQ4Q4J8WnJPjlHWqw+MrTnWbuXzh2aLXTsT/fI8I3y0b23YH71i/OVMgRe6uvPA6aUb78lq180nV+ut+YusVawXug0nUeHBGR/kpbKFaGJsY+kt5QMSH+FyFiWagbKWTT0eaxZJJmmablLwkwFIwwobrwu+QWUZsU8XF4HK/60dwI/c6YipIq5QvtkD6rW79bdhP3z+67FNbX10qyHgQ4WNAktMctcOoI86UrXYblNJYB11drj5e4fPXyyshOLWwgdgv2yNKh5uX4Fc0mRRRqyrLffyUpQmmh9S3ZWX065+8PQ7eptAY1CFwr2sMYPEGQ4oZ97Mvq"
  ingress:
    hosts:
      - host: "aescan.prd.service.aepps.com"
        paths:
          - path: "/"
      - host: "aescan.io"
        paths:
          - path: "/"
      - host: "www.aescan.io"
        paths:
          - path: "/"
  resources:
    limits:
      memory: 4000Mi
    requests:
      memory: 4000Mi
  image:
    tag: 0.28.2
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.io"
    "NUXT_PUBLIC_SENTRY_DSN": "https://ca073f3a8941437ea8726ac0b5617841@sentry.dev.service.aepps.com/3"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw/v3"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io/v3"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://testnet.aescan.io"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
    "NUXT_PUBLIC_PLAUSIBLE_DOMAIN": "aescan.io"
    "NUXT_PUBLIC_PLAUSIBLE_API_HOST": "https://plausible.prd.service.aepps.com"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW;ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "NUXT_PUBLIC_NETWORK_ID": "ae_mainnet"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway.prd.service.aepps.com"
    "NUXT_PUBLIC_ENABLE_NODES": "true"
    "NUXT_PUBLIC_ENABLE_MARKET_STATS": "true"
    "NUXT_PUBLIC_ENABLE_MINING": "true"
