app:
  ingress:
    hosts:
      - host: "aescan.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-876-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-876"
      - host: "pr-881-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-881"
      - host: "pr-885-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-885"
      - host: "pr-887-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-887"
      - host: "pr-894-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-894"
      - host: "pr-897-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-897"
      - host: "pr-906-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-906"
      - host: "pr-913-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-913"
      - host: "pr-915-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-915"
      - host: "pr-917-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-917"
      - host: "pr-918-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-918"
      - host: "pr-919-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-919"
      - host: "pr-923-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-923"
      - host: "pr-926-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-926"
      - host: "pr-927-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-927"
      - host: "pr-930-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-930"
      - host: "pr-931-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-931"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.stg.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-testnet.stg.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW, ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_mainnet"
  versions:
    - version: "pr-881"
      gitSha: "null"
    - version: "pr-894"
      gitSha: "null"
    - version: "pr-887"
      gitSha: "756a2df"
    - version: "pr-897"
      gitSha: "5a8f44b"
    - version: "pr-906"
      gitSha: "null"
    - version: "pr-876"
      gitSha: "8f4a113"
    - version: "pr-915"
      gitSha: "07e8ef6"
    - version: "pr-918"
      gitSha: "d376407"
    - version: "pr-923"
      gitSha: "null"
    - version: "pr-926"
      gitSha: "null"
    - version: "pr-927"
      gitSha: "null"
    - version: "pr-885"
      gitSha: "bd1331b"
    - version: "pr-913"
      gitSha: "2345bbc"
    - version: "pr-919"
      gitSha: "039e63e"
    - version: "pr-917"
      gitSha: "596d5c8"
    - version: "pr-930"
    - version: "pr-931"
