app:
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgBTocdiLiWJr9Dy8AbXQ4asaTZscNqCWBvpTfvGRS4rvulfgHD4icZaClODeKyPJpSUGfEYzamSECpLGVUQTbxtvcmoUVpe76zwX4nQcWlU7sAuniWsgDEVgwjoHHc1BDWunQDHrRSN8qbAJvfB21SAUyt1tupniQE0wOAJb4sCYSv2ctTVIywtlXOlzVYnEtfYRmcYesAfofgThyoA6+VzaP7KRa2roqXr3FVVCYYYEcRLf6dLSEiUpvQ1DHPN4dGzQ86i/YTcD5b5X+WTcnbqPimA2POioCNan3y6Eph4ZjHQ5aKLW219g1QUkmq5a3NKLbwyh4QokL6XBfXZnstWQdCsWanOkD05XlIRJ0qTv4lgVuBjTfMZ4NNMq9HFKkFegnLqNfA/60GzAixUkO8iRcAwDA4Dj/PCRcoEwyFREVUAgjTTeMwHDf2QvbaOrnGj8MAl8d5lbDCod9K8PGLtzbgI3pfEGviMsq/R/G++g+JjAmaG84G6cHJt6SHl0qyJT7/nwiVdshanyAgbyB8zbo2vc6vqNPues5aaiE1cWK4R0e+b8Y2OcCC01DY7yAuSd3s7WmduSZwQqH9QZxFyaB6zRaZE64LM3qrJ3ZnlYgKV1gIIJzBP6GuY0CJodaI/IRO/1Jeu3fY5GnB6Xnvw3mvwIPFEOJm7r4rDeYqrxFvv+rSt7ofrvjMy7byNJEyE2gLGzZZKD+iuk7/FzG5ZWrB4YPH1kCk+wNdSt8aObA=="
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    hosts:
      - host: "aescan.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
      - host: "dev.aescan.io"
        paths:
          - path: "/"
            version: "develop"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-testnet.dev.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW, ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_mainnet"
  versions:
    - {version: "develop", gitSha: "7f01ce2"}
