app:
  strategyType: "Recreate"
  service:
    port: "8080"
  image:
    tag: "develop"
    repository: "aeternity/aescan"
    pullPolicy: "Always"
  resources:
    limits:
      memory: 1500Mi
      cpu: 1500m
    requests:
      memory: 1500Mi
      cpu: 100m
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
