app:
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgB1KschjBvKXYugK8/3kDpfr4jWEafEm/FFIVjAmLJlI/pnzeaPSxh+Dtl5XiYuqcxohn8gAdBM38OiBULYGg65hzLrfZbacHOjt46IOr2sFzsiH7cOnZJbwQfoWr+i6lTb03eJVRB6Qiq/nV8WVOw96lhZ6kYJNU8js6ZwxGrwF3tJkztexDksXURTdh8chDcWO3LDet6xwSAqzUTDMAAdAXGsNCvzM1OT7aagFgunUsjYqXbz6H1EB0CewnFoX9InL81/E0I8QSuw0v+hfX874TGhGwxAhIN4bMn3v3GMp0zQbUucJeKUgsysXHpIRE7+hfZPkVdrPyGXbyuScgHA311T0WPUxyrFCZD+i88xArFOeGZfaxgoa+Pfh6hJrUoIMtTyfyHVVPIaJK+qzfCs5CllGfP7mzhD9DokOHqGHvJ+snvAHrX1/YNaEG+uU0PsznkRjHkhxpVnbg9bEOl4NeddjROdRgTb0UPXJlvYsJdt9STiqut5OfTmj32rZTOSReu5wwfiN+Px8Q0h4xwuaI4tZ/qnbNgjNGZ2PHNOBeiAy4kSwjd6Cn4MYEmOstzM258hsPjm90LDAl59L0KS8NII1RvTygCzGmKPL/xIos2rCiVyTMO5S68AwZWsc7ERMODNvSD5REXSwZai3wzB+lD5O09+aWCJ4t6cIUIjMZsKvnqjYF/HMvf3XGHgD7oDuscScZKezmRXSZrUqdTmIO7w7sMFGU/ZzpPySz5IYi/SjieN3QgagIdyaMqFuQdvhyKBM5s4uJi3EtdqBffY"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    hosts:
      - host: "aescan.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
      - host: "dev.aescan.io"
        paths:
          - path: "/"
            version: "develop"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-testnet.dev.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW, ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_mainnet"
  versions:
    - {version: "develop", gitSha: "9d4a9c9"}
