app:
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    hosts:
      - host: "aescan.dev.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "d487bce"}
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.dev.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-testnet.dev.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
