app:
  probes:
    liveness:
      enabled: "false"
    readiness:
      enabled: "false"
  ingress:
    hosts:
      - host: "aescan.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-590-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-590"
      - host: "pr-591-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-591"
      - host: "pr-601-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-601"
      - host: "pr-603-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-603"
      - host: "pr-607-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-607"
      - host: "pr-608-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-608"
      - host: "pr-611-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-611"
      - host: "pr-618-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-618"
      - host: "pr-619-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-619"
      - host: "pr-618-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-618"
      - host: "pr-618-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-618"
      - host: "pr-627-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-627"
      - host: "pr-631-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-631"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.stg.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-testnet.stg.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW, ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
  versions:
    - version: "pr-603"
      gitSha: "d054b93"
    - version: "pr-607"
      gitSha: "null"
    - version: "pr-627"
      gitSha: "076e45b"
    - version: "pr-608"
      gitSha: "3eaadaa"
    - version: "pr-631"
      gitSha: "null"
    - {version: "pr-619", gitSha: "2090364"}
    - {version: "pr-611", gitSha: "904e978"}
    - {version: "pr-618", gitSha: "e87328d"}
