app:
  image:
    tag: "0.0.1"
    repository: "aeternity/aescan"
    pullPolicy: "Always"
  resources:
    limits:
      memory: 750Mi
      cpu: 450m
    requests:
      memory: 500Mi
      cpu: 300m
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
