app:
  ingress:
    hosts:
      - host: "aescan.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-678-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-678"
      - host: "pr-681-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-681"
      - host: "pr-809-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-809"
      - host: "pr-810-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-810"
      - host: "pr-812-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-812"
      - host: "pr-819-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-819"
      - host: "pr-825-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-825"
      - host: "pr-831-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-831"
      - host: "pr-834-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-834"
      - host: "pr-835-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-835"
      - host: "pr-837-aescan.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-837"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.stg.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-testnet.stg.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW, ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_mainnet"
  versions:
    - version: "pr-810"
      gitSha: "null"
    - version: "pr-819"
      gitSha: "null"
    - version: "pr-825"
      gitSha: "null"
    - version: "pr-809"
      gitSha: "cad9c56"
    - version: "pr-823"
      gitSha: "dc95256"
    - version: "pr-812"
      gitSha: "7b6cba6"
    - version: "pr-681"
      gitSha: "2dce379"
    - version: "pr-678"
      gitSha: "e3c47a9"
    - version: "pr-834"
      gitSha: "117a8cb"
    - version: "pr-837"
      gitSha: "null"
    - {version: "pr-831", gitSha: "d96c811"}
    - {version: "pr-835", gitSha: "54105cb"}
