app:
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgBDQOh7Vp2tTd+ov0XyCkt8FilknMjqzwQRJgVJWCxiOu796qZyW0UOGO/4tCPu0Hs8CLQR+I6lEIJNcgVMMq3ZE8Wok3tfuQsezEG7gtp+v90JYo0a8AyHBzq/zisK5Ud5AfViFfJCNXkIEw5rSe3pYNBUISCOkWZZPjyD5ir+Bva/R1R33CDA8V1k+gx5866ohqAOJs5pv8m/nVloOYuKyXEvOOBQ+NKQmeDmA3zbooGtgzSrMjtwNQYwU3vcFjg12Jxg/05HjvI55NltKIFj83M41O8NSrmqmtWloBwMi1IiAVRCPRGLiRGozNKsKgA0G517nsrETsurCHI6Hal2YWdoPRovyvu7Jj6YnxQMOctvBD2a4YZ2gR7Kf0dwm7TBMdqNKTkrPBdDhtCj1UqnkWoLMm/e33F52X0iMp71Jxaeve7rjUMvnmFEd51Olt/mn/oQi2VdjLnJwD3WLPC2YWiXwOIfKhHaki0BPZEc70AinisnslN7JV56bY0xyXgNWEUuj6Z+adU+m6zZDQb3hlhdYsGmAk+nm27cTT4YoPC/4vWARv5nPdRa2ueVbH94bqaPUtFjKOTuaq+O47tvjBHyXVfrY8w216a6BUtXPynMYl3n4qGSOd+OUqLQMfB4+AVGH67zSsHYa39aITLh1eNTqp8JiET0Cyj2hO0g2hxTKAgd1kKrKgJD6P0BiuddP1OsyCcZH/Lw3tSj5Rvt+mbFxs9OAz9KeW58Tt6yqw=="
  ingress:
    hosts:
      - host: "aescan-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  requests:
    cpu: 300m
    memory: 450Mi
  limits:
    cpu: 4500m
    memory: 6000Mi
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://testnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-testnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9, ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway-testnet.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_uat"
  versions:
    - {version: "develop", gitSha: "7f01ce2"}
