app:
  image:
    repository: "aeternity/aescan"
    pullPolicy: "Always"
    tag: "0.0.1"
  resources:
    limits:
      memory: 2000Mi
      cpu: 1000m
    requests:
      memory: 1500Mi
      cpu: 500m
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
