app:
  service:
    port: 8080
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgB/NoG9VDpNMfRSE2b/wvgmndcZ2nz9B3OcHK5wNMwcS4NYyUHmgZT/dC+2dKBE9VBgII8fJ011UXehuurADfkxbn9WAie3m796GVW9rLcQnDKKVZTIflfBm8rtQSFIqd65u4SBFjibnyLc02oYxO+giWKKd4Kn/0rz4pRN82Dk8XuA6Djv9PkP1oIXk1e+kbDGR65qo2sistDeY7kzKXgR4xxromn5BKxSbxfia5CZPl7O5TLjJCNpDnhF3AakqWyqx7sH1diszXiqqGVKT8J9shcZ9JO9uJbqA9qWeAUBywrvv3NU0/KskP6AN7OR95gEdNnBT7UICHwuqSyUQGuWIZdYYq9PYK8EVATOisBkCuZZ/01BZviIjvz3vp2gBIKG3X4SFXBGIf4UFFs/iHS20KyRZQ0CieGq9mDw2JaO8VJdCrGyphAdzT44IK3gxQSJcPwGKDKe3eDUu4EAwlCzGpcsSw/uYl1nwkkjg1MXhMNF7niZeZ5GaoYxT1TGOCiG34cpcntXF8CV/9lYE64Va4PEDTWWZzOWGRqve24jGRtVZNIpxI8MHAIk6MCI4P30Xt6ZPhPhjbmB9CulTlUdPlOkz9TZwh+o9FLU5Y3OYYKFzlZC0KyKSQ5jQo2296Cclu0xCw7sirr4ZycFwbqNYBwBZQU8EBa6/6YM9YpGQXAG+H5VViOiw3bvv3yEeKKdTMWIyXlt0nVk1g9Usf6rSmXmp7a/KAiUBdqGndiylNG3gjJAIS1Vjlg3C2Fx0J38O8/b7gysOa28PsNwDypm"
  ingress:
    hosts:
      - host: "aescan-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
      - host: "testnet.aescan.io"
        paths:
          - path: "/"
  image:
    tag: 0.25.0
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "testnet.aescan.io"
    "NUXT_PUBLIC_SENTRY_DSN": "https://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw/v3"
    "NUXT_PUBLIC_NODE_URL": "https://testnet.aeternity.io/v3"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan.io"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-testnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
    "NUXT_PUBLIC_PLAUSIBLE_DOMAIN": "testnet.aescan.io"
    "NUXT_PUBLIC_PLAUSIBLE_API_HOST": "https://plausible.prd.service.aepps.com"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9, ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "NUXT_PUBLIC_NETWORK_ID": "ae_uat"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway-testnet.prd.service.aepps.com"
    "NUXT_PUBLIC_ENABLE_NODES": "true"
    "NUXT_PUBLIC_ENABLE_MARKET_STATS": "true"
    "NUXT_PUBLIC_ENABLE_MINING": "true"
