app:
  image:
    repository: "aeternity/aescan"
    pullPolicy: "Always"
  resources:
    limits:
      memory: 900Mi
      cpu: 500m
    requests:
      memory: 700Mi
      cpu: 300m
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
