app:
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgAfy0HJS3UA9Nf6xhzevyuA9JgtphU3S3bcFQ6ZMBs5jmE/AGbPSeqM8blgyBInxn1ZlTJqSwtmED4sTmVer8tH8foK+So4QdQBDxUu26F9PwyzVtUxQOkD/hl03q0Ltw7N3wuUB6ND6UfomXfFmQCZMsRN2pXfVwJ2iV5cK5wjcugb/WZGLKWIsu3uaOJXs9mv99oiiawZcLk8U974EcqzUisnFbkHGaenGHtJjFRW1CkpeMwDrE2GXQpwyNXlRfybQjXVEPxJGJu+o8m+hVaGZnvDmbagY0iASsU7D13GK7pHZHG80SkkBOFvMpAbQZeJExCM+YSZLgZ9zGArONJxKX1/RTY8JIZzX5j7eXd0ZJDpRHYONdz7tO5qZpvddrAj9HHDY2AG8D6MyNMvs65PEk6JDxNectk4ZAN5A+TjLZ3HNxYOWFfYv2TmX951wOJlz0GIDsOXOn3dtzdBE62WYDI0yLNzS6YOBA5CHgKMK7w/wkOG0Xpl69HjYDqOShVs8QZNr5QJr29a4NAHX/Sr1yb/mt3uYUKTwW/6kP0fdsSJv9/RypLCK/uAPNN/2nJ3D1WrMsu1M1eOVI8qfSvm3zTuPyl5zJtjHJlNxj6S0znPETFJu4RpziAXd4SzbwymoAW8Oq7UkO0NYSfMCXtSCu0zA7ycvOm2nYEjW0Xa3d+z7U9UAk1fy9H+d52H/0SV/+it+B8p/IjzGOxhKghdPUioQREjqtsGG2Mecmfury3aG7EkRCELGOScXm8wjqiPE9nH9C3Kh43yx1Y/4wpU"
  ingress:
    hosts:
      - host: "aescan-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  requests:
    cpu: 300m
    memory: 450Mi
  limits:
    cpu: 4500m
    memory: 6000Mi
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://testnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-testnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9, ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway-testnet.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_uat"
  versions:
    - {version: "develop", gitSha: "5190403"}
