app:
  strategyType: "Recreate"
  service:
    port: "8080"
  ingress:
    hosts:
      - host: "aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-1169-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1169"
      - host: "pr-1169-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1169"
      - host: "pr-1169-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1169"
      - host: "pr-1169-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1169"
      - host: "pr-1170-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1170"
      - host: "pr-1171-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1171"
      - host: "pr-1173-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1173"
      - host: "pr-1173-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1173"
      - host: "pr-1173-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-1173"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "testnet.aescan.io"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw/v3"
    "NUXT_PUBLIC_NODE_URL": "https://testnet.aeternity.io/v3"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan.io"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-testnet.stg.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9;ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway-testnet.stg.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_uat"
    "NUXT_PUBLIC_ENABLE_NODES": "true"
    "NUXT_PUBLIC_ENABLE_MARKET_STATS": "true"
    "NUXT_PUBLIC_ENABLE_MINING": "true"
  versions:
    - version: "pr-1170"
      gitSha: "null"
    - version: "pr-1171"
      gitSha: "null"
    - {version: "pr-1173", gitSha: "cbeb98c49c58b7bc0f417a7a62cd359488221f17"}
