app:
  ingress:
    hosts:
      - host: "aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-661-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-661"
      - host: "pr-672-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-672"
      - host: "pr-675-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-675"
      - host: "pr-677-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-677"
      - host: "pr-678-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-678"
      - host: "pr-681-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-681"
      - host: "pr-701-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-701"
      - host: "pr-717-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-717"
      - host: "pr-721-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-721"
      - host: "pr-724-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-724"
      - host: "pr-731-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-731"
      - host: "pr-741-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-741"
      - host: "pr-760-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-760"
      - host: "pr-784-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-784"
      - host: "pr-785-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-785"
      - host: "pr-789-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-789"
      - host: "pr-790-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-790"
      - host: "pr-791-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-791"
      - host: "pr-799-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-799"
      - host: "pr-801-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-801"
      - host: "pr-805-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-805"
      - host: "pr-808-aescan-testnet.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-808"
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.stg.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://testnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan.stg.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-testnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9, ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway-testnet.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_uat"
  versions:
    - version: "pr-661"
      gitSha: "adea654"
    - version: "pr-672"
      gitSha: "null"
    - version: "pr-675"
      gitSha: "null"
    - version: "pr-678"
      gitSha: "67c8bca"
    - version: "pr-677"
      gitSha: "d57a0b8"
    - version: "pr-681"
      gitSha: "a7d6866"
    - version: "pr-701"
      gitSha: "null"
    - version: "pr-731"
      gitSha: "null"
    - version: "pr-741"
      gitSha: "null"
    - version: "pr-724"
      gitSha: "54df231"
    - version: "pr-719"
      gitSha: "3ec68c7"
    - version: "pr-760"
      gitSha: "null"
    - version: "pr-721"
      gitSha: "b1848c4"
    - version: "pr-785"
      gitSha: "null"
    - version: "pr-789"
      gitSha: "null"
    - version: "pr-791"
      gitSha: "2954855"
    - version: "pr-784"
      gitSha: "16bccd5"
    - version: "pr-805"
      gitSha: "null"
    - version: "pr-808"
      gitSha: "null"
    - {version: "pr-801", gitSha: "812420f"}
    - {version: "pr-717", gitSha: "14ccd54"}
    - {version: "pr-799", gitSha: "674db19"}
    - {version: "pr-790", gitSha: "16716e7"}
