app:
  encValues:
    NUXT_PUBLIC_SENTRY_AUTH_TOKEN: "AgBrfzNdoySm6Rlm2v0NkVzCfOHZJWvjSCE5X1XwEXD6ombyLA/QE5Sgmwws5JFZJ2TRfGAdtOmbi+rKCBmFpHgbvKCNxhCvKE5ht7qesyjIHc9LXy/H1o+bxgmG/Aovi5LX9sDSIQL5zQ2rGmkBtSoDim9HCd1++qwKBk3tw1EyBlA7CdiZuMChacaoSxwQWAnm9H+tQ0zOuOdjvv26KSv1QstquXNvTRiGvsc71VvBWClmoZenhFx8L6alcwQQAXn9wPtpPVgJP31hvcMegAKSFjarHypAo6YQA+QQH/zJpiYszDjLR1xpZ5n69nAXnKHUod407Uy66xhPdvrypCNYItGwJSzBukJGLgbXyEYt/QqtpKV6aCMIggSOUNqX/BZEzk7cNXYJwZMWqVoLEqYih2gkmCLYACfmYYk4C0sfpktLSsrCM4i8s8Oj/K7sm2e3YzPSJMLG4y6Px/Fpre+8GTn1uruLQOpe1I/s36LvX17gI3cGRQLBjfGHIRnJ1yI3cn2uypGgosaj3cGQr+dRuJ1DaFTCMhUZ2ovxdMNd1HFvQaOGMqeGyoi8xbR6Lf5QbWzVLo8pJc4gpYKsxAtZ9HnEdurRspEPHVuiT+Q3A8F3HbZ0aCHGpB7hiLZJGrBBYPpZZ2jtsFL/BLO3XHmUeEiLAp1XMe6uGGDh0Wh7j+zDHyRGhqcro2uI+P4suXSHD0QIqiaq7eiNqcA7su8NdyoM84IKIVRjmzA6BGCkefVU9iW90Dq31/MdKLtFKoHS4KXypJzfhQq1zWAUC6V8"
  ingress:
    hosts:
      - host: "aescan-testnet.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  requests:
    cpu: 300m
    memory: 450Mi
  limits:
    cpu: 4500m
    memory: 6000Mi
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "http://dbb329d340904b2c8461a6d5bc362bd9@sentry.dev.service.aepps.com/2"
    "NUXT_PUBLIC_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://testnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://testnet.aeternity.io"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://testnet.aeternity.io/mdw/v2/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan.dev.service.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-testnet.prd.service.aepps.com"
    "NUXT_PUBLIC_AE_TOKEN_ID": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
    "NUXT_PUBLIC_SH_DEX_CONTRACTS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9, ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "NUXT_PUBLIC_CONTRACT_VERIFICATION_SERVICE_URL": "https://scv-gateway-testnet.dev.service.aepps.com"
    "NUXT_PUBLIC_NETWORK_ID": "ae_uat"
  versions:
    - {version: "develop", gitSha: "7d48260"}
