app:
  encValues:
    POSTGRES_PASSWORD: "AgBY3sy88u7EgHMuoUrM9iEjIPKcCeK3gJGoc7stcVv+AbwMOSFOSpHT/51qV6x1pk3EokbhJI0U8qeMiCU33OCCqeWdlost2Q3dIP39aGSfL3KVOCX6cUtYhhXRTgffCXV30JDgc4lc2umxvq08hGc2S4qVr4LoZrqkdd/nem6lOjvL7n9yZQU95mtDeE4xA2wcvewAm7nt6XziG+S+S7vtmvLTWzJG7I+zLmklFGh7UJOEX3vKl+88r0EuyD34tSwQkaXyTAde93EwIt0nk18p0maNxBwQnAOmolvz4nK2htJOn1L8GSERLLP/vq3jYNKAwRbV07UY/4sUhsarFiaJORyeKqMLOdbmcBc23rxXwVsWV3MWZlyharoeg90vapHMcqJjdc7Lfysda5Zy11YEbecphWElwkXUuZ/TdKqy5oH6hZXcxCQgnKlkdzKyJfXdlh+Q9suVdCyF3Tb2F1IsNTwh9BCSddw3u03irDlT0uzZs1rZ0VT7DTd9nuPIW7ri3B0q/J9tiXSELKhgCtAg1uM52BnrXMiRjmigYwOjrMmfLN4RFNkKRItxVAx6xI40D56+v9DNiVUdwx5WxdMHbf0GhjCRoEXF+oyFOM3NGv6yPDVF7Pxue8IKeIC7r8t53jH0V2g6FDo68RdS2LPJpGAVUF/WSfZ7oH4ao0RfAaqvOQemca/4PCXS08EcaK1+7MgbINSLHx8crR8="
    AUTHENTICATION_PASSWORD: "AgChEopWiBhkVCsHtb5VXpt96/lC+0vWQjgv3PUCPv3gay230Px4sf9e+iXGFkTxhGgo3Wt6Wq1CWEyeUKLvE+jMKarMKt03juIUD/ZyWvjvl5Mq/uOU5B9Hg2KtDGppO19u5WTwbqd6uMm0t6VzixIexdI2DiiN2N6AylFifBnahz0hRe/tw6cpX9+hEiPW2MZRMH1i/4AgaJZXP/xrzxJ3M88IUDOv6yyUb7ihDnq612pTne9e5CkN/SZW7XbqcbPMIYCccAC+TgR5qMNhD84gtLOFVhHbf3i5Ax43p65DIX8FVcDMDpTx+GjzdIFEtEgLJNtgKrPTCT80QuEYJfUeNzNSJKmbCFZGnxT/tR7dG2o84ZZa9E/uWfq4djYEHfvNjhqInom9X5QtddHT/IuoDInbB0BfQcfSTBYEjxRtCvEJ9Q9MfXNP3i6CWKUs2tj4LcQLdHepsLfBUzr70ssZ5loYMnuIa9QinAvGpzrlY8vaFaMrbkyqHFBkqyaMsZ5OV/PaN12DlVL4dGpF7ntX0tQvMUlRFWLljhXd1yhbDincvK1uWPMHDP9CamWwpRYY5QzekX17YpnWzESc361c7gPVpGakzNYWOlsoDM1r8XndDOTL/3Vigu5iTyzed9aoerHI20knTR+95FvYkAKTAFerpYNKRQRcHM9bT+0Ao8Sb4oYGDwH5xuIp5skS63TuE8tjAYqtCBDybik8Zsrd"
    PRIVATE_KEY: "AgBfRDZp+tGt7KoI/CLOgBkrPJs2gsM67FFgpjkUYpZHeOnyBtUhI6pgA81xjP2an8VZ2sJq9BfeLLcUeyR3gk9ob+jPAf4y+9XKks+YCiGnPjLCZAGQCpDAvW0RlIPzE8Nxpazk2Tdg5VUhbNG27iL2L9ho8muqr1KufZC0ed9Z7KbEABWnxxJcS2HqiADszYEjdP670ivzPOu6V+fvApzyvgS6x8fdMEglh/Q4423+fY6f8G9/1DKGFAAyeTzSA510dWdW22wDtYkGf0iMYOPEaJAntPjPGig4zDwjGS3n+Tw79SrJpc18NdbQtkDuxrLN+PFa00wMr4fLgYZj7mG3EwKLzOPv0K05tu8iPxf8jwoCvSdll5sKE8oOr7QuHfsA003pi4iVjU1GfEk90zTO9RkHepmumalXCOIOo2OrbD0k0qDrWROGuaUkNeyPZ9e/noyidQfPmK48tWmjHffPNgqM8Xd+Y7u+i+QFf16eIeJQQMXAvfS8/V0SjNsTSoVYVCH0V5Ny3V3DBY33mySuehW+16Y0edmrA5eqVC6+mbdyenLemyYz9Lw2xOjm0tlS2lm6vvmksCXkdjJbefIz0cyVTiYa33vicYzfhoqSgISzVbXQu0bt5Eu5PRds/WMwuykJHdE1Yu8P/hSTT6HmU0xT7+1muWQa4+GTyKFveU73A9GHO7WWBPc5ZsSRTG5uvSKynERPvMqV0QHV0cdct57jDHkk3x8ZXOIqB0NUl/o4UOadxfsIxWCO0raykVw0oh7RejzhMg/tO8XamMKDPBBck5oKZXOv9iJP4A8VJFIE3txN51jtuO4Q2tVGmeeLtwhjOnENQUMk8YJ75bP7a66Pnd56CDAB8er/zul1Yg=="
  env:
    "REDIS_HOST": "redis-master.redis"
    "REDIS_PORT": "6379"
    "NODE_URL": "https://mainnet.aeternity.io"
    "COMPILER_URL": "https://latest.compiler.aepps.com"
    "CONTRACT_V1_ADDRESS": "ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z"
    "CONTRACT_V3_ADDRESS": "ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb"
    "TOKEN_REGISTRY_ADDRESS": "ct_2n76BQCN3zNEjuEvHFNZtgyWPc5zizy47wNrUT3RHP2MrPKhbq"
    "ORACLE_CONTRACT_ADDRESS": "ct_7wqP18AHzyoqymwGaqQp8G2UpzBCggYiq7CZdJiB71VUsLpR4"
    "MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "IPFS_URL": "http://ipfs.prd.service.aepps.com:5001"
    "PUBLIC_KEY": "ak_HryHrgaVUSxezLQBfNENhptKeXk6tpg4kjWBk88nsU5RJvhNk"
    "AUTHENTICATION_USER": "admin"
    "NODE_ENV": "production"
    "WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/websocket"
    "ORACLE_GETTER_ADDRESS": "ct_anbp2U5VUsF6PkrX1ER1hSqj76Krpvqy97c5JBLmubBecCWui"
    "CONTRACT_V1_GETTER_ADDRESS": "ct_NR7Bd7j5LRdzvKZmrMagMkfxzG8ZPWseKQkdwWootpq4kAJY2"
    "CONTRACT_V3_GETTER_ADDRESS": "ct_2NdZ6PX9tZHWFhgcoYjthYNFF15qxjDwFSsNXRPeajEWazxkTo"
    "POSTGRES_USER": "superhero"
    "POSTGRES_DB": "superhero_backend"
    "POSTGRES_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "POSTGRES_SSL": "false"
  image:
    repository: aeternity/superhero-backend
    tag: "v3.1.13"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  service:
    port: 3000
  resources:
    limits:
      memory: 3500Mi
      cpu: 3
    requests:
      memory: 3500Mi
      cpu: 2
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: apps-superhero-backend-app-text-compression@kubernetescrd
    TextCompression: true
    hosts:
      - host: "superhero-backend-mainnet.prd.service.aepps.com"
        paths:
          - path: "/"
  persistence:
    enabled: true
    disks:
      - name: disk1
        storageClass: "hcloud-volumes"
        accessMode: "ReadWriteOnce"
        size: "50Gi"
        mountPath: "/app/traces"
      - name: disk2
        storageClass: "hcloud-volumes"
        accessMode: "ReadWriteOnce"
        size: "50Gi"
        mountPath: "/app/images"
  podSecurityContext:
    fsGroup: 65533
    runAsUser: 1001
    runAsGroup: 65533
