app:
  encValues:
    POSTGRES_PASSWORD: "AgAcT/ZwJu68T0mXlmpaKOyZKOCeYql/YfPjuoo42qxk0rY+LmHdpD9ElCx+vX1OxlYAXhkyfwebX6PSom6vSC2BnLWM/FUTzIB8h/c4RTSLgnU4RCT3hZyS1FffOTVmfbJsoLcntvNFooDicuCyzAqhBkYEhSO/9XU6m0VMpV+X8mGAQ6GO8YYr5lnEbLnd/UjZu5BglkhwwjorussAhNC5yMnByIEipw/ZdmyQLQu+XyITJF3mySnY18W9WuoDrufwqkqLsMht0kmGRsDPJdCkt5zcyu8sXb4Otbhsr/3QTXrnULlliItZUVh61vXvUpDHCn9p4vO+ugXVG3u5Bpo/j0IHYZINdTIxh0n7i7BpoX33+JSsBiW7xTrbT6v6Mye9YoagaJylQDBFtmr+F7YRXRleVAw+8m+E5QFORjdGU9NOJ1ApNIVY5L7hBVVqiq7+NRBiBib+idh0fVa8/U7HNAW8K+0szA2Jze7JXQWSQyLupJlpk7j8cSP1xi9r/pQkyOZJfxqm4bOaWqLk/8YzJEvjtsx8q/u1zV9gtBG3gxLf42kyYXgL0RCigPlYmsmWWSxOAYIkvZLD5UsU6f4aG5CzXER8CC6T6po2Z5Zkt2Yi+rcefDsgm6M2mKlqK0IcH9juASysdCH9x4RZK583FvUzmIZIKCXhvklKV/COxsZmuLqvomVFcJNDEAuxghOD4hrY+JKUvbCuXDg="
    AUTHENTICATION_PASSWORD: "AgBOP11JTuvLqPWWGTghj6PH3BEj4FjMgYzAJw5SxlGeNxtrFnL+cIvBdlZIJMjjAEiWY4f72WrkyTCioBmBgr8518OJclqoszvVqaKS7XNnGKN4SUMgCHvp5nbNvG7SxYkYgvKrqWSSP2DX8BELJ9A+xrhhgO5vQ6psNtuE3m85HfiDVsDohD/2vLesli2W4vB27NtaaD+FaIWkdXEBJAPbG+j/38efITHJ8G/zKbD+ED3SsVawCaKYG5L+fjFveC9Ct/GgRCORfdM+gB/7/CBRqrdXoEm+LhUfO21UEq5CotFHxLBvdB/nbywCu/hLebj9ZoMTTtIQZ6ELuZRbYWzCpbrsBoz/QGhz5ZdxFQdkne0K8VDQZC1mDZ73zF25ueipvVCxZi8D7cr+frxFuhGH/UzZlpcJffnzNtZxyJhooQTWZwfVHpDS23Zqxv6zRId/jw80RB0/iImCik19MEZlEOeG8bI4by+JVXADQSLbN2RoYIhDx2hdv1cyQVOhymHmVQ90aMl/c+ZaM5tw25KWbzFwgby0mckq14OV9y5N+99EVCwfztKRW+5ra91OPaKwUZX8rGUfjiqHQnYbQHm/9qrjxUW/rbV1P6CVJoi0lY2PI132Eu+os8A3qS8I3TzBF7RVXOYOncMy32zstnhNVm6bDngprakAf1kJCTQn5OvUUmvR4QLRVo7w+o8NDP7R9RJtzPEbIh2y4UdWfBGo"
    PRIVATE_KEY: "AgAN2zOx668LYkxuKIkOpHxpDGogyoTDAaZa5ckpNvNh+F+aVKqJDEcC3RbdeE2hCr51BMn3L8Bbr9QIXYoEGfWGpIifksYkxh3WzsH/16/wWkTcwbYyc2QTuETFlKNe7tobozlBQaPfYkEmnL8PCYIOOAmz//amFvxPprn5myCCCQHvur5PCDKHU0csyFuDzQdvrJQvzVWOqiPe94CibaIRg2iIedZv9EVeoLf86LKlG4nTcGiF51WVH8A/JMSlqy9UcxHNVPJw+cSGnqKzoQ4ziqTqxI7UV7oZ2dcaHx0WgGPuHbIbEH7BOb82a82FqNVAbwt+JUFBolBZG/k5rbH84Zyz38yMTCfbE+M6bj8+dn9vgxIA43G6VXo51CTYjL0zQofZ1psWgG64MHBaNPSbz/zF3y9x/L2yv8vCWQ02pJOlZPsdzuOm7NsN02FV4SV8cdaJHv1IMbqdHGWa1b9A4TrE9Sx5URBRK5CEh6e2ocZqYpXWmke8r2dA6JNP/6So9m8kRRF5EqFtNXrQVNSTejWd1TAdaY26ARDKLF1mhZHHCT/xjImN85Ivm8NoH2xqoLdg4rOjw1KRpq0i53+pPtwnqciKNRouXi8ZSeJ2dGwc6k1wcXwCauRPEo1DIhcNw1OFvfz+VrMKre9ekfSk+3BKYQgH2W0JJDJOc1A4k6gHmJGnmdbwcSDhOZP1ygxiiKK/eQwu86gPUhZRtuFbgx5XmTPW5fUN+lA3k4M8vWKKsDyvrwP+QsFAYmI5F7SZUCcdy3vIt0IyZKVjHSMzkJqE/fwOKEVBYf7WGI6iCqwvy/H6Hau8YReX/pwttgz4Wq+OT/+EzhnRDWawUbKr0gEXlNVOS1myjuvrMM+iCg=="
  env:
    "REDIS_HOST": "192.168.2.4"
    "REDIS_PORT": "6379"
    "NODE_URL": "https://mainnet.aeternity.io"
    "COMPILER_URL": "https://latest.compiler.aepps.com"
    "CONTRACT_V1_ADDRESS": "ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z"
    "CONTRACT_V3_ADDRESS": "ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb"
    "TOKEN_REGISTRY_ADDRESS": "ct_2n76BQCN3zNEjuEvHFNZtgyWPc5zizy47wNrUT3RHP2MrPKhbq"
    "ORACLE_CONTRACT_ADDRESS": "ct_7wqP18AHzyoqymwGaqQp8G2UpzBCggYiq7CZdJiB71VUsLpR4"
    "MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "IPFS_URL": "http://ipfs.stg.service.aepps.com:5001"
    "PUBLIC_KEY": "ak_HryHrgaVUSxezLQBfNENhptKeXk6tpg4kjWBk88nsU5RJvhNk"
    "AUTHENTICATION_USER": "admin"
    "NODE_ENV": "production"
    "WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/websocket"
    "ORACLE_GETTER_ADDRESS": "ct_anbp2U5VUsF6PkrX1ER1hSqj76Krpvqy97c5JBLmubBecCWui"
    "CONTRACT_V1_GETTER_ADDRESS": "ct_NR7Bd7j5LRdzvKZmrMagMkfxzG8ZPWseKQkdwWootpq4kAJY2"
    "CONTRACT_V3_GETTER_ADDRESS": "ct_2NdZ6PX9tZHWFhgcoYjthYNFF15qxjDwFSsNXRPeajEWazxkTo"
    "POSTGRES_USER": "superhero"
    "POSTGRES_DB": "superhero_backend"
    "POSTGRES_HOST": "pg-superhero-backend.stg.service.aepps.com"
    "POSTGRES_SSL": "false"
  image:
    repository: aeternity/superhero-backend
    tag: "latest"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  service:
    port: 3000
  resources:
    limits:
      memory: 3500Mi
      cpu: 1000m
    requests:
      memory: 2000Mi
      cpu: 500m
  ingress:
    enabled: true
    hosts:
      - host: "superhero-backend.stg.service.aepps.com"
        paths:
          - path: "/"
