
app:
  encValues:
    PG_PASSWORD: "AgCMmcM8SzDjodcbDQ/23vRM8kU/ws6zIUlrSnkq/DbGgvVsQo7gJZKNWpI0SHmgQVKlQVdjlueaRRMb+cZwvHMy71EA4B8SloKHNACIv9VNzv86fLJ3TAwQ8mR7dbzvYo9pZigQH09ZaAfqm4/XvsY5Aara0IqKSl+c92ueNJF/cNp8xKRtYTf6tyOXXH1YHXeXucWn2iiXuKLF4ZF0INdSFhhKPU37QB+zuvLo0NcMaiIOzhk3f7XpKLpIXVqXU30Kbk9eCr+rn971007QomN5Pe6vK3JuZvZbyGXst81TAeKrVq7eC5QljztaCrKZBbvM2fk3ALC/oTJdiOBI4mzOzzxM5e8XUpHLi5OKIQxQgBlPD8t7ALSjARZysvZndXJniJCl/tRIcmoQpIl80L0nw22dtfi9+7txOZ53lPgH26BMI1hpUBRVfT18gN+K93RvZFiGm67l0qVNALYR51TbXTu5m/LmjQZ4eRx8Cryzo4gxsneYBG+mwC9YwUer5U+aKcgAqkMpBQiXhL6JRqmEgH+DXHfSgJ2IVjummdcC1SW72QH1kyZN4N94n9ov/FwqSREUL5IeEpfhoi6hwPz4+T0J2LJCVk0vRiBvnKPD71wpiMP7ny9w0/vejcW1cT/HXzune49a+eI1boXGUAyutyRwFKt+eFQdgZUraxsb81BmTNIs1oENuBfwHtFXI01L6jAc7tU1Ed+x"
  image:
    repository: aeternitybot/ga-multisig-backend
    tag: v1.1.0
    pullPolicy: "Always"
  service:
    port: 3000
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  ingress:
    enabled: true
    #annotations:
      #traefik.ingress.kubernetes.io/router.middlewares: ga-multisig-backend-mainnet-app-text-compression@kubernetescrd
    TextCompression: true
    hosts:
      - host: "ga-multisig-backend-mainnet.dev.service.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_DB": "ga-multisig-backend-mainnet"
    "PG_PORT": "5432"
    "PG_USER": "ga-multisig-backend"
    "PG_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "MIDDLEWARE_URL": https://mainnet.aeternity.io/mdw
    "NODE_URL": https://mainnet.aeternity.io
