
app:
  encValues:
    PG_PASSWORD: "AgCbJoY3WHkf7WTFQRx/E5hj2UFMMid5Vz7u/MDNm/7grsoQ3Chq9IXDySUro77fKwkVT8cOBt8HuKBnYd8d5S0INfeqv7DbblHkEXkUe9dMcCn8hFlqGy33X88Ha6/OBKe8XjxuYgcSAn3+oT9Gm+k8hSr4tZMUdKZrkq6z8ZQ30ZUNPLF5vxwx5HQ/4qZjBEfl8t7luHbLiuOGWemFfVi1JosvaLXAcO05EkvrrBNQnNa60LLhP3TFP/Kdz4Zx7jD4Kr/EEPQNaPc+vOpCBm9/nhHswdWVObT1qDoXXHiH7Ff80T9pAema6QEoW2s36O3YY3UW5FzKoCB38l1QM9RT46DeN2qdk2WWODM7yqrxITLSUmDfjIZ2E/oPXWeH7eAo0MvrMN4xb2vLmEhD6Zumd/EmGa2h+lHsZL42gg/nzoKN9srWJ5xFJ/WSGw+7dU7xZqmKW2PWkMO2SZv2P5VyYqYIQg17mmrGnCNX9zq/qpbQvvElhINIzKWiqwvEDIu2AJr/P4g5+5y9PvZwazir7rQQepoUJHckF6j3o8n6DTwIKw7vnrWS7L/LzNEwBwYgI3KTmvSusJ4mtuQQUysgc+nyhahZE1CxdTpc8arfZuie39YjvpIXVl07tn0dF/S8QdDE5BrPEs8ri35ePs3iSM5+eaVv3NdsG362sjWS8XTSI5SpcdnvTEEH7GvxKbGvfbo7B5hLtPE"
  image:
    repository: aeternitybot/ga-multisig-backend
    tag: v1.1.0
    pullPolicy: "Always"
  service:
    port: 3000
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  ingress:
    enabled: true
    hosts:
      - host: "ga-multisig-backend-mainnet.dev.service.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_DB": "ga-multisig-backend-mainnet"
    "PG_PORT": "5432"
    "PG_USER": "ga-multisig-backend"
    "PG_HOST": "pg-superhero-backend.dev.service.aepps.com"
    "MIDDLEWARE_URL": https://mainnet.aeternity.io/mdw
    "NODE_URL": https://mainnet.aeternity.io
