app:
  nameOverride: superhero-ui
  image:
    repository: "aeternity/superhero-ui-web"
    tag: "latest"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
  resources:
    limits:
      memory: 100Mi
      cpu: 200m
    requests:
      memory: 100Mi
      cpu: 50m
