app:
  image:
    repository: "aeternity/aepp-lqty"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  ingress:
    hosts:
      - host: "lqty.dev.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "205db21"}
