app:
  image:
    tag: "develop"
    repository: "aeternity/aepp-lqty"
    pullPolicy: "Always"
  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 300Mi
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  serviceMonitor:
    enabled: false
