app:
  image:
    repository: "aeternitybot/test-repo"
    pullPolicy: "Always"
  ingress:
    hosts:
      - host: "test-repo.stg.aepps.com"
        paths:
          - path: "/"
  versions:
    - {version: "pr-182", gitSha: "9c72bf5"}
    - {version: "pr-186", gitSha: "05b386d"}
