app:
  image:
    repository: "aeternitybot/test-repo"
    pullPolicy: "Always"
  ingress:
    hosts:
      - host: "test-repo.stg.aepps.com"
        paths:
          - path: "/"
      - host: "pr-178-test-repo.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-178"
  versions:
    - version: "pr-178"
