app:
  image:
    repository: "aeternitybot/test-repo"
    pullPolicy: "Always"
  ingress:
    hosts:
      - host: "test-repo.stg.aepps.com"
        paths:
          - path: "/"
      - host: "pr-178-test-repo.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-178"
      - host: "pr-180-test-repo.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-180"
      - host: "pr-179-test-repo.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-179"
  versions:
    - version: "pr-178"
    - version: "pr-180"
    - version: "pr-179"
