app:
  ingress:
    hosts:
      - host: "state-channel-demo-backend.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-265-state-channel-demo-backend.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-265"
      - host: "pr-269-state-channel-demo-backend.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-269"
  versions:
    - version: "pr-265"
      gitSha: "null"
  env:
    "NODE_URL": "https://testnet.aeternity.io"
    "WS_URL": "wss://sdk-testnet.aepps.com/channel"
    "NODE_ENV": "testnet"
