app:
  nameOverride: simplex-integration
  image:
    repository: "aeternity/simplex-integration"
    tag: "latest"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "simplex-integration.prd.service.aepps.com"
        paths:
          - path: "/"
  serviceMonitor:
    enabled: false
