app:
  ingress:
    hosts:
      - host: "simplex-integration.prd.aepps.com"
        paths:
          - path: "/"
    tls:
      - hosts:
        - "simplex-integration.prd.aepps.com"
        secretName: simplex-integration-cert
